Added initial delete_user

diff --git a/modules/bash/system/functions b/modules/bash/system/functions
--- a/modules/bash/system/functions
+++ b/modules/bash/system/functions
@@ -118,6 +118,81 @@ ensure_user_exists()
   fi
 }
 
+delete_user()
+{
+  local _token _group
+  # parse arguments
+  while [[ $# -gt 0 ]] ; do
+    _token="$1" ; shift
+
+    case "${_token}" in
+      group)
+        _group="${1}" ; shift
+        ;;
+      with)
+        continue # Syntatic sugar, ignore, next!
+        ;;
+      from)
+        _source="${1}" ; shift
+        ;;
+      --force)
+        _force_flag=1
+        ;;
+
+      *)
+        if [[ -z "${_group}" ]] ; then
+          _group="${_token}"
+          break
+        fi
+        ;;
+    esac
+  done
+
+  if [[ $UID -eq 0 ]] ; then
+    (
+    case "$(uname)" in
+      "OpenBSD")
+        groupdel "$package_user"
+        userdel -g "$package_user" "$package_user"
+        ;;
+
+      "FreeBSD")
+        pw groupdel -q "$package_user"
+        ;;
+
+      "Linux")
+        userdel "${package_user}"
+      ;;
+
+      "Darwin")
+        gid="501" #only gids > 500 show up in user preferences
+
+        #Find an open gid
+        while true; do
+          name=$(dscl . search /groups PrimaryGroupID $gid | cut -f1 -s)
+          if [ -z "$name" ] ; then
+            break
+          fi
+          gid=$[$gid +1]
+        done
+
+        #Create the group
+        dscl . -delete "/Users/${package_user}" PrimaryGroupID "$gid" # UserShell /bin/bash
+        dscl . -delete "/Groups/$package_user"
+        dscl . -delete "/Groups/$package_user" gid "$gid"
+      ;;
+
+      "SunOS")
+        groupdel "$package_user"
+        userdel "$package_user"
+        ;;
+    esac
+    ) || true # Ignore failures with this for now...
+  else
+    fail "Users and groups may be manipulated only by the super user (root) via su or sudo."
+  fi
+}
+
 running_as_root() { [[ $UID -eq 0 ]] ; }
 running_as_superuser() { [[ $UID -eq 0 ]] ; }
 running_as_user() { [[ $UID -ne 0 ]] ; }
