Updated service services

diff --git a/services/service/edit b/services/service/edit
--- a/services/service/edit
+++ b/services/service/edit
@@ -1,1 +1,23 @@
 #!/usr/bin/env bash
+
+if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi
+
+result=0 ; service="$1" ; shift
+releases_url="${releases_url:-$($scripts_path/db "$config_path/bdsm" "releases_url")}"
+service_url="${service_url:-$($scripts_path/db "$config_path/bdsm" "service_url")}"
+if [[ -z "$service" ]] ; then
+  "$scripts_path"/log "error" "A service must be specified." ; exit 1
+fi
+# TODO: Should we allow user installs?...
+if [[ "root" != "user" ]] ; then
+  "$scripts_path"/log "error" "Services must be installed as root." ; exit 1
+fi
+
+if [[ -z "$service" ]] ; then
+  $scripts_path/log "error" "A service must be specified to edit." ; exit 1
+else
+  cd "$services_path/$service/"
+  ${EDITOR:-vi} .
+fi
+
+exit $?
diff --git a/services/service/install b/services/service/install
--- a/services/service/install
+++ b/services/service/install
@@ -3,10 +3,11 @@
 if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi
 
 result=0 ; services="$1" ; shift
-
 releases_url="${releases_url:-$($scripts_path/db "$config_path/bdsm" "releases_url")}"
 service_url="${service_url:-$($scripts_path/db "$config_path/bdsm" "service_url")}"
-
+if [[ -z "$services" ]] ; then
+  "$scripts_path"/log "error" "A service must be specified." ; exit 1
+fi
 # TODO: Should we allow user installs?...
 if [[ "root" != "user" ]] ; then
   "$scripts_path"/log "error" "Services must be installed as root." ; exit 1
@@ -15,10 +16,6 @@ fi
 # TODO: Allow ',' separated service list.
 
 mkdir -p "$src_path/bdsm/"
-
-releases_url="${releases_url:-$($scripts_path/db "$config_path/bdsm" "releases_url")}"
-service_url="${service_url:-$($scripts_path/db "$config_path/bdsm" "service_url")}"
-
 
 for service in ${services//,/ } ; do
 
diff --git a/services/service/uninstall b/services/service/uninstall
--- a/services/service/uninstall
+++ b/services/service/uninstall
@@ -3,16 +3,16 @@
 if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi
 
 result=0 ; services="$1" ; shift
+releases_url="${releases_url:-$($scripts_path/db "$config_path/bdsm" "releases_url")}"
+service_url="${service_url:-$($scripts_path/db "$config_path/bdsm" "service_url")}"
 if [[ -z "$services" ]] ; then
   "$scripts_path"/log "error" "A service must be specified." ; exit 1
 fi
-
-releases_url="${releases_url:-$($scripts_path/db "$config_path/bdsm" "releases_url")}"
-service_url="${service_url:-$($scripts_path/db "$config_path/bdsm" "service_url")}"
 # TODO: Should we allow user installs?...
 if [[ "root" != "user" ]] ; then
-  "$scripts_path"/log "error" "Services must be installed as root." ; exit 1
+  "$scripts_path"/log "error" "Services must be uninstalled as root." ; exit 1
 fi
+
 
 for service in ${services//,/ } ; do
   if [[ -d "$services_path/$service" ]] ; then
diff --git a/services/service/update b/services/service/update
--- a/services/service/update
+++ b/services/service/update
@@ -3,12 +3,14 @@
 if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi
 
 result=0 ; services="$1" ; shift
-
 releases_url="${releases_url:-$($scripts_path/db "$config_path/bdsm" "releases_url")}"
 service_url="${service_url:-$($scripts_path/db "$config_path/bdsm" "service_url")}"
-
 if [[ -z "$services" ]] ; then
   "$scripts_path"/log "error" "A service must be specified." ; exit 1
+fi
+# TODO: Should we allow user installs?...
+if [[ "root" != "user" ]] ; then
+  "$scripts_path"/log "error" "Services must be updated as root." ; exit 1
 fi
 
 for service in ${services//,/ } ; do
