Refactored the variables module.

diff --git a/core/ext/modules/shell/variables/dsl b/core/ext/modules/shell/variables/dsl
--- a/core/ext/modules/shell/variables/dsl
+++ b/core/ext/modules/shell/variables/dsl
@@ -36,19 +36,16 @@
 #
 first()
 {
-  # Store the parameters in an array variable
   local _array=("$@")
 
   # If the array is nonempty, print the first element out.
   # Otherwise no parameters were passed in; this is a programming error.
   # Send a failure message which also triggers a backtrace enabling the
   # developer to quickly pinpoint and fix their error.
-  if (( ${#_array[@]} > 0 ))
-  then
-    printf "%s" "${_array[0]}"
-  else
+  (( ${#_array[@]} > 0 )) ||
     fail "No parameters given; cannot return the first one."
-  fi
+
+  printf "%s" "${_array[0]}"
 }
 
 #
@@ -94,12 +91,10 @@ last()
   # Otherwise no parameters were passed in; this is a programming error.
   # Send a failure message which also triggers a backtrace enabling the
   # developer to quickly pinpoint and fix their error.
-  if (( ${#_array[@]} > 0 ))
-  then
-    printf "%s" "${_array[$((${#_array[@]} - 1))]}"
-  else
+  (( ${#_array[@]} > 0 )) ||
     fail "No parameters given; cannot return the last one."
-  fi
+
+  printf "%s" "${_array[$((${#_array[@]} - 1))]}"
 }
 
 #
@@ -141,46 +136,26 @@ last()
 #
 match()
 {
-  # Store the first parameter into the value variable.
-  local _value="$1"
+  local _value="${1:-}"
+  shift || fail "A value and regex must be specified in order to match."
 
-  # If the varable is nonempty
-  if variable_is_nonempty _value
-  then
-    # Remove the value from the parameters list and set the regex variable
-    # to the next parameter.
-    shift
-    local _regex="$1"
+  local _regex="${1:-}"
+  shift || fail "A regex must be specified in order to match ${_value} against it."
 
-    # if the regex variable is nonempty
-    if variable_is_nonempty _regex
-    then
-      # Ensure that extended shell globbing (bash) is turned on.
-      shopt -s extglob
-      # Use a case statement for pattern matching the regex against the value.
-      # If the value matches the given regex pattern then return true, 0.
-      # Otherwise the value does not match the given regex pattern,
-      # so return false, 1.
-      case "${_value}" in
-        (${_regex})
-          return 0
-          ;;
-        (*)
-          return 1
-          ;;
-      esac
-    else
-      # Otherwise, no regex parameter was passed in; this is a programming error.
-      # Send a failure message which also triggers a backtrace enabling the
-      # developer to quickly pinpoint and fix their error.
-      fail "A regex must be specified in order to match ${_value} against it."
-    fi
-  else
-    # Otherwise no parameters were passed in; this is a programming error.
-    # Send a failure message which also triggers a backtrace enabling the
-    # developer to quickly pinpoint and fix their error.
-    fail "A value and regex must be specified in order to match."
-  fi
+  # Ensure that extended shell globbing (bash) is turned on.
+  shopt -s extglob
+  # Use a case statement for pattern matching the regex against the value.
+  # If the value matches the given regex pattern then return true, 0.
+  # Otherwise the value does not match the given regex pattern,
+  # so return false, 1.
+  case "${_value}" in
+    (${_regex})
+      return 0
+      ;;
+    (*)
+      return 1
+      ;;
+  esac
 }
 
 #
@@ -222,45 +197,25 @@ match()
 #
 ematch()
 {
-  # Store the first parameter into the value variable.
-  local _value="$1"
+  local _value="${1:-}"
+  shift || fail "A value and regex must be specified in order to match."
 
-  # If the variable is nonempty
-  if variable_is_nonempty _value
-  then
-    # Remove the value from the parameters list and set the regex variable
-    # to the next parameter.
-    shift
-    local _regex="$1"
+  local _regex="${1:-}"
+  shift || fail "A regex must be specified in order to match ${_value} against it."
 
-    # If the regex variable is nonempty
-    if variable_is_nonempty _regex
-    then
-      # Use grep for extended regexp.
-      echo "${_value}" | grep -qE "${_regex}"
-      local result=$?
-      case $result in
-        0|1)
-          # 0 & 1 are correct results.
-          return $result
-          ;;
-        *)
-          # Any other result means an error in grep.
-          fail "grep returned unknown code: $result"
-          ;;
-      esac
-    else
-      # Otherwise, no regex parameter was passed in; this is a programming error.
-      # Send a failure message which also triggers a backtrace enabling the
-      # developer to quickly pinpoint and fix their error.
-      fail "A regex must be specified in order to match ${_value} against it."
-    fi
-  else
-    # Otherwise, no parameters were passed in; this is a programming error.
-    # Send a failure message which also triggers a backtrace enabling the
-    # developer to quickly pinpoint and fix their error.
-    fail "A value and regex must be specified in order to match."
-  fi
+  # Use grep for extended regexp.
+  echo "${_value}" | grep -qE "${_regex}"
+  local result=$?
+  case $result in
+    0|1)
+      # 0 & 1 are correct results.
+      return $result
+      ;;
+    *)
+      # Any other result means an error in grep.
+      fail "grep returned unknown code: $result"
+      ;;
+  esac
 }
 
 #
@@ -312,26 +267,14 @@ variables_must_be_nonempty()
 {
   local _variable _variables=("$@")
 
-  if (( ${#_variables[@]} > 0 ))
-  then
-    for _variable in "${_variables}"
-    do
-      if variable_is_nonempty "${_variable}"
-      then
-        continue
-      else
-        # One of the variables was not set; this is a programming error.
-        # Send a failure message which also triggers a backtrace enabling the
-        # developer to quickly pinpoint and fix their error.
-        fail "Required variable '$_variable' is not set."
-      fi
-    done
-  else
-    # Otherwise no parameters were passed in; this is a programming error.
-    # Send a failure message which also triggers a backtrace enabling the
-    # developer to quickly pinpoint and fix their error.
+  (( ${#_variables[@]} > 0 )) ||
     fail "Cannot ensure variables are nonempty, as no variables were given."
-  fi
+
+  for _variable in "${_variables}"
+  do
+    variable_is_nonempty "${_variable}" ||
+      fail "Required variable '$_variable' is not set."
+  done
 }
 
 #
@@ -372,22 +315,11 @@ variables_must_be_nonempty()
 #
 variable_is_nonempty()
 {
-  # Store the first parameter, which should be the variable name, in the
-  # variable variable :)
   local _variable="${1:-}"
 
-  # If the variable name is nonempty
-  if [[ -n "${_variable}" ]]
-  then
-    # If the evaluation of a nonempty test with the variable name used [huh???]
-    eval "[[ -n \"\${${_variable}:-}\" ]]"
-  else
-    # Otherwise no parameters were passed in; this is a programming error.
-    # Send a failure message which also triggers a backtrace enabling the
-    # developer to quickly pinpoint and fix their error.
-    fail "Cannot check if variable is nonempty; no variable was given."
-  fi
+  shift || fail "Cannot check if variable is nonempty; no variable was given."
 
+  eval "[[ -n \"\${${_variable}:-}\" ]]"
 }
 
 #
@@ -428,27 +360,17 @@ variable_is_nonempty()
 #
 variable_is_empty()
 {
-  # Store the first parameter, which should be the variable name, in the
-  # variable variable :)
   local _variable="${1:-}"
+  shift || fail "Cannot check if variable is empty, as no variable was given."
 
-  # If the variable name is nonempty
-  if [[ -n "${_variable}" ]]
+  # If the evaluation of an empty test with the variable name used...
+  if eval "[[ -z \"\${${_variable}:-}\" ]]"
   then
-    # If the evaluation of an empty test with the variable name used...
-    if eval "[[ -z \"\${${_variable}:-}\" ]]"
-    then
-      # ...is true, then return true, 0.
-      return 0
-    else
-      # ...is false, then return false, 1.
-      return 1
-    fi
+    # ...is true, then return true, 0.
+    return 0
   else
-    # Otherwise no parameters were passed in; this is a programming error.
-    # Send a failure message which also triggers a backtrace enabling the
-    # developer to quickly pinpoint and fix their error.
-    fail "Cannot check if variable is empty, as no variable was given."
+    # ...is false, then return false, 1.
+    return 1
   fi
 }
 
@@ -496,26 +418,22 @@ variables_are_nonempty()
   local _variable _variables=("$@")
 
   # If the number of variable names passed in is nonzero
-  if (( "${#_variables[@]}" > 0 ))
-  then
-    # For each variable passed in:
-    for _variable in "${_variables}"
-    do
-      # Evaluate an 'is empty' test using the variable name.
-      if eval "[[ -z \"\${${_variable}:-}\" ]]"
-      then
-        # If any of the variables are empty, return false, 1.
-        return 1
-      fi
-    done
-    # If we get to this point, then all variables were set; return true, 0
-    # to the caller.
-    return 0
-  else
-    # Otherwise, no parameters were passed in; this is a programming error.
-    # Send a failure message which also triggers a backtrace enabling the
-    # developer to quickly pinpoint and fix their error.
+  (( "${#_variables[@]}" > 0 )) ||
     fail "Cannot check if variables are nonempty as no variables were given."
-  fi
+
+  # For each variable passed in:
+  for _variable in "${_variables}"
+  do
+    # Evaluate an 'is empty' test using the variable name.
+    if eval "[[ -z \"\${${_variable}:-}\" ]]"
+    then
+      # If any of the variables are empty, return false, 1.
+      return 1
+    fi
+  done
+
+  # If we get to this point, then all variables were set; return true, 0
+  # to the caller.
+  return 0
 }
 
