More updates and refinements.

diff --git a/extensions/rails/setup b/extensions/rails/setup
--- a/extensions/rails/setup
+++ b/extensions/rails/setup
@@ -2,17 +2,69 @@
 
 if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi
 
+
+while [ $# -gt 0 ] ; do
+  token="$1" ; shift
+  case "$token" in
+    --repo)        repo="$1"     ; shift ;;
+    --database)    database="$1" ; shift ;;
+    --environment) environment="$1" ; shift ;;
+    *)
+      echo "rails setup: unrecognized argument(s) $*"
+  esac
+done
+
 #
 # Sanity checks
 #
 if [[ "root" = $(whoami) ]] ; then
   $scripts_path/log "error" "bdsm extension $extension must be run as the project user and NOT root." ; exit 1
 fi
-for variable in project environment; do
-  if [[ -z "$variable" ]] ; then
-    $scripts_path/log "error" "$variable must be set for extension $extension." ; exit 1
+
+mkdir -p $shared_path
+
+if [[ -z "$project" ]] ; then
+  $scripts_path/log "error" "$variable must be set for extension $extension." ; exit 1
+else
+  if ! awk "/^project/" "$HOME/.bash_profile" ; then
+    echo "export project=\"$(user)\"" >> $HOME/.bdsmrc
   fi
-done
+fi
+
+if [[ -z "$environment" ]] ; then
+  $scripts_path/log "error" "$variable must be set for extension $extension." ; exit 1
+else
+  if ! awk "/^environment/" "$HOME/.bash_profile" ; then
+    echo "export environment=\"$environment\"" >> $HOME/.bdsmrc
+  fi
+
+  if ! awk "/^RAILS_ENV/" "$HOME/.bash_profile" ; then
+    echo "export RAILS_ENV=\"$environment\"" >> $HOME/.bdsmrc
+  fi
+fi
+
+if [[ ! -z "$repo" ]] ; then
+  if ! awk "/^repo/" "$HOME/.bash_profile" ; then
+    echo "export repo=\"$repo\"" >> $HOME/.bdsmrc
+  fi
+
+  cd $shared_path
+  if [[ "$scm" = "git" ]] || (echo $repo | awk "/git/") ; then
+    if [[ ! -d "$shared_path/$project/.git" ]] ; then
+      git clone $repo $project
+    fi
+  elif [[ "$scm" = "svn" ]] || (echo $repo | awk "/svn/") ; then
+    if [[ ! -d "$shared_path/$project/.svn" ]] ; then
+      svn checkout $repo $project
+    fi
+  elif [[ "$scm" = "hg" ]] || (echo $repo | awk "/hg/") ; then
+    if [[ ! -d "$shared_path/$project/.hg" ]] ; then
+      hg clone $repo $project
+    fi
+  else
+    echo -e "ERROR: repo type not known, expecting {git,svn,hg} in the repo url."
+  fi
+fi
 
 for dir in config log pids sockets "public/assets" tmp  ; do
   mkdir -p "$project_path/shared/$dir"
@@ -22,17 +74,6 @@ done
 # Ensure the .bdsmrc file and the profiles are setup properly.
 #
 touch $project_path/shared/config/database.yml $project_path/.bash_profile
-if ! awk "/^project/" "$HOME/.bash_profile" ; then
-  echo "export project=\"$(user)\"" >> $HOME/.bdsmrc
-fi
-
-if ! awk "/^environment/" "$HOME/.bash_profile" ; then
-  echo "export environment=\"production\"" >> $HOME/.bdsmrc
-fi
-
-if ! awk "/^RAILS_ENV/" "$HOME/.bash_profile" ; then
-  echo "export RAILS_ENV=\"\$environment\"" >> $HOME/.bdsmrc
-fi
 
 if [[ ! -z "$database" ]] ; then
   if ! awk "/^database/" "$HOME/.bash_profile" ; then
diff --git a/extensions/unicorn/setup b/extensions/unicorn/setup
--- a/extensions/unicorn/setup
+++ b/extensions/unicorn/setup
@@ -1,18 +1,17 @@
 #!/usr/bin/env bash
 
-if [[ ! -z "$HOME/.bashrc" ]] ; then source "$HOME/.bashrc" ; fi
+if [[ -s "$HOME/.bashrc" ]] ; then source "$HOME/.bashrc" ; fi
+if [[ -s "$HOME/.rvm/scripts/rvm" ]] && [[ -z "$rvm_loaded_flag" ]] ; then source "$HOME/.rvm/scripts/rvm" ; fi
 
 if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi
 
-cd $current_path
-if [[ ! -z ".rvmrc" ]] ; then source ".rvmrc" ; fi
+if [[ -s "$current_path/.rvmrc" ]] ; then source "$current_path/.rvmrc" ; fi
 
-if [[ -s $bdsm_dir/unicorn/templates/unicorn.rb ]] ; then
-  echo -e "ERROR: $bdsm_dir/unicorn/templates/unicorn.rb template is missing."
+if [[ -s "$extensions_path/unicorn/templates/unicorn.rb" ]] ; then
+  if [[ ! -d "$shared_path/config/" ]] ; then mkdir -p $shared_path/config/ ; fi
+  cp "$extensions_path/unicorn/templates/unicorn.rb" "$shared_path/config/"
+  exit $?
+else
+  echo -e "ERROR: $extensions_path/unicorn/templates/unicorn.rb template is missing."
   exit 1
 fi
-
-mkdir -p $shared_path/config/
-
-cp $bdsm_dir/unicorn/templates/unicorn.rb $shared_path/config/
-exit $?
