fix files move/chmod/chown

diff --git a/core/internal/shell/files/functions b/core/internal/shell/files/functions
--- a/core/internal/shell/files/functions
+++ b/core/internal/shell/files/functions
@@ -94,8 +94,8 @@ __sm.files.link()
 
 __sm.files.move()
 {
-  local _source="$1" _target="$2" _flags=($3) _mode="$4" _owner="$5"
-  shift 5
+  local _source="$1" _target="$2" _flags=($3) #_mode="$4" _owner="$5"
+  shift 3
   local _file _files=("$@")
 
   if [[ -n "${_files}" ]]
@@ -106,38 +106,38 @@ __sm.files.move()
         fail "There was an error ($?) moving the source '${_source}/${_file}'" \
         "to the target '${_target}/${_file}'."
 
-      if [[ -n "${_mode}" ]]
-      then
-        chmod "${_mode}" "${_target}/${_file}" ||
-          warn "There was an error ($?) changing"\
-          " target's '${_target}' mode to '${_mode}'."
-      fi
-
-      if [[ -n "${_owner}" ]]
-      then
-        chown "${_owner}" "${_target}/${_file}" ||
-          warn "There was an error ($?) changing"\
-          " target's '${_target}' owner to '${_owner}'."
-      fi
+#      if [[ -n "${_mode}" ]]
+#      then
+#        chmod "${_mode}" "${_target}/${_file}" ||
+#          warn "There was an error ($?) changing"\
+#          " target's '${_target}' mode to '${_mode}'."
+#      fi
+#
+#      if [[ -n "${_owner}" ]]
+#      then
+#        chown "${_owner}" "${_target}/${_file}" ||
+#          warn "There was an error ($?) changing"\
+#          " target's '${_target}' owner to '${_owner}'."
+#      fi
     done
   else # moving single file
-    mv ${_flags[@]} "${_source}" "${_target}/" ||
+    mv ${_flags[@]} "${_source}" "${_target}" ||
       fail "There was an error ($?) moving the source '${_source}'" \
       "to the target '${_target}'."
 
-    if [[ -n "${_mode}" ]]
-    then
-      chmod "${_mode}" "${_target}" ||
-        warn "There was an error ($?) changing"\
-        " target's '${_target}' mode to '${_mode}'."
-    fi
-
-    if [[ -n "${_owner}" ]]
-    then
-      chown "${_owner}" "${_target}" ||
-        warn "There was an error ($?) changing"\
-        " target's '${_target}' owner to '${_owner}'."
-    fi
+#    if [[ -n "${_mode}" ]]
+#    then
+#      chmod "${_mode}" "${_target}" ||
+#        warn "There was an error ($?) changing"\
+#        " target's '${_target}' mode to '${_mode}'."
+#    fi
+#
+#    if [[ -n "${_owner}" ]]
+#    then
+#      chown "${_owner}" "${_target}" ||
+#        warn "There was an error ($?) changing"\
+#        " target's '${_target}' owner to '${_owner}'."
+#    fi
   fi
 }
 
