Extract command for files api at the beginning.

diff --git a/core/internal/shell/files/functions b/core/internal/shell/files/functions
--- a/core/internal/shell/files/functions
+++ b/core/internal/shell/files/functions
@@ -83,11 +83,13 @@ __sm.files.create()
 
   for _file in "${_files[@]}"
   do
-    ! [[ -f "${_file}" ]] || continue
+    if [[ -f "${_file}" ]]
+    then
+      continue # Already exists, move along.
+    fi
     _path="${_file%\/*}"
     paths create "${_path}"
-    touch "${_file}" ||
-      fail "Error creating the file '${_file}' on the filesystem; "\
+    touch "${_file}" || fail "Error creating the file '${_file}'; "\
       " touch command returned error code '$?'."
   done
 }
