put back logging dsl for now.

diff --git a/core/bdsm/modules/shell/logging/dsl b/core/bdsm/modules/shell/logging/dsl
--- a/core/bdsm/modules/shell/logging/dsl
+++ b/core/bdsm/modules/shell/logging/dsl
@@ -33,7 +33,7 @@
 #
 core_log()
 {
-  printf "%s\n" "$*"
+  printf "$*\n"
 }
 
 log()
@@ -74,9 +74,8 @@ log()
 #
 core_warn()
 {
-  printf "WARNING: %s\n" "$*"
+  printf "WARNING: $*\n"
 }
-
 warn()
 {
   core_warn "$@"
@@ -120,14 +119,16 @@ warn()
 #
 core_debug()
 {
-  local type="${1:-}"
+  local type="$1"
   shift
 
-  (( debug_flag == 1 )) && options_check "$debug_flags" "$type" || return 0
-
-  printf "DEBUG %s\n" "$type: $*"
+  if (( debug_flag == 1 )) && options_check "$debug_flags" "$type"
+  then
+    printf "DEBUG $type: $*\n"
+  else
+    return 0
+  fi
 }
-
 debug()
 {
   core_debug "$@"
@@ -170,11 +171,13 @@ core_log_search()
   shift
   shift
 
-  (( debug_flag == 1 )) && options_check "$debug_flags" "search" || return 0
-
-  printf "DEBUG search: %9s %-25s in $*.\n" "$name" "$value"
+  if (( debug_flag == 1 )) && options_check "$debug_flags" "search"
+  then
+    printf "DEBUG search: %9s %-25s in $*.\n" "$name" "$value"
+  else
+    return 0
+  fi
 }
-
 log_search()
 {
   core_log_search "$@"
@@ -213,12 +216,14 @@ log_search()
 #
 core_log_todo()
 {
-  (( debug_flag == 1 )) && options_check "$debug_flags" "todo" || return 0
-
-  local file="${BASH_SOURCE[2]}" line="${BASH_LINENO[1]}"
-
-  printf "DEBUG todo: ${file##${bdsm_path}\/}:${line}:\n"
-  printf "$*" | xargs -s 72 | xargs -I {} printf "DEBUG todo: # {}\n"
+  if (( debug_flag == 1 )) && options_check "$debug_flags" "todo"
+  then
+    local file="${BASH_SOURCE[2]}" line="${BASH_LINENO[1]}"
+    printf "DEBUG todo: ${file##${bdsm_path}\/}:${line}:\n"
+    printf "$*" | xargs -s 72 | xargs -I {} printf "DEBUG todo: # {}\n"
+  else
+    return 0
+  fi
 }
 
 log_todo()
@@ -262,12 +267,11 @@ log_todo()
 core_error()
 {
   set +o xtrace
-  printf "\nERROR: %s\n" "$*" >&2
+  printf "\nERROR: $*\n" >&2
   set +o errtrace
   trap - ERR
   exit 1
 }
-
 error()
 {
   core_error "$@"
@@ -307,10 +311,12 @@ error()
 #
 core_succeed() {
   set +o xtrace
-  [[ -z "$*" ]] || printf "%s\n" "$*"
+  if [[ -n "$*" ]]
+  then
+    printf "$*\n"
+  fi
   exit 0
 }
-
 succeed()
 {
   core_succeed "$@"
@@ -355,7 +361,6 @@ core_fail()
   backtrace "$*"
   exit 1
 }
-
 fail()
 {
   core_fail "$@"
@@ -398,6 +403,7 @@ set_ps4()
   # Finally, return true, 0, for success.
   PS4="# \${BASH_SOURCE##\${bdsm_path}\/} \${FUNCNAME[0]:+\${FUNCNAME[0]}()} \${LINENO} $ "
   export PS4
+  return 0
 }
 
 #
@@ -471,7 +477,6 @@ core_trace_filter()
     fi
   fi
 }
-
 trace_filter()
 {
   set +o xtrace
@@ -541,7 +546,10 @@ separator()
 
   if [[ -z "${COLUMNS}" ]]
   then
-    _columns=$(tput cols) || _columns=80
+    if ! _columns=$(tput cols)
+    then
+      _columns=80
+    fi
     export COLUMNS=${_columns}
   fi
 
@@ -644,7 +652,10 @@ backtrace()
   local _message="${1:-}" _flag="$2"
 
   # If a message was given, print the message to the calling environment's STDERR.
-  [[ -z _message ]] || printf "\n%s\n\n" "${_message}" >&2
+  if [[ -n _message ]]
+  then
+    printf "\n${_message}\n\n" >&2
+  fi
 
   # Declare function local variables
   local _source _function _line _index _largest _format _digits _longest
@@ -656,8 +667,11 @@ backtrace()
   do
     # For each function name in the stack, if the function name is longer than
     # the current largest, then...
-    (( ${#FUNCNAME[${_index}]} <= ${#_largest} )) ||
-      _largest=${FUNCNAME[${_index}]} # ...set it as the new largest element.
+    if (( ${#FUNCNAME[${_index}]} > ${#_largest} ))
+    then
+      # ...set it as the new largest element.
+      _largest=${FUNCNAME[${_index}]}
+    fi
   done
 
   # Loop over the bash source files array, to find the longest element.
@@ -666,8 +680,10 @@ backtrace()
   do
     # For each source file in the source files array, if the file name/path
     # is longer than the current longest, then set it as the new longest element.
-    (( ${#BASH_SOURCE[${_index}]} <= ${#_longest} )) ||
+    if (( ${#BASH_SOURCE[${_index}]} > ${#_longest} ))
+    then
       _longest=${BASH_SOURCE[${_index}]}
+    fi
   done
 
   for (( _index=0 ; _index < ${#BASH_LINENO[@]} ; _index++ ))
@@ -739,9 +755,12 @@ backtrace()
   # then turn tracing back on.
   printf "${_separator// /=}\n" 1>&2
 
-  [[ "${_flag}" != "no_exit" ]] || return 0
-
-  finish_app
+  if [[ "${_flag}" != "no_exit" ]]
+  then
+    finish_app
+  else
+    return 0
+  fi
 }
 
 finish_app()
@@ -833,3 +852,4 @@ clean_tmp_logs()
   rm -rf ${TMP_PATH:-/tmp}/err_*.log || \
     printf "Could not clean old logs, please clean by calling:\n  sudo rm -rf ${TMP_PATH:-/tmp}/err_*.log\n"
 }
+
