Missed a few renames.

diff --git a/modules/bash/filesystem/dsl b/modules/bash/filesystem/dsl
--- a/modules/bash/filesystem/dsl
+++ b/modules/bash/filesystem/dsl
@@ -2517,32 +2517,32 @@ extract_archive()
 
   case "${_archive}" in
     *.tar.gz|*.tgz) # gzip
-      if ! tar zxf "${archive}"
+      if ! tar zxf "${_archive}"
       then
-        error "There was an error while extracting the archive '${archive}'"
+        error "There was an error while extracting the archive '${_archive}'"
       fi
       ;;
     *tar.xz) # LZMA
       # TODO: if 'xz' command exists, use that, otherwise use tar J
-      if ! tar Jxf "${archive}"
+      if ! tar Jxf "${_archive}"
       then
-        error "There was an error while extracting the archive '${archive}'"
+        error "There was an error while extracting the archive '${_archive}'"
       fi
       ;;
     *.tar.bz2) # bzip
-      if ! tar jxf "${archive}"
+      if ! tar jxf "${_archive}"
       then
-        error "There was an error while extracting the archive '${archive}'"
+        error "There was an error while extracting the archive '${_archive}'"
       fi
       ;;
     *.zip)
-      if ! unzip "${archive}" -d "${_path:-}"
+      if ! unzip "${_archive}" -d "${_path:-}"
       then
-        error "There was an error while extracting the archive '${archive}'"
+        error "There was an error while extracting the archive '${_archive}'"
       fi
       ;;
     *)
-      error "Unknown archive format for ${archive}"
+      error "Unknown archive format for ${_archive}"
       ;;
   esac
 }
