Some cleanup.

diff --git a/modules/bash/filesystem/dsl b/modules/bash/filesystem/dsl
--- a/modules/bash/filesystem/dsl
+++ b/modules/bash/filesystem/dsl
@@ -390,10 +390,10 @@ ensure_files_exist()
 #
 #     user$ ensure_files_are_executable /etc/rc.d/postgresql
 #
+# TODO: change this to be a  fail function if one is not
+#       make this into make_files_executable or some such
 ensure_files_are_executable()
 {
-  # TODO: change this to be a  fail function if one is not
-  #       make this into make_files_executable or some such
   local _file _files=("$@") _path
 
   if (( ${#_files[@]} == 0 ))
@@ -492,10 +492,14 @@ link()
   fi
 
   # TODO: What should we do if files already exist?
-  if [[ -f "${_target}" ]] ; then
+  if [[ -f "${_target}" ]]
+  then
     error "Cannot link ${_source} to ${_target} exists and is a file!"
-  elif [[ -d "${_target}" ]] ; then
+
+  elif [[ -d "${_target}" ]]
+  then
     error "Cannot link ${_source} to ${_target} exists and is a directory"
+
   else
     ensure_paths_exist "${_target%\/*}"
     ln -fs "${_source}" "${_target}"
@@ -542,44 +546,61 @@ move_directory()
     token="$1" ; shift
     case "${token}" in
       to)
-        _target="${1}" ; shift
+        _target="${1}"
+        shift
         ;;
 
       from)
-        _source="${1}" ; shift
+        _source="${1}"
+        shift
         ;;
 
       mode)
-         _mode="${1}" ; shift
+         _mode="${1}"
+         shift
         ;;
 
       owner)
-         _owner="${1}" ; shift
+         _owner="${1}"
+         shift
         ;;
 
       *)
-        if [[ -z "${_source}" ]] ; then
+        if [[ -z "${_source}" ]]
+        then
           _source="$token"
-        elif [[ -z "${_target}" ]] ; then
+
+        elif [[ -z "${_target}" ]]
+        then
           _target="$token"
-          break # When we have a target we are done.
-          # An alternative idea would be to allow an array of multiple targets
-          # to symlink to...
+          # When we have a target we are done.
+          break
         fi
         ;;
     esac
   done
 
-  [[ -n "${_source}" ]] ||
+  if [[ -z "${_source}" ]]
+  then
     fail "Cannot move file as the source and target must be specified. "
+  fi
 
-  [[ -n "${_target}" ]] ||
+  if [[ -z "${_target}" ]]
+  then
     fail "Cannot move file as the source and target must be specified. "
+  fi
 
   mv "${_source}" "${_target}"
 
-  [[ -z "${_mode:-}" ]]  || chmod -R "${_mode}" "${_target}"
-  [[ -z "${_owner:-}" ]] || chown -R "${_owner}" "${_target}"
+  if [[ -n "${_mode:-}" ]]
+  then
+    chmod -R "${_mode}" "${_target}"
+  fi
+
+  if [[ -n "${_owner:-}" ]]
+  then
+    chown -R "${_owner}" "${_target}"
+  fi
 }
 
 #
@@ -622,44 +643,57 @@ move_file()
     token="$1" ; shift
     case "${token}" in
       to)
-        _target="${1}" ; shift
+        _target="${1}"
+        shift
         ;;
-
       from)
-        _source="${1}" ; shift
+        _source="${1}"
+        shift
         ;;
-
       mode)
-         _mode="${1}" ; shift
+         _mode="${1}"
+         shift
         ;;
-
       owner)
-         _owner="${1}" ; shift
+         _owner="${1}"
+         shift
         ;;
 
       *)
-        if [[ -z "${_source}" ]] ; then
+        if [[ -z "${_source}" ]]
+        then
           _source="$token"
-        elif [[ -z "${_target}" ]] ; then
+
+        elif [[ -z "${_target}" ]]
+        then
           _target="$token"
-          break # When we have a target we are done.
-          # An alternative idea would be to allow an array of multiple targets
-          # to symlink to...
+          break
         fi
         ;;
     esac
   done
 
-  [[ -n "${_source}" ]] ||
+  if [[ -z "${_source}" ]]
+  then
     fail "Cannot move file as the source and target must be specified. "
+  fi
 
-  [[ -n "${_target}" ]] ||
+  if [[ -z "${_target}" ]]
+  then
     fail "Cannot move file as the source and target must be specified. "
+  fi
 
   mv "${_source}" "${_target}"
 
-  [[ -z "${_mode:-}" ]]  || chmod "${_mode}" "${_target}"
-  [[ -z "${_owner:-}" ]] || chown "${_owner}" "${_target}"
+  if [[ -n "${_mode:-}" ]]
+  then
+    chmod "${_mode}" "${_target}"
+  fi
+
+  if [[ -n "${_owner:-}" ]]
+  then
+    chown "${_owner}" "${_target}"
+  fi
 }
 
 #
@@ -699,7 +733,8 @@ copy_file()
   local _source _target
 
   while (( $# > 0 )) ; do
-    token="$1" ; shift
+    token="$1"
+    shift
     case "${token}" in
       to)
         _target="${1}"
@@ -710,23 +745,23 @@ copy_file()
         shift
         ;;
       mode)
-         _mode="${1}" ; shift
+         _mode="${1}"
+         shift
         ;;
-
       owner)
-         _owner="${1}" ; shift
+         _owner="${1}"
+         shift
         ;;
       *)
         if [[ -z "${_source:-}" ]]
         then
           _source="$token"
           shift
+
         elif [[ -z "${_target:-}" ]]
         then
           _target="$token"
-          break # When we have a target we are done.
-          # An alternative idea would be to allow an array of multiple targets
-          # to symlink to...
+          break
         fi
         ;;
     esac
@@ -749,33 +784,7 @@ copy_file()
 #
 # ## copy_files_to
 #
-# Copys a given list of files into the named path.
-#
-# ### Input Parameters
-#
-# The first parameter is the path to copy the files into.
-# Remaining parameters are the file name/path list.
-#
-# ### Stream Outputs
-#
-# None.
-#
-# ### Environmental effects
-#
-# If successful, all named files are copied into the target path.
-#
-# ### Return Codes
-#
-# 0 for success.
-#
-# ### Failure Scenarios
-#
-# Fails if no target path is given.
-# Fails if no files are given.
-#
-# ### Usage Examples
-#
-#     user$ copy_files_to "$HOME/backup" "$HOME/.bashrc" "$HOME/.bash_profile"
+# depreciated, please use copy_files with the 'to' specifier instead
 #
 copy_files_to()
 {
@@ -1090,16 +1099,16 @@ copy_directory()
         _source="${1}"
         shift
         ;;
-
       *)
-        if [[ -z "${_source}" ]] ; then
+        if [[ -z "${_source}" ]]
+        then
           _source="$token"
           shift
-        elif [[ -z "${_target}" ]] ; then
+
+        elif [[ -z "${_target}" ]]
+        then
           _target="$token"
-          break # When we have a target we are done.
-          # An alternative idea would be to allow an array of multiple targets
-          # to symlink to...
+          break
         fi
         ;;
     esac
@@ -1674,7 +1683,7 @@ enter()
 
   if ! builtin cd "${_path}"
   then
-    error "There was an error ($?) wile attempting to enter the directory '${_path}'."
+    error "There was an error ($?) while entering the directory '${_path}'."
   fi
 }
 
@@ -1802,16 +1811,16 @@ file_is_executable()
 {
   local _file="${1:-}"
 
-  if [[ -z "${_file}" ]]
+  if [[ -n "${_file}" ]]
   then
-    fail "Cannot check if a file is executable as no file path/name was given"
-  fi
-
-  if [[ -x "${_file}" ]]
-  then
-    return 0
+    if [[ -x "${_file}" ]]
+    then
+      return 0
+    else
+      return 1
+    fi
   else
-    return 1
+    fail "Cannot check if a file is executable as no file path/name was given"
   fi
 }
 
@@ -1855,16 +1864,16 @@ file_exists()
 {
   local _file="${1:-}"
 
-  if [[ -z "${_file}" ]]
+  if [[ -n "${_file}" ]]
   then
-    fail "Cannot check to see if a file exists as no file name/path was given"
-  fi
-
-  if [[ -f "${_file}" ]]
-  then
-    return 0
+    if [[ -f "${_file}" ]]
+    then
+      return 0
+    else
+      return 1
+    fi
   else
-    return 1
+    fail "Cannot check to see if a file exists as no file name/path was given"
   fi
 }
 
@@ -1967,16 +1976,16 @@ file_is_empty()
 {
   local _file="${1:-}"
 
-  if [[ -z "${_file}" ]]
+  if [[ -n "${_file}" ]]
   then
-    fail "Cannot check if a file is empty as no file path/name was given"
-  fi
-
-  if [[ -f "${_file}" && ! -s "${_file}" ]]
-  then
-    return 0
+    if [[ -f "${_file}" && ! -s "${_file}" ]]
+    then
+      return 0
+    else
+      return 1
+    fi
   else
-    return 1
+    fail "Cannot check if a file is empty as no file path/name was given"
   fi
 }
 
@@ -2020,16 +2029,16 @@ file_is_missing()
 {
   local _file="${1:-}"
 
-  if [[ -z "${_file}" ]]
+  if [[ -n "${_file}" ]]
   then
-    fail "Cannot check if file is missing as no file path/name was given"
-  fi
-
-  if [[ ! -f "${_file}" ]]
-  then
-    return 0
+    if [[ ! -f "${_file}" ]]
+    then
+      return 0
+    else
+      return 1
+    fi
   else
-    return 1
+    fail "Cannot check if file is missing as no file path/name was given"
   fi
 }
 
@@ -2075,14 +2084,14 @@ file_is_empty_or_missing()
 
   if [[ -z "${_file}" ]]
   then
-    fail "Cannot check if file is empty or missing as no file path/name was given"
-  fi
-
-  if [[ ! -f "${_file}" || ! -s "${_file}" ]]
-  then
-    return 0
+    if [[ ! -f "${_file}" || ! -s "${_file}" ]]
+    then
+      return 0
+    else
+      return 1
+    fi
   else
-    return 1
+    fail "Cannot check if file is empty or missing as no file path/name was given"
   fi
 }
 
@@ -2145,6 +2154,7 @@ file_contains()
   fi
 
   local _pattern="${1:-}"
+
   if [[ -z "${_pattern}" ]]
   then
     fail "String pattern for search was not given!"
@@ -2203,16 +2213,16 @@ symlink_exists()
 {
   local _file="${1:-}"
 
-  if [[ -z "${_file}" ]]
+  if [[ -n "${_file}" ]]
   then
-    fail "Cannot check if symlink exists as no path/name was given"
-  fi
-
-  if [[ -L "${_file}" ]]
-  then
-    return 0
+    if [[ -L "${_file}" ]]
+    then
+      return 0
+    else
+      return 1
+    fi
   else
-    return 1
+    fail "Cannot check if symlink exists as no path/name was given"
   fi
 }
 
@@ -2256,16 +2266,16 @@ directory_exists()
 {
   local _directory="${1:-}"
 
-  if [[ -z "${_directory}" ]]
+  if [[ -n "${_directory}" ]]
   then
-    fail "Cannot check if directory exists as no name/path was given"
-  fi
-
-  if [[ -d "$_directory" ]]
-  then
-    return 0
+    if [[ -d "$_directory" ]]
+    then
+      return 0
+    else
+      return 1
+    fi
   else
-    return 1
+    fail "Cannot check if directory exists as no name/path was given"
   fi
 }
 
