Cleanup of filesystem. For scm_update ensure in the repo_path.

diff --git a/modules/bash/filesystem/dsl b/modules/bash/filesystem/dsl
--- a/modules/bash/filesystem/dsl
+++ b/modules/bash/filesystem/dsl
@@ -37,18 +37,23 @@ source_files()
 {
   local _file _files=("$@")
 
-  (( ${#_files[@]} > 0 )) || fail "Cannot source files as no files were given."
+  if (( ${#_files[@]} > 0 ))
+  then
+    for _file in "${_files[@]}"
+    do
+      _file=${_file/\~\//$HOME\/} # Expand ~/ to full value of $HOME
 
-  for _file in "${_files[@]}" ; do
-    _file=${_file/\~\//$HOME\/} # Expand ~/ to full value of $HOME
-
-    if file_is_nonempty "${_file}" ; then
-      source "${_file}"
-      # TODO: figure out how to see if 'source' itself failed or simply
-      # returning nonzero code.
-      # || fail "Failed to source ${_file}."
-    fi
-  done
+      if file_is_nonempty "${_file}"
+      then
+        source "${_file}"
+        # TODO: figure out how to see if 'source' itself failed or simply
+        # returning nonzero code.
+        # || fail "Failed to source ${_file}."
+      fi
+    done
+  else
+    fail "Cannot source files as no files were given."
+  fi
 }
 
 #
@@ -86,16 +91,18 @@ nonempty_files()
 {
   local _file _files=("$@")
 
-  (( ${#_files[@]} > 0 )) ||
+  if (( ${#_files[@]} > 0 ))
+  then
+    for _file in "${_files[@]}"
+    do
+      if file_is_nonempty "${_file}"
+      then
+        printf "${_file}\n"
+      fi
+    done
+  else
     fail "Cannot return nonempty files as no files were given."
-
-  for _file in "${_files[@]}"
-  do
-    if file_is_nonempty "${_file}"
-    then
-      printf "${_file}\n"
-    fi
-  done
+  fi
 }
 
 #
@@ -136,13 +143,18 @@ ensure_paths_exist()
 {
   local _path _paths=("$@")
 
-  (( ${#_paths[@]} > 0 )) ||
+  if (( ${#_paths[@]} > 0 ))
+  then
+    for _path in "${_paths[@]}"
+    do
+      if ! directory_exists "${_path}"
+      then
+        mkdir -p "${_path}"
+      fi
+    done
+  else
     fail "Cannot ensure paths exist as no paths were given."
-
-  for _path in "${_paths[@]}"
-  do
-    directory_exists "${_path}" || mkdir -p "${_path}"
-  done
+  fi
 }
 
 #
@@ -186,21 +198,26 @@ remove_files()
 {
   local _file _files=("$@")
 
-  (( ${#_files[@]} > 0 )) ||
+  if (( ${#_files[@]} > 0 ))
+  then
+    for _file in "${_files[@]}"
+    do
+      if [[ -f "${_file}" || -L "${_file}" ]]
+      then
+        rm -f "${_file}"
+      elif [[ -d "${_file}" ]]
+      then
+        error "Cannot remove the file ${_file} as it is a directory."
+      elif [[ -e "${_file}" ]]
+      then
+        error "Unknown filesystem entity type located at ${_file}, cannot remove."
+      else
+        true # already gone
+      fi
+    done
+  else
     fail "Cannot remove files as no files were given."
-
-  for _file in "${_files[@]}"
-  do
-    if [[ -f "${_file}" || -L "${_file}" ]] ; then
-      rm -f "${_file}"
-    elif [[ -d "${_file}" ]] ; then
-      error "Cannot remove the file ${_file} as it is a directory."
-    elif [[ -e "${_file}" ]] ; then
-      error "Unknown filesystem entity type located at ${_file}, cannot remove."
-    else
-      true # already gone
-    fi
-  done
+  fi
 }
 
 #
@@ -244,21 +261,22 @@ remove()
 {
   local _file _files=("$@")
 
-  if (( ${#_files[@]} == 0 ))
+  if (( ${#_files[@]} > 0 ))
   then
+    for _file in "${_files[@]}"
+    do
+      if [[ -f "${_file}" || -L "${_file}" || -d "${_file}" ]]
+      then
+        rm -rf "${_file}"
+
+      elif [[ -e "${_file}" ]]
+      then
+        error "Unhandled filesystem entity type located at ${_file}, cannot remove. (File, link and directory types are handled)"
+      fi
+    done
+  else
     fail "Cannot remove files as no files were given."
   fi
-
-  for _file in "${_files[@]}"
-  do
-    if [[ -f "${_file}" || -L "${_file}" || -d "${_file}" ]] ; then
-      rm -rf "${_file}"
-
-    elif [[ -e "${_file}" ]] ; then
-      error "Unhandled filesystem entity type located at ${_file}, cannot remove. (File, link and directory types are handled)"
-
-    fi
-  done
 }
 
 #
@@ -296,21 +314,33 @@ remove_paths()
 {
   local _path _paths=("$@")
 
-  (( ${#_paths[@]} > 0 )) || fail "Cannot remove paths as no paths were given."
+  if (( ${#_paths[@]} > 0 ))
+  then
+    for _path in "${_paths[@]}"
+    do
+      if [[ -f "${_path}" ]]
+      then
+        error "Cannot remove the path '${_path}' as it is a file."
 
-  for _path in "${_paths[@]}" ; do
-    if [[ -f "${_path}" ]] ; then
-      error "Cannot remove the path '${_path}' as it is a file."
-    elif [[ -L "${_path}" ]] ; then
-      rm -f "${_path}"
-    elif [[ -d "${_path}" ]] ; then
-      rm -rf "${_path}"
-    elif [[ -e "${_path}" ]] ; then
-      error "Unknown filesystem entity type at ${_path}, cannot remove."
-    else
-      true # already gone
-    fi
-  done
+      elif [[ -L "${_path}" ]]
+      then
+        rm -f "${_path}"
+
+      elif [[ -d "${_path}" ]]
+      then
+        rm -rf "${_path}"
+
+      elif [[ -e "${_path}" ]]
+      then
+        error "Unknown filesystem entity type at ${_path}, cannot remove."
+
+      else
+        true # already gone
+      fi
+    done
+  else
+    fail "Cannot remove paths as no paths were given."
+  fi
 }
 
 #
@@ -351,15 +381,25 @@ ensure_files_exist()
 {
   local _file _files=("$@") _path
 
-  (( ${#_files[@]} > 0 )) ||
-    fail "Cannot ensure files exist as no files were given."
+  if (( ${#_files[@]} > 0 ))
+  then
+    for _file in "${_files[@]}"
+    do
+      _path="${_file%\/*}"
 
-  for _file in "${_files[@]}"
-  do
-    _path="${_file%\/*}"
-    [[ -d "${_path}" ]] || mkdir -p "${_path}"
-    [[ -e "${_file}" ]] || touch "${_file}"
-  done
+      if [[ ! -d "${_path}" ]]
+      then
+        mkdir -p "${_path}"
+      fi
+
+      if [[ ! -e "${_file}" ]]
+      then
+        touch "${_file}"
+      fi
+    done
+  else
+    fail "Cannot ensure files exist as no files were given."
+  fi
 }
 
 #
@@ -400,31 +440,31 @@ ensure_files_are_executable()
 {
   local _file _files=("$@") _path
 
-  if (( ${#_files[@]} == 0 ))
+  if (( ${#_files[@]} > 0 ))
   then
+    for _file in "${_files[@]}"
+    do
+      if [[ -d "${_file}" ]]
+      then
+        fail "Cannot make the file '${_file}' executable as it is a directory."
+      fi
+
+      if [[ ! -f "${_file}" ]]
+      then
+        fail "Cannot make the file '${_file}' executable as the file does not exist."
+      fi
+
+      _path="${_file%\/*}"
+
+      if ! [[ -n "${_path}" && ! -d "${_file}" ]]
+      then
+        fail "Cannot make the file '${_file} executable as '${_path}' does not even exist."
+      fi
+      chmod +x "${_file}"
+    done
+  else
     fail "Cannot ensure files are executable as no files were given."
   fi
-
-  for _file in "${_files[@]}"
-  do
-    if [[ -d "${_file}" ]]
-    then
-      fail "Cannot make the file '${_file}' executable as it is a directory."
-    fi
-
-    if [[ ! -f "${_file}" ]]
-    then
-      fail "Cannot make the file '${_file}' executable as the file does not exist."
-    fi
-
-    _path="${_file%\/*}"
-    if ! [[ -n "${_path}" && ! -d "${_file}" ]]
-    then
-      fail "Cannot make the file '${_file} executable as '${_path}' does not even exist."
-    fi
-
-    chmod +x "${_file}"
-  done
 }
 
 #
@@ -466,24 +506,30 @@ link()
 {
   local token _source _target _force_flag=0
 
-  while (( $# > 0 )) ; do
-    token="$1" ; shift
+  while (( $# > 0 ))
+  do
+    token="$1"
+    shift
 
     case "${token}" in
       to)
-        _target="${1}" ; shift
+        _target="${1}"
+        shift
         ;;
       from)
-        _source="${1}" ; shift
+        _source="${1}"
+        shift
         ;;
       --force)
         _force_flag=1
         ;;
-
       *)
-        if [[ -z "${_source}" ]] ; then
+        if [[ -z "${_source}" ]]
+        then
           _source="$token"
-        elif [[ -z "${_target}" ]] ; then
+
+        elif [[ -z "${_target}" ]]
+        then
           _target="$token"
         fi
         ;;
@@ -1093,8 +1139,10 @@ copy_directory()
 {
   local _source _target
 
-  while (( $# > 0 )) ; do
-    token="$1" ; shift
+  while (( $# > 0 ))
+  do
+    token="$1"
+    shift
     case "${token}" in
       to)
         _target="${1}"
@@ -1557,30 +1605,40 @@ chmod_files()
 #
 chmod_paths()
 {
-  local _permissions="$1" _path
+  local _permissions="$1" _path _message
+
   if [[ -n "${_permissions}" ]]
   then
     shift
-  else
-    fail "Cannot chmod_paths as the permissions were not given as the first parameter!!"
-  fi
-
-  local _paths=("$@")
-
-  if (( ${#_paths[@]} == 0 ))
-  then
-    fail "Cannot chmod_paths as no paths were given in order to change permissions to ${_permissions}."
-  fi
-
-  for _path in "${_paths[@]}"
-  do
-    if directory_exists "${_path}"
+    local _paths=("$@")
+    if (( ${#_paths[@]} > 0 ))
     then
-      chmod ${_permissions} "${_path}"
+      for _path in "${_paths[@]}"
+      do
+        if directory_exists "${_path}"
+        then
+          chmod ${_permissions} "${_path}"
+        else
+          _message=(
+          "Cannot chmod directory ${_path} to ${_permissions}"
+          " as the directory does not exist.")
+          error "${_message[*]}"
+        fi
+      done
     else
-      error "Cannot chmod directory ${_path} to ${_permissions} as the directory does not exist."
+      _message=(
+      "Cannot chmod_paths as no paths were given in "
+      "order to change permissions to ${_permissions}."
+      )
+      fail "${_message[*]}"
     fi
-  done
+  else
+    _message=(
+    "Cannot chmod_paths as the permissions were "
+    "not given as the first parameter!!"
+    )
+    fail "${_message[*]}"
+  fi
 }
 
 #
@@ -1616,28 +1674,34 @@ chmod_paths()
 #
 chmod_paths_recursively()
 {
-  local _permissions="${1:-}" _path
-  if [[ -z "${_permissions}" ]]
+  local _permissions="${1:-}" _path _message
+
+  if [[ -n "${_permissions}" ]]
   then
+    shift
+    local _paths=("$@")
+
+    if (( ${#_paths[@]} > 0 ))
+    then
+      for _path in "${_paths[@]}"
+      do
+        if directory_exists "${_path}"
+        then
+          chmod -R ${_permissions} "${_path}"
+        else
+          _message=(
+          "Cannot chmod directory ${_path} to ${_permissions} "
+          "as the directory does not exist."
+          )
+          error "${_message[*]}"
+        fi
+      done
+    else
+      fail "No paths given to chmod ${_permissions}."
+    fi
+  else
     fail "Permissions not given as the first parameter!!"
   fi
-  shift
-  local _paths=("$@")
-
-  if (( ${#_paths[@]} == 0 ))
-  then
-    fail "No paths given to chmod ${_permissions}."
-  fi
-
-  for _path in "${_paths[@]}"
-  do
-    if directory_exists "${_path}"
-    then
-      chmod -R ${_permissions} "${_path}"
-    else
-      error "Cannot chmod directory ${_path} to ${_permissions} as the directory does not exist."
-    fi
-  done
 }
 
 #
@@ -1676,19 +1740,19 @@ enter()
 {
   local _path="$1"
 
-  if [[ -z "${_path}" ]]
+  if [[ -n "${_path}" ]]
   then
+    if [[ -d "${_path}" ]]
+    then
+      if ! builtin cd "${_path}"
+      then
+        error "There was an error ($?) while entering the directory '${_path}'."
+      fi
+    else
+      error "Cannot enter the directory '${_path}' as it does not exist."
+    fi
+  else
     fail "Cannot enter a directory as no directory was given."
-  fi
-
-  if [[ ! -d "${_path}" ]]
-  then
-    error "Cannot enter the directory '${_path}' as it does not exist."
-  fi
-
-  if ! builtin cd "${_path}"
-  then
-    error "There was an error ($?) while entering the directory '${_path}'."
   fi
 }
 
@@ -1729,7 +1793,7 @@ enter()
 #
 hash_file()
 {
-  local _file="${1:-}"
+  local _file="${1:-}" _message
 
   if [[ -z "${_file}" ]]
   then
@@ -1752,7 +1816,11 @@ hash_file()
   then
     ensure_files_exist "$_file"
   else
-    error "Cannot access the database file '${_file}' as the directory '${_file%\/*}' does not exist."
+    _message=(
+    "Cannot access the database file '${_file}' "
+    "as the directory '${_file%\/*}' does not exist."
+    )
+    error "{$_message[*]}"
   fi
 
   value="$*"
@@ -1922,24 +1990,23 @@ file_is_nonempty()
 {
   local _file="${1:-}"
 
-  if [[ -z "${_file}" ]]
+  if [[ -n "${_file}" ]]
   then
+    if [[ -d "${_file}" ]]
+    then
+      error "When checking whether the file '${_file}' is nonempty, a directory was found in its place."
+    else
+      if [[ -s "${_file}" ]]
+      then
+        return 0
+      else
+        return 1
+      fi
+    fi
+  else
     fail "Cannot check if file is nonempty as no file path/name was given"
   fi
-
-  if [[ -d "${_file}" ]]
-  then
-    error "When checking whether the file '${_file}' is nonempty, a directory was found in its place."
-  fi
-
-  if [[ -s "${_file}" ]]
-  then
-    return 0
-  else
-    return 1
-  fi
 }
-
 
 #
 # ## file_is_empty
@@ -2144,37 +2211,37 @@ file_is_empty_or_missing()
 #       echo "no w00t :("
 #     fi
 #
-#     user$ "$HOME/test"
-#     no w00t :(
 #
 file_contains()
 {
-  local _file="${1:-}"
+  local _file="${1:-}" _message
 
   if [[ -n "${_file}" ]]
   then
     shift
+    local _pattern="${1:-}"
+    if [[ -n "${_pattern}" ]]
+    then
+      if [[ -f "${_file}" ]]
+      then
+        if grep "${_pattern}" "${_file}" >/dev/null 2>&1
+        then
+          return 0
+        else
+          return 1
+        fi
+      else
+        _message=(
+        "First parameter must be a file, '${_file}'"
+        " does not appear to be a file."
+        )
+        fail "${_message[*]}"
+      fi
+    else
+      fail "String pattern for search was not given!"
+    fi
   else
     fail "File path/name was not given!"
-  fi
-
-  local _pattern="${1:-}"
-
-  if [[ -z "${_pattern}" ]]
-  then
-    fail "String pattern for search was not given!"
-  fi
-
-  if [[ ! -f "${_file}" ]]
-  then
-    fail "First parameter must be a file, '${_file}' does not appear to be a file."
-  fi
-
-  if grep "${_pattern}" "${_file}" >/dev/null 2>&1
-  then
-    return 0
-  else
-    return 1
   fi
 }
 
