Added extensive error checking to functions in the filesystem module, fixed copy and move names to copy_files and move_files.

diff --git a/modules/bash/filesystem/functions b/modules/bash/filesystem/functions
--- a/modules/bash/filesystem/functions
+++ b/modules/bash/filesystem/functions
@@ -10,10 +10,15 @@
 source_files()
 {
   local _file
+  local _files=("$@")
 
-  for _file in "$@" ; do
+  [[ ${#files[@]} -gt 0 ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => No files given to source! "
+
+  for _file in "${files[@]}" ; do
     _file=${_file/\~\//$HOME\/} # Expand ~/ to full value of $HOME
-    [[ -s "${_file}" ]] && source "${_file}"
+
+    file_is_nonempty && source "${_file}"
   done
 }
 
@@ -21,9 +26,10 @@ source_files()
 nonempty_files()
 {
   local _file
+  local _files=$("$@")
 
-  for _file in "${@}" ; do
-    [[ -s "$_file" ]] && printf "$_file"
+  for _file in "${_files[@]}" ; do
+    file_is_nonempty "${_file}" && printf "${_file}\n"
   done
 }
 
@@ -32,7 +38,7 @@ ensure_paths_exist()
   local _path
 
   for _path in "$@" ; do
-    [[ -d "${_path}" ]] || mkdir -p "${_path}"
+    directory_exists "${_path}" || mkdir -p "${_path}"
   done
 }
 
@@ -44,9 +50,10 @@ remove_files()
     if [[ -f "${_file}" || -L "${_file}" ]] ; then
       rm -f "${_file}"
     elif [[ -d "${_file}" ]] ; then
-      error "${_file} is a directory! "
+      error "${extension} ${action} ${FUNCNAME}()\n => Cannot remove ${_file}, it is a directory! "
+
     elif [[ -e "${_file}" ]] ; then
-      error "Unknown entry at ${_file}, cannot remove."
+      error "${extension} ${action} ${FUNCNAME}()\n => Unknown filesystem entity type located at ${_file}, cannot remove."
     else
       true # already gone
     fi
@@ -56,27 +63,34 @@ remove_files()
 remove_paths()
 {
   local _path
+  local _paths=("$@")
 
-  for _path in "$@" ; do
+  for _path in "${_paths[@]}" ; do
+
     if [[ -f "${_path}" ]] ; then
-      error "${_path} is a file! "
+      error "${extension} ${action} ${FUNCNAME}()\n => Cannot remove the path '${_path}' as it is a file! "
     elif [[ -L "${_path}" ]] ; then
       rm -f "${_path}"
     elif [[ -d "${_path}" ]] ; then
       rm -rf "${_path}"
     elif [[ -e "${_path}" ]] ; then
-      error "Unknown entry at ${_path}, cannot remove."
+      error "${extension} ${action} ${FUNCNAME}()\n => Unknown filesystem entity type at ${_path}, cannot remove."
     else
       true # already gone
     fi
+
   done
 }
 
 ensure_files_exist()
 {
   local _file
+  local _files=("$@")
 
-  for _file in "$@" ; do
+  [[ ${#_files[@]} -gt 0 ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => Cannot ensure files exist, no files were given."
+
+  for _file in "${_files[@]}" ; do
     [[ -e "${_file}" ]] || touch "${_file}"
   done
 }
@@ -87,13 +101,13 @@ ensure_files_are_executable()
 {
   local _file="$1"
 
-  ensure_files_exist "${_file}"
+  [[ -d "${_file}" ]] &&
+    fail "${extension} ${action} ${FUNCNAME}()\n => Cannot make ${_file} executable, it is a directory."
 
-  if [[ -d "${_file}" ]] ; then
-    fail "Cannot make ${_file} executable, it is a directory."
-  else
-    chmod +x "${_file}"
-  fi
+  [[ -f "${_file}" ]] &&
+    fail "${extension} ${action} ${FUNCNAME}()\n => Cannot make ${_file} executable, the file does not exist."
+
+  chmod +x "${_file}"
 }
 
 #
@@ -139,15 +153,15 @@ link()
 
   # TODO: What should we do if files already exist?
   if [[ -f "${_target}" ]] ; then
-    error "Cannot link ${_source} to ${_target} exists and is a file!"
+    error "${extension} ${action} ${FUNCNAME}()\n => Cannot link ${_source} to ${_target} exists and is a file!"
   elif [[ -d "${_target}" ]] ; then
-    error "Cannot link ${_source} to ${_target} exists and is a directory"
+    error "${extension} ${action} ${FUNCNAME}()\n => Cannot link ${_source} to ${_target} exists and is a directory"
   else
     ln -fs "${_source}" "${_target}"
   fi
 }
 
-move()
+move_file()
 {
   local _source _target
 
@@ -179,7 +193,7 @@ move()
   mv "${_source}" "${_target}"
 }
 
-copy()
+copy_file()
 {
   local _source _target
 
@@ -214,33 +228,54 @@ copy()
 copy_files_to()
 {
   local _path="$1" _file ; shift
+  local _files=("$@")
 
   ensure_paths_exist "${_path}"
 
-  for _file in "$@" ; do
-    [[ -s "${_file}" ]] && cp "${_file}" "${_path}/${_file}"
+  for _file in "${_files[@]}" ; do
+
+    if file_is_missing ; then
+      error "${extension} ${action} ${FUNCNAME}()\n => Cannot copy file ${_file} to ${_path} as the file does not exist."
+    else
+      cp "${_file}" "${_path}/${_file}"
+    fi
+
   done
 }
 
 copy_directories_to()
 {
   local _path="${1}" _directory ; shift
+  local _directories=("$@")
 
   ensure_paths_exist "${_path}"
 
-  for _directory in "$@" ; do
-    cp -Rf "${_directory}" "${_path}/"
+  for _directory in "${_directories[@]}" ; do
+
+    if directory_exists "${_directory}" ; then
+      cp -Rf "${_directory}" "${_path}/"
+    else
+      error "${extension} ${action} ${FUNCNAME}()\n => Cannot copy directory ${_directory} to ${_path} as the directory does not exist."
+    fi
+
   done
 }
 
 move_files_to()
 {
   local _path="$1" _file ; shift
+  local _files=("$@")
 
   ensure_paths_exist "${_path}"
 
-  for _file in "$@" ; do
-    [[ -f "${_file}" ]] && mv "${_file}" "${_path}/${_file}"
+  for _file in "${_files[@]}" ; do
+
+    if file_exists "${_file}" ; then
+      mv "${_file}" "${_path}/${_file}"
+    else
+      error "${extension} ${action} ${FUNCNAME}()\n => Cannot move file ${_file} to ${_path} as the file does not exist."
+    fi
+
   done
 }
 
@@ -249,25 +284,59 @@ chown_files()
   local _idenity="$1" _file; shift
 
   for _file in "${@}" ; do
-    [[ -f "${_file}" ]] && chown -R ${_idenity} "${_file}"
+
+    if file_exists "${_file}" ; then
+      chown -R ${_idenity} "${_file}"
+    else
+      error "${extension} ${action} ${FUNCNAME}()\n => Cannot chown file ${_file} to ${_idenity} as the file does not exist."
+    fi
+
   done
 }
 
 chown_paths()
 {
   local _idenity="$1" _path; shift
+  local _paths=("$@")
 
-  for _path in "$*" ; do
-    [[ -d "${_path}" ]] && chown -R ${_idenity} "${_path}"
+  for _path in "${_paths[@]}" ; do
+
+    if directory_exists "${_path}" ; then
+      chown ${_idenity} "${_path}"
+    else
+      error "${extension} ${action} ${FUNCNAME}()\n => Cannot chown path ${_path} to ${_idenity} as the directory does not exist."
+    fi
+
+  done
+}
+
+chown_paths_recursively()
+{
+  local _idenity="$1" _path; shift
+  local _paths=("$@")
+
+  for _path in "${_paths[@]}" ; do
+
+    if directory_exists "${_path}" ; then
+      chown -R ${_idenity} "${_path}"
+    else
+      error "${extension} ${action} ${FUNCNAME}()\n => Cannot recursively chown ${_path} to ${_idenity} as the directory does not exist."
+    fi
+
   done
 }
 
 chmod_files()
 {
   local _permissions="$1" _file; shift
+  local _files=("$@")
 
-  for _file in "${@}" ; do
-    [[ -f "${_file}" ]] && chmod ${_permissions} "${_file}"
+  for _file in "${_files[@]}" ; do
+    if file_exists "${_file}" ; then
+      chmod ${_permissions} "${_file}"
+    else
+      error "${extension} ${action} ${FUNCNAME}()\n => Cannot chmod file ${_file} to ${_permissions} as the file does not exist."
+    fi
   done
 }
 
@@ -276,7 +345,24 @@ chmod_paths()
   local _permissions="$1" _path; shift
 
   for _path in "${@}" ; do
-    [[ -d "${_path}" ]] && chmod -R ${_permissions} "${_path}"
+    if directory_exists "${_directory}" ; then
+      chmod ${_permissions} "${_path}"
+    else
+      error "${extension} ${action} ${FUNCNAME}()\n => Cannot chmod directory ${_path} to ${_permissions} as the directory does not exist."
+    fi
+  done
+}
+
+chmod_paths_recursively()
+{
+  local _permissions="$1" _path; shift
+
+  for _path in "${@}" ; do
+    if directory_exists "${_directory}" ; then
+      chmod -R ${_permissions} "${_path}"
+    else
+      error "${extension} ${action} ${FUNCNAME}()\n => Cannot chmod directory ${_path} to ${_permissions} as the directory does not exist."
+    fi
   done
 }
 
@@ -284,58 +370,233 @@ enter()
 {
   local _path="$1"
 
-  if [[ ! -d "${_path}" ]] ; then
-    fail "Could not enter directory ${_path}."
-  else
-    builtin cd "${_path}"
-  fi
+  builtin cd "${_path}" ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => Could not enter directory ${_path}."
 }
 
 hash_file()
 {
-  [[ -f "$1" ]] || fail "db() => Usage: $0 database key [value]"
+  local _file="${1:-}" ; shift
+  local _key="${2:-}" ; shift
 
-  database_file="$1" ; shift
-  key="$1"           ; shift
+  [[ -f "${_file}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => File path/name not given.\n => Usage: $0 <filename> <key> [value]"
 
-  ensure_paths_exist $(dirname $database_file)
-  ensure_files_exist "$database_file"
+  ensure_paths_exist $(dirname $_file)
 
-  [[ -n "$key" ]] || fail "usage: $0 database key [value]"
+  ensure_files_exist "$_file"
+
+  [[ -n "${_key}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => Key not given.\n => Usage: $0 <filename> <key> [value]"
 
   value="$*"
   case "$value" in
     unset|delete)
-      sed -i.tmp "s#^$key=.*\$##" $database_file
+      sed -i.tmp "s#^${_key}=.*\$##" "${_file}"
       ;;
     *)
       if [[ -z "$value" ]] ; then # get
-        awk -F= '/^'"${key}"'=/{print $2}' "$database_file"
+        awk -F= '/^'"${key}"'=/{print $2}' "$_file"
       else # set
-        if ! awk -F= "/^'"$key"'=/{print $2}" "$database_file" >/dev/null 2>&1; then
-          echo "$key=$value" >> $database_file
+        if ! awk -F= "/^'"${_key}"'=/{print $2}" "${_file}" >/dev/null 2>&1; then
+          echo "${_key}=$value" >> "${_file}"
         else # overwrite
-          sed -i.tmp "s#^$key=.*\$#$key=$value#" "$database_file"
+          sed -i.tmp "s#^${_key}=.*\$#${_key}=$value#" "${_file}"
         fi
       fi
       ;;
   esac
 }
 
-# File conditional functions
-file_is_executable() { [[ -x "$1" ]] ; }
-file_exists() { [[ -f "$1" ]] ; }
-file_is_nonempty() { [[ -s "$1" ]] ; }
-file_is_empty() { [[ -f "$1" && ! -s "$1" ]] ; }
-file_is_missing() { [[ ! -f "$1" ]] ; }
-file_is_empty_or_missing() { [[ ! -f "$1" ]] || [[ ! -s "$1" ]] ; }
+file_is_executable()
+{
+  local _file="${1:-}"
+
+  [[ -n "${_file}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => File path/name was not given!"
+
+  [[ -x "${_file}" ]]
+}
+
+file_exists()
+{
+  local _file="${1:-}"
+
+  [[ -n "${_file}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => File path/name was not given!"
+
+  [[ -f "${_file}" ]]
+}
+
+file_is_nonempty()
+{
+  local _file="${1:-}"
+
+  [[ -n "${_file}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => File path/name was not given!"
+
+  [[ -s "${_file}" ]]
+}
+
+file_is_empty()
+{
+  local _file="${1:-}"
+
+  [[ -n "${_file}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => File path/name was not given!"
+
+  [[ -f "${_file}" && ! -s "${_file}" ]]
+}
+
+file_is_missing()
+{
+  local _file="${1:-}"
+
+  [[ -n "${_file}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => File path/name was not given!"
+
+  [[ ! -f "${_file}" ]]
+}
+
+file_is_empty_or_missing() {
+  local _file="${1:-}"
+
+  [[ -n "${_file}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => File path/name was not given!"
+
+  [[ ! -f "${_file}" || ! -s "${_file}" ]] ;
+}
+
 file_contains()
 {
-  local _file="${1}" _string="${2}"
-  grep -q "${_string}" "${_file}" 2>/dev/null
+  local _file="${1:-}" _pattern="${2:-}"
+
+  [[ -n "${_file}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => File path/name was not given!"
+
+  [[ -n "${_pattern}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => String pattern for search was not given!"
+
+  grep "${_pattern}" "${_file}" >/dev/null 2>&1
 }
-symlink_exists() { [[ -L "$1" ]] ; }
+
+symlink_exists()
+{
+  local _file="${1:-}"
+
+  [[ -n "${_file}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => File path/name was not given!"
+
+  [[ -L "${_file}" ]]
+}
 
 # Directory conditional functions
-directory_exists() { [[ -d "$1" ]] ; }
+directory_exists()
+{
+  local _directory="${1:-}"
+  [[ -n "${_directory}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => Directory name/path was not given!"
+
+  [[ -d "$_directory" ]]
+}
+
+directories_in()
+{
+  local _path="${1:-}"
+
+  [[ -n "${path}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => Directory name/path was not given!"
+
+  [[ -d "${_path}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => '${_path}' is not a directory!"
+
+  find "${_path}" -mindepth 1 -maxdepth 1 -type d
+}
+
+directories_in_matching()
+{
+  local _path="${1:-}" _pattern="${2:-}"
+
+  [[ -n "${path}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => Directory name/path was not given!"
+
+  [[ -d "${_path}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => '${_path}' is not a directory!"
+
+  [[ -n "${_pattern}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => '${_path}' is not a directory!"
+
+  find "${_path}" -mindepth 1 -maxdepth 1 -type d
+}
+
+directories_under()
+{
+  local _path="${1:-}"
+
+  [[ -n "${path}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => Directory name/path was not given!"
+
+  [[ -d "${_path}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => '${_path}' is not a directory!"
+
+  find "${_path}" -mindepth 1 -type d
+}
+
+directories_under_matching()
+{
+  local _path="${1:-}" _pattern="${2:-}"
+
+  [[ -n "${path}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => Directory name/path was not given!"
+
+  [[ -d "${_path}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => '${_path}' is not a directory!"
+
+  [[ -n "${_pattern}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => '${_path}' is not a directory!"
+
+  find "${_path}" -mindepth 1 -iname "${_pattern}" -type d
+}
+
+files_in()
+{
+  local _path="${1:-}"
+
+  [[ -n "${path}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => Directory name/path was not given!"
+
+  [[ -d "${_path}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => '${_path}' is not a directory!"
+
+  find "${_path}" -mindepth 1 -maxdepth 1 -type f
+}
+
+files_under()
+{
+  local _path="${1:-}"
+
+  [[ -n "${path}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => Directory name/path was not given!"
+
+  [[ -d "${_path}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => '${_path}' is not a directory!"
+
+  find "${_path}" -mindepth 1 -type f
+}
+
+files_under_matching()
+{
+  local _path="${1:-}" _pattern="${2:-}"
+
+  [[ -n "${path}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => Directory name/path was not given!"
+
+  [[ -d "${_path}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => '${_path}' is not a directory!"
+
+  [[ -n "${_pattern}" ]] ||
+    fail "${extension} ${action} ${FUNCNAME}()\n => '${_path}' is not a directory!"
+
+  find "${_path}" -mindepth 1 -iname "${_pattern}" -type f
+}
 
