Added verbosity to installer. Backtrace enhancement.

diff --git a/modules/bash/logging/dsl b/modules/bash/logging/dsl
--- a/modules/bash/logging/dsl
+++ b/modules/bash/logging/dsl
@@ -28,7 +28,10 @@ succeed() {
 
 fail() {
   error "$*"
+  #set -e
+  #false # => This should trigger the backtrace?
   backtrace
+  #
   exit 1
 }
 
@@ -36,10 +39,18 @@ backtrace()
 {
   local _source _function _line
 
-  printf "%s\n" "Trace:" 1>&2
-  printf "  %6s %6s %-20s %-55s\n" "Depth" "Line" "Function" "File" 1>&2
 
-  for (( index = 2 ; index < (${#FUNCNAME[@]}) ; ++index )) ; do
+  local _lineno="${1}" _message="${2}" _status="${3:-1}"
+
+  if [[ -n "${_message}" ]] ; then
+    printf "%s" "Error on or around line ${_lineno}:\n\"${_message}\"\nExiting with status ${_status}"
+  else
+    printf "%s" "Error on or around line ${_lineno}:\nExiting with status ${_status}"
+  fi
+
+  printf "  %6s %6s %-20s %-55s\n" "Trace" "Line" "Function" "File" 1>&2
+
+  for (( index = 0 ; index < (${#FUNCNAME[@]}) ; ++index )) ; do
     # line="${LINENO} > "
     _source="${BASH_SOURCE[${index}]}" # "##${bdsm_path}}"
     _function="${FUNCNAME[${index}]:+${FUNCNAME[${index}]}()}"
@@ -50,5 +61,7 @@ backtrace()
     printf " %-20s" "${_function}" 1>&2
     printf " %-55s\n" "${_source} " 1>&2
   done
+
+  exit "${_status}"
 }
 
diff --git a/modules/bash/trace/dsl b/modules/bash/trace/dsl
--- a/modules/bash/trace/dsl
+++ b/modules/bash/trace/dsl
@@ -7,7 +7,7 @@ set_ps4()
 
 enable_trace()
 {
-  [[ ${trace_flag:-0} -eq 1 ]] || return
+  [[ ${trace_flag:-0} -eq 1 ]] || return 0
 
   export trace_flag
   set -o xtrace
@@ -15,9 +15,54 @@ enable_trace()
 
 enable_debug()
 {
-  [[ ${debug_flag:-0} -eq 1 ]] || return
+  [[ ${debug_flag:-0} -eq 1 ]] || return 0
 
   export debug_flag
   set -o verbose
+}
+
+enable_backtrace()
+{
+  trap 'backtrace ${lineno}' ERR
+}
+
+backtrace()
+{
+  echo "\n\$?: $?\n"
+
+  local _source _function _line
+
+  local _message="${1}" _status="${2:-0}" _string=""
+
+  [[ ${_status} -gt 0 ]] ||
+    return 0 # If the return status was success, do not print a backtrace
+
+  echo "\$*: $*"
+
+  _string+="On or around line ${BASH_LINENO[0]}"
+  _string+=" of ${BASH_SOURCE[0]}"
+  _string+=" in ${FUNCNAME[0]}()"
+
+  [[ -n "${_message}" ]] && _string+="  Message: ${_message}"
+
+  _string+="Exiting with status ${_status}"
+
+  printf "%s" "${_string}"
+
+  printf "  %6s %6s %-20s %-55s\n" "Trace" "Line" "Function" "File" 1>&2
+
+  for (( index = 0 ; index < (${#FUNCNAME[@]}) ; ++index )) ; do
+    # line="${LINENO} > "
+    _source="${BASH_SOURCE[${index}]}" # "##${bdsm_path}}"
+    _function="${FUNCNAME[${index}]:+${FUNCNAME[${index}]}()}"
+    _line=${BASH_LINENO[$(( index - 1 ))]}
+
+    printf "  %5d." "$((${#FUNCNAME[@]} - index ))" 1>&2
+    printf " %6s" "${_line}" 1>&2
+    printf " %-20s" "${_function}" 1>&2
+    printf " %-55s\n" "${_source} " 1>&2
+  done
+
+  exit "${_status}"
 }
 
