Mirror sets install behavior.

diff --git a/core/cli/modules/shell/ext/dsl b/core/cli/modules/shell/ext/dsl
--- a/core/cli/modules/shell/ext/dsl
+++ b/core/cli/modules/shell/ext/dsl
@@ -60,6 +60,19 @@ ext_list_known()
 
 ext_install()
 {
+  local _name _names="${1:-}" _uri=${2:-}
+  shift || fail "$FUNCNAME: Cannot install a ext; No ext name was given."
+
+  _names=(${_names//,/ })
+
+  for _name in ${_names[@]}
+  do
+    log_step "bdsm_${_name}" extension_install "${_name}" ${_uri}
+  done
+}
+
+extension_install()
+{
   local _name="${1:-}"
   shift || fail "$FUNCNAME: Cannot install extension; No extension name was given."
 
