Move FUNCNAME into fail/error, thanks Michael :)

diff --git a/core/cli/modules/shell/ext/dsl b/core/cli/modules/shell/ext/dsl
--- a/core/cli/modules/shell/ext/dsl
+++ b/core/cli/modules/shell/ext/dsl
@@ -61,7 +61,7 @@ ext_list_known()
 ext_install()
 {
   local _name _names="${1:-}" _uri=${2:-}
-  shift || fail "$FUNCNAME: Cannot install a ext; No ext name was given."
+  shift || fail "Cannot install a ext; No ext name was given."
 
   _names=(${_names//,/ })
 
@@ -74,7 +74,7 @@ ext_install()
 extension_install()
 {
   local _name="${1:-}"
-  shift || fail "$FUNCNAME: Cannot install extension; No extension name was given."
+  shift || fail "Cannot install extension; No extension name was given."
 
   local _uri="${1:-}"
   shift || _uri=$( awk -F = "/^${_name}=/ {print \$2 }" < "${sm_path}/core/cli/config/known_ext" | tail -n 1 )
@@ -82,7 +82,7 @@ extension_install()
   local _identifier="$(scm_identifier "${_uri}")"
 
   [[ -n "${_uri}" ]] ||
-    error "$FUNCNAME: uri not given and cannot find ${_name} in known extensions."
+    error "uri not given and cannot find ${_name} in known extensions."
 
   local _identifier="$(scm_identifier "${_uri}")"
 
diff --git a/core/cli/modules/shell/sets/dsl b/core/cli/modules/shell/sets/dsl
--- a/core/cli/modules/shell/sets/dsl
+++ b/core/cli/modules/shell/sets/dsl
@@ -67,7 +67,7 @@ sets_list_known()
 sets_install()
 {
   local _name _names="${1:-}" _uri=${2:-}
-  shift || fail "$FUNCNAME: Cannot install a set; No set name was given."
+  shift || fail "Cannot install a set; No set name was given."
 
   _names=(${_names//,/ })
 
@@ -80,7 +80,7 @@ sets_install()
 set_install()
 {
   local _name="${1:-}"
-  shift || fail "$FUNCNAME: Cannot install a set; No set name was given."
+  shift || fail "Cannot install a set; No set name was given."
 
   local _uri="${1:-}"
   shift || _uri=$( awk -F = "/^${_name}=/ {print \$2 }" < "${sm_path}/core/cli/config/known_sets" | tail -n 1 )
@@ -88,7 +88,7 @@ set_install()
   local _identifier="$(scm_identifier "${_uri}")"
 
   [[ -n "${_uri}" ]] ||
-    error "$FUNCNAME: uri not given and cannot find ${_name} in known extension sets."
+    error "uri not given and cannot find ${_name} in known extension sets."
 
   ensure_paths_exist "${extension_sets_home}"
   enter "${extension_sets_home}"
diff --git a/core/ext/modules/shell/environment/dsl b/core/ext/modules/shell/environment/dsl
--- a/core/ext/modules/shell/environment/dsl
+++ b/core/ext/modules/shell/environment/dsl
@@ -40,7 +40,7 @@ command_exists()
 {
   trace_filter environment
   local _name="${1:-}"
-  shift || fail "$FUNCNAME: Cannot test if command exists;"\
+  shift || fail "Cannot test if command exists;"\
     " No command name was given."
 
   if command -v "${_name}" > /dev/null 2>&1
@@ -95,7 +95,7 @@ is_a_function()
 {
   trace_filter environment
   local _name="${1:-}"
-  shift || fail "$FUNCNAME: Cannot test if function exists;"\
+  shift || fail "Cannot test if function exists;"\
     " No function name was given."
 
   if declare -f "${_name}" >/dev/null 2>&1
diff --git a/core/ext/modules/shell/extensions/manipulation/dsl b/core/ext/modules/shell/extensions/manipulation/dsl
--- a/core/ext/modules/shell/extensions/manipulation/dsl
+++ b/core/ext/modules/shell/extensions/manipulation/dsl
@@ -32,7 +32,7 @@
 extension_version()
 {
   local _extension="${1:-}"
-  shift || fail "$FUNCNAME: Cannot retrieve extension version;"\
+  shift || fail "Cannot retrieve extension version;"\
     " No extension was given."
   true ${extension_path:="${extensions_path}/${_extension}"}
 
@@ -97,7 +97,7 @@ extension_license()
   local _extension="${1:-${extension}}"
 
   variable_is_nonempty _extension ||
-    fail "$FUNCNAME: Cannot display extension license;"\
+    fail "Cannot display extension license;"\
     " Extension name was not given."
 
   cat -v "${extensions_path}/${_extension}/LICENSE"
@@ -145,7 +145,7 @@ extension_actions()
 {
   local _extension="${1:-}" _files _file _actions=()
 
-  shift || fail "$FUNCNAME; Cannot list actions for extension;"\
+  shift || fail "Cannot list actions for extension;"\
     " No extension was given."
 
   path_exists "${extension_actions_path}" || return 0
@@ -198,11 +198,11 @@ extension_install()
   # TODO: This should likely be removed now with sets/ext ?
 
   local _extension="${1:-}" _src="${2:-${_extension}}"
-  shift || fail "$FUNCNAME: Cannot install extension;"\
+  shift || fail "Cannot install extension;"\
     " No extension name was given."
 
   extension_is_valid "${extensions_src_path}/${_src}" ||
-    error "$FUNCNAME: ${extensions_src_path}/${_src} is not a valid extension,"\
+    error "${extensions_src_path}/${_src} is not a valid extension,"\
     "as it is missing VERSION and/or actions/help files."
 
   log "Installing ${_extension}"
diff --git a/core/ext/modules/shell/help/dsl b/core/ext/modules/shell/help/dsl
--- a/core/ext/modules/shell/help/dsl
+++ b/core/ext/modules/shell/help/dsl
@@ -84,7 +84,7 @@ show_help()
 description()
 {
   local _description="$*"
-  shift || fail "$FUNCNAME: Cannot add description to help; description given."
+  shift || fail "Cannot add description to help; description given."
   help_descriptions+=("$*")
 }
 
@@ -178,8 +178,8 @@ help_description()
 action()
 {
   local _name="${1:-}" _description="${2:-}"
-  shift || fail "$FUNCNAME: An action name must be provided:\naction {name} {description}."
-  shift || fail "$FUNCNAME: An description must be provided:\naction {name} {description}."
+  shift || fail "An action name must be provided:\naction {name} {description}."
+  shift || fail "An description must be provided:\naction {name} {description}."
 
   help_action_names+=( "${_name}" )
   help_action_descriptions+=( "${_description}" )
diff --git a/core/ext/modules/shell/os/dsl b/core/ext/modules/shell/os/dsl
--- a/core/ext/modules/shell/os/dsl
+++ b/core/ext/modules/shell/os/dsl
@@ -51,7 +51,7 @@ init_scripts_path()
         then
           printf "/etc/rc.d"
         else
-          fail "$FUNCNAME: Unknown init scripts directory (/etc/init.d or /etc/rc.d not found)."
+          fail "Unknown init scripts directory (/etc/init.d or /etc/rc.d not found)."
         fi
         ;;
     esac
@@ -730,7 +730,7 @@ os_version_patch()
 os_open()
 {
   local _uri="${1:-}"
-  shift || fail "$FUNCNAME: Cannot open URI; No uri was given."
+  shift || fail "Cannot open URI; No uri was given."
 
   if command_exists open
   then
diff --git a/core/ext/modules/shell/package/dsl b/core/ext/modules/shell/package/dsl
--- a/core/ext/modules/shell/package/dsl
+++ b/core/ext/modules/shell/package/dsl
@@ -45,7 +45,7 @@
 package_error()
 {
   local _message="${1:-}" _log="${2:-}"
-  shift || fail "$FUNCNAME: Cannot print a package error; No message was provided."
+  shift || fail "Cannot print a package error; No message was provided."
 
   if [[ -n ${_log} ]] && file_exists ${_log}
   then # Append tail of error log to the error message.
@@ -165,7 +165,7 @@ package_definition()
       #  eval "${key}=${value}"
       #  ;;
       *)
-        fail "$FUNCNAME: Unknown key '${key}' (value: ${value})."
+        fail "Unknown key '${key}' (value: ${value})."
       ;;
     esac
   done
@@ -217,52 +217,52 @@ package_cli()
       prefix)
         packages_path="${_package_args[$((++index))]}"
         [[ -n "${packages_path}" ]] ||
-          error "$FUNCNAME: a path must follow keyword 'prefix'"
+          error "a path must follow keyword 'prefix'"
         ;;
       src)
         src_path="${_package_args[$((++index))]}"
         [[ -n "${src_path}" ]] ||
-          error "$FUNCNAME: a path must follow keyword 'src'"
+          error "a path must follow keyword 'src'"
         ;;
       data)
         data_path="${_package_args[$((++index))]}"
         [[ -n "${data_path}" ]] ||
-          error "$FUNCNAME: a path must follow keyword 'data'"
+          error "a path must follow keyword 'data'"
         ;;
       user)
         package_user="${_package_args[$((++index))]}"
         [[ -n "${package_user}" ]] ||
-          error "$FUNCNAME: a user name must follow keyword 'user'"
+          error "a user name must follow keyword 'user'"
         ;;
       version)
         package_version="${_package_args[$((++index))]}"
         [[ -n "${package_version}" ]] ||
-          error "$FUNCNAME: a version number string must follow keyword 'version'"
+          error "a version number string must follow keyword 'version'"
         ;;
       base_url)
         package_base_url="${_package_args[$((++index))]}"
         [[ -n "${package_base_url}" ]] ||
-          error "$FUNCNAME: a base path url must follow keyword 'base_url'"
+          error "a base path url must follow keyword 'base_url'"
         ;;
       file)
         package_file="${_package_args[$((++index))]}"
         [[ -n "${package_file}" ]] ||
-          error "$FUNCNAME: a path must follow keyword 'file'"
+          error "a path must follow keyword 'file'"
         ;;
       dir)
         package_directory="${_package_args[$((++index))]}"
         [[ -n "${package_directory}" ]] ||
-          error "$FUNCNAME: a single extracted directory name must follow keyword 'dir'"
+          error "a single extracted directory name must follow keyword 'dir'"
         ;;
       archive_format)
         archive_format="${_package_args[$((++index))]}"
         [[ -n "${archive_format}" ]] ||
-          error "$FUNCNAME: an archive format (tar.gz,tar.bz2,tar.xz,zip,...) must follow keyword 'archive_format'"
+          error "an archive format (tar.gz,tar.bz2,tar.xz,zip,...) must follow keyword 'archive_format'"
         ;;
       md5)
         package_md5="${_package_args[$((++index))]}"
         [[ -n "${package_md5}" ]] ||
-          error "$FUNCNAME: an md5 sum string must follow keyword 'md5'"
+          error "an md5 sum string must follow keyword 'md5'"
         ;;
       force)
         force_flag=1
@@ -302,7 +302,7 @@ package_init()
   package_name="${1:-${package_name:-${extension}}}"
 
   [[ -n "${package_name}" ]] ||
-    fail "$FUNCNAME(): Package name must be given as first parameter.\n"
+    fail "Package name must be given as first parameter.\n"
 
   case "${package_name}" in
     *=*) # exact version specifier
@@ -361,7 +361,7 @@ package_init()
 
   # This check should only happen in places that require a version...
   #[[ -n "${package_version}" ]] ||
-  #  fail "$FUNCNAME(): Package version must be specified.\n"\
+  #  fail "Package version must be specified.\n"\
   #  "(For example version=x.y.z set in extension's config/defaults file.)\n"
 
   fhs_dirs=( bin etc include lib libexec sbin share man )
@@ -1044,7 +1044,7 @@ package_deactivate()
   local _package="${package_name}" _package_version="${2:-${package_version}}" \
     _file _files _version
 
-  [[ -n "${_package}" ]] || fail "$FUNCNAME: Cannot deactivate package;"\
+  [[ -n "${_package}" ]] || fail "Cannot deactivate package;"\
     " Package name must be given."
 
   if symlink_exists "${packages_path}/${_package}/active"
@@ -1125,9 +1125,9 @@ package_deactivate()
 package_activate_if_first()
 {
   local _package="${1:-}" _version="${2:-}"
-  shift || fail "$FUNCNAME: Cannot activate package, if first;"\
+  shift || fail "Cannot activate package, if first;"\
     " Package name must be given as first parameter."
-  shift || fail "$FUNCNAME: Cannot activate package, if first;"
+  shift || fail "Cannot activate package, if first;"
     " Package version must be given as second parameter."
 
   if path_exists "${install_path}"
@@ -1175,7 +1175,7 @@ package_activate_if_first()
 package_ldconfig()
 {
   local _package="${1:-${package_name}}" _path _files _ldconfig="/sbin/ldconfig"
-  [[ -n "${_package}" ]] || fail "$FUNCNAME: Cannot run ldconfig for a package;"\
+  [[ -n "${_package}" ]] || fail "Cannot run ldconfig for a package;"\
     "Package name must be given."
 
   #  path_exists "${packages_path}/${_package}/active/lib" ||
@@ -1243,7 +1243,7 @@ package_ldconfig()
 package_profile_d()
 {
   local _package="${1:-${package_name}}"
-  [[ -n "${_package}" ]] || fail "$FUNCNAME: Cannot run setup profile_d for a package;"\
+  [[ -n "${_package}" ]] || fail "Cannot run setup profile_d for a package;"\
     "Package name must be given."
 
   template_exists "profile.d.template" || return 0
@@ -1397,11 +1397,11 @@ package_patch()
 package_apply_patches()
 {
   local _patch _patches=("$@")
-  shift || fail "$FUNCNAME: Cannot apply patches; No patches were given."
+  shift || fail "Cannot apply patches; No patches were given."
 
   for _patch in "${_patches[@]}"
   do
-    error "$FUNCNAME: TODO: patch application is NIY (see package_patch())"
+    error "TODO: patch application is NIY (see package_patch())"
   done
 }
 
@@ -1493,7 +1493,7 @@ package_usage() {
 package_is_active()
 {
   local _name="${1:-}" _version="${2:-}"
-  shift || fail "$FUNCNAME: Cannot query if a package is active;"\
+  shift || fail "Cannot query if a package is active;"\
     " No package name was given, or name is empty."
 
   local _path="${packages_path}/${_name}"
@@ -1543,11 +1543,11 @@ package_must_be_active()
 {
   local _name="${1:-}"
 
-  shift || fail "$FUNCNAME: Cannot ensure that package is active;"\
+  shift || fail "Cannot ensure that package is active;"\
     "No package name was given (or name is empty.)"
 
   package_is_active "${_name}" ||
-    error "$FUNCNAME: Install/activate the node package extension, before installing ${_name}."
+    error "Install/activate the node package extension, before installing ${_name}."
 }
 
 #
@@ -1586,7 +1586,7 @@ package_must_be_active()
 packages_must_be_active()
 {
   local _package _packages="$@"
-  shift || fail "$FUNCNAME: Cannot ensure that packages are active;"\
+  shift || fail "Cannot ensure that packages are active;"\
     "No packages were given."
 
   for _package in "${_packages[@]}"
@@ -1788,7 +1788,7 @@ package_man()
   MANPATH="${package_path}/man"
 
   path_exists $MANPATH ||
-    error "$FUNCNAME: No man page available for package ${package_name} ${package_version}"
+    error "No man page available for package ${package_name} ${package_version}"
 
   man ${extension_actions[@]:-${package_name}} || true
 }
diff --git a/core/ext/modules/shell/paths/dsl b/core/ext/modules/shell/paths/dsl
--- a/core/ext/modules/shell/paths/dsl
+++ b/core/ext/modules/shell/paths/dsl
@@ -40,7 +40,7 @@ ensure_paths_exist()
 
   local _path _paths=("$@")
 
-  shift || fail "FUNCNAME: Cannot ensure paths exist; No paths were given."
+  shift || fail "Cannot ensure paths exist; No paths were given."
 
   for _path in "${_paths[@]}"
   do
@@ -103,7 +103,7 @@ remove_paths()
 {
   trace_filter filesystem
   local _path _paths=("$@")
-  shift || fail "$FUNCNAME: Cannot remove paths; No paths were given."
+  shift || fail "Cannot remove paths; No paths were given."
 
   removed_paths=()
   nonexistant_paths=()
@@ -112,18 +112,18 @@ remove_paths()
   do
     if [[ -L "${_path}" ]]
     then
-      rm -f "${_path}" || fail "$FUNCNAME: Could not remove the entity '${_entity}';"\
+      rm -f "${_path}" || fail "Could not remove the entity '${_entity}';"\
           "'rm' command failed with error code '$?'."
       removed_paths+=("${_path}")
     elif [[ -d "${_path}" ]]
     then
-      rm -rf "${_path}" || fail "$FUNCNAME: Could not remove the entity '${_entity}';"\
+      rm -rf "${_path}" || fail "Could not remove the entity '${_entity}';"\
           "'rm' command failed with error code '$?'."
       removed_paths+=("${_path}")
 
     elif [[ -e "${_path}" ]]
     then
-      fail "$FUNCNAME: Cannot remove the path '${_path}', as it is a file."
+      fail "Cannot remove the path '${_path}', as it is a file."
 
     else
       nonexistant_paths+=("${_path}")
@@ -176,22 +176,22 @@ move_directory()
     case "${token}" in
       to)
         _target="${1}"
-        shift || fail "$FUNCNAME: Target path must be provided after keyword 'to'"
+        shift || fail "Target path must be provided after keyword 'to'"
         ;;
 
       from)
         _source="${1}"
-        shift || fail "$FUNCNAME: Source path must be provided after keyword 'from'"
+        shift || fail "Source path must be provided after keyword 'from'"
         ;;
 
       mode)
         _mode="${1}"
-        shift || fail "$FUNCNAME: Mode must be provided after keyword 'mode'"
+        shift || fail "Mode must be provided after keyword 'mode'"
         ;;
 
       owner)
         _owner="${1}"
-        shift || fail "$FUNCNAME: Owner must be provided after keyword 'owner'"
+        shift || fail "Owner must be provided after keyword 'owner'"
         ;;
 
       *) # If the token is unknown
@@ -268,12 +268,12 @@ copy_paths()
     case "${token}" in
       to)
         _target="${1}"
-        shift || fail "$FUNCNAME: Target path must be given after keyword 'from'"
+        shift || fail "Target path must be given after keyword 'from'"
         ;;
 
       from)
         _directories+=( "${1}" )
-        shift || fail "$FUNCNAME: Source path must be given after keyword 'from'"
+        shift || fail "Source path must be given after keyword 'from'"
         ;;
 
       *)
@@ -282,19 +282,19 @@ copy_paths()
     esac
   done
 
-  variable_is_nonempty _target   || fail "$FUNCNAME: Cannot move file; Target must be given."
-  array_is_nonempty _directories || fail "$FUNCNAME: Cannot copy; Directories must be given."
+  variable_is_nonempty _target   || fail "Cannot move file; Target must be given."
+  array_is_nonempty _directories || fail "Cannot copy; Directories must be given."
 
   ensure_paths_exist "${_target}"
 
   for _directory in "${_directories[@]}"
   do
     [[ -d "${_directory}" ]] ||
-      error "$FUNCNAME: Cannot copy directory ${_directory} to ${_target},"\
+      error "Cannot copy directory ${_directory} to ${_target},"\
       "as the directory '${_directory}' does not exist (in '$PWD')."
 
     cp -Rf "${_directory}" "${_target}/" ||
-      fail "$FUNCNAME: Could not copy the entity '${_entity}',"\
+      fail "Could not copy the entity '${_entity}',"\
       "as the 'cp -Rf' command failed with error code '$?'."
   done
 }
@@ -343,11 +343,11 @@ copy_directory()
     case "${token}" in
       to)
       _target="${1}"
-      shift || fail "$FUNCNAME: Target path must be given after keyword 'from'"
+      shift || fail "Target path must be given after keyword 'from'"
       ;;
       from)
       _source="${1}"
-      shift || fail "$FUNCNAME: Source path must be given after keyword 'from'"
+      shift || fail "Source path must be given after keyword 'from'"
       ;;
       *)
         if variable_is_empty _source
@@ -362,11 +362,11 @@ copy_directory()
     esac
   done
 
-  [[ -n "${_source}" ]] || fail "$FUNCNAME: Cannot move file; Source must be given."
-  [[ -n "${_target}" ]] || fail "$FUNCNAME: Cannot move file, Target must be given."
+  [[ -n "${_source}" ]] || fail "Cannot move file; Source must be given."
+  [[ -n "${_target}" ]] || fail "Cannot move file, Target must be given."
 
   cp -Rf "${_source}" "${_target}" ||
-    fail "$FUNCNAME: Could not copy '${_source}' to '${_target}',"\
+    fail "Could not copy '${_source}' to '${_target}',"\
       "as the 'cp' command failed with error code '$?'."
 }
 
@@ -415,11 +415,11 @@ chown_paths()
 
   (( _recursive_flag == 0 )) || _flags+=(-R)
 
-  shift || fail "$FUNCNAME: Cannot chown paths; user[:group] was not given as the first parameter."
+  shift || fail "Cannot chown paths; user[:group] was not given as the first parameter."
 
   local _paths=("$@")
 
-  array_is_nonempty _paths || fail "$FUNCNAME: Cannot chown paths; No files were given."
+  array_is_nonempty _paths || fail "Cannot chown paths; No files were given."
 
   for _path in "${_paths[@]}"
   do
@@ -538,7 +538,7 @@ enter()
   shift || fail "Cannot enter path; No path was given."
 
   [[ -d "${_path}" ]] ||
-    fail "$FUNCNAME: Cannot enter path '${_path}'; Path does not exist."
+    fail "Cannot enter path '${_path}'; Path does not exist."
 
   builtin cd "${_path}" ||
     fail "Could not cd into the given path '${_path}'; "\
@@ -585,7 +585,7 @@ path_exists()
 {
   trace_filter filesystem
   local _path="${1:-}"
-  shift || fail "$FUNCNAME: Cannot check if path exists; No name/path was given."
+  shift || fail "Cannot check if path exists; No name/path was given."
   [[ -d "$_path" ]]
 }
 
@@ -636,9 +636,9 @@ directories_in()
 {
   trace_filter filesystem
   local _path="${1:-}"
-  shift || fail "$FUNCNAME: Directory name/path was not given!"
+  shift || fail "Directory name/path was not given!"
 
-  [[ -d "${_path}" ]] || fail "$FUNCNAME: '${_path}' is not a directory!"
+  [[ -d "${_path}" ]] || fail "'${_path}' is not a directory!"
 
   find "${_path}" -mindepth 1 -maxdepth 1 -type d
 }
@@ -651,11 +651,11 @@ directories_in_matching()
 {
   trace_filter filesystem
   local _pattern _path="${1:-}"
-  shift     || fail "$FUNCNAME: Directory name/path was not given!"
-  [[ -d "${_path}" ]]    || fail "$FUNCNAME: '${_path}' is not a directory!"
+  shift     || fail "Directory name/path was not given!"
+  [[ -d "${_path}" ]]    || fail "'${_path}' is not a directory!"
 
   local _pattern="${2:-}"
-  shift  || fail "$FUNCNAME: '${_path}' is not a directory!"
+  shift  || fail "'${_path}' is not a directory!"
 
   find "${_path}" -mindepth 1 -maxdepth 1 -type d
 }
@@ -668,9 +668,9 @@ directories_under()
 {
   trace_filter filesystem
   local _path="${1:-}"
-  shift  || fail "$FUNCNAME: Directory name/path was not given!"
+  shift  || fail "Directory name/path was not given!"
 
-  [[ -d "${_path}" ]] || fail "$FUNCNAME: '${_path}' is not a directory!"
+  [[ -d "${_path}" ]] || fail "'${_path}' is not a directory!"
 
   find "${_path}" -mindepth 1 -type d
 }
@@ -683,13 +683,13 @@ directories_under_matching()
 {
   trace_filter filesystem
   local _path="${1:-}"
-  shift || fail "$FUNCNAME: Directory name/path was not given as the first parameter."
+  shift || fail "Directory name/path was not given as the first parameter."
 
   local _pattern="${1:-}"
-  shift || fail "$FUNCNAME: Pattern was not given as the second parameter."
+  shift || fail "Pattern was not given as the second parameter."
 
-  [[ -d "${_path}" ]]    || fail "$FUNCNAME: '${_path}' is not a directory!"
-  [[ -n "${_pattern}" ]] || fail "$FUNCNAME: '${_path}' is not a directory!"
+  [[ -d "${_path}" ]]    || fail "'${_path}' is not a directory!"
+  [[ -n "${_pattern}" ]] || fail "'${_path}' is not a directory!"
 
   find "${_path}" -mindepth 1 -iname "${_pattern}" -type d
 }
@@ -729,8 +729,8 @@ full_path()
 {
   trace_filter filesystem
   local _path="$1"
-  shift || fail "$FUNCNAME: Cannot go to path; No path was given."
-  [[ -d "${_path}" ]] || fail "$FUNCNAME: Path '${_path}' does not exist."
+  shift || fail "Cannot go to path; No path was given."
+  [[ -d "${_path}" ]] || fail "Path '${_path}' does not exist."
   (
   builtin cd "${_path}"
   pwd
diff --git a/core/sm/modules/shell/logging/dsl b/core/sm/modules/shell/logging/dsl
--- a/core/sm/modules/shell/logging/dsl
+++ b/core/sm/modules/shell/logging/dsl
@@ -126,7 +126,7 @@ warn()
 core_debug()
 {
   local type="$1"
-  shift || fail "$FUNCNAME: Debug type must be given as the first parameter."
+  shift || fail "Debug type must be given as the first parameter."
 
   if (( debug_flag == 1 )) && options_check "$debug_flags" "$type"
   then
@@ -182,8 +182,8 @@ debug()
 core_log_search()
 {
   local name="${1:-}" value="${2:-}"
-  shift || fail "$FUNCNAME: name must be given as the first parameter."
-  shift || fail "$FUNCNAME: value must be given as the second parameter."
+  shift || fail "name must be given as the first parameter."
+  shift || fail "value must be given as the second parameter."
 
   if (( debug_flag == 1 )) && options_check "$debug_flags" "search"
   then
@@ -282,7 +282,7 @@ log_todo()
 core_error()
 {
   set +o xtrace
-  printf "\nERROR: $*\n" >&2
+  printf "${FUNCNAME[1]}(): ERROR: $*\n" >&2
   set +o errtrace
   trap - ERR
   exit 1
@@ -381,7 +381,7 @@ core_fail()
 
 fail()
 {
-  core_fail "$@"
+  core_fail "${FUNCNAME[1]}(): $@"
 }
 
 #
@@ -459,7 +459,7 @@ set_ps4()
 core_trace_filter()
 {
   local _action="$1" old
-  shift || fail "$FUNCNAME: Filter action {start,stop} must be specified."
+  shift || fail "Filter action {start,stop} must be specified."
 
   case "${_action}" in
     start)
@@ -475,7 +475,7 @@ core_trace_filter()
       fi
       ;;
     *)
-      fail "$FUNCNAME: Unknown trace action ${_action}, use {start,stop}."
+      fail "Unknown trace action ${_action}, use {start,stop}."
       ;;
   esac
 
@@ -517,8 +517,8 @@ action_call()
 action_source()
 {
   local script="$1"
-  shift || fail "$FUNCNAME: No script was given as the first parameter."
-  [[ -r "$script" ]] || fail "$FUNCNAME: Could not find script to run: $script."
+  shift || fail "No script was given as the first parameter."
+  [[ -r "$script" ]] || fail "Could not find script to run: $script."
   trace_filter action
   source "$script"
 }
diff --git a/core/sm/modules/shell/modules/dsl b/core/sm/modules/shell/modules/dsl
--- a/core/sm/modules/shell/modules/dsl
+++ b/core/sm/modules/shell/modules/dsl
@@ -25,16 +25,16 @@ modules_initialize()
 
   for module in ${preload_modules[@]}
   do
-    module_or_error ${module} "$FUNCNAME: Cannot preload module: ${module}."
+    module_or_error ${module} "Cannot preload module: ${module}."
   done
 }
 
 reorder_path()
 {
   local part="${1:-}" extensions_path="${2:-}" extension="${3:-}"
-  shift || fail "$FUNCNAME: Path part must be given as the first parameter."
-  shift || fail "$FUNCNAME: Extensions path must be given as the second parameter."
-  shift || fail "$FUNCNAME: Extension name must be given as the third parameter."
+  shift || fail "Path part must be given as the first parameter."
+  shift || fail "Extensions path must be given as the second parameter."
+  shift || fail "Extension name must be given as the third parameter."
 
   local output="$extensions_path/$extension/$part/$*"
   rebuilded_path="${output// //}"
@@ -43,8 +43,8 @@ reorder_path()
 rebuild_path()
 {
   local part="$1" extensions_path="$2"
-  shift || fail "$FUNCNAME: Path part must be given as the first parameter."
-  shift || fail "$FUNCNAME: Extensions path must be given as the second parameter."
+  shift || fail "Path part must be given as the first parameter."
+  shift || fail "Extensions path must be given as the second parameter."
 
   local params="$*"
   reorder_path "${part}" "${extensions_path}" ${params//\// }
@@ -58,7 +58,7 @@ is_module()
 detect_module()
 {
   local extensions_path=$1 _module_path
-  shift || fail "$FUNCNAME: Extensions path must be given as the first parameter."
+  shift || fail "Extensions path must be given as the first parameter."
 
   rebuild_path "modules/shell" $extensions_path $@
   _module_path=${rebuilded_path}
@@ -179,7 +179,7 @@ in_search_paths()
 {
   trace_filter search
   local callback="${1:-}"
-  shift || fail "$FUNCNAME: Callback name must be given ast the first parameter."
+  shift || fail "Callback name must be given ast the first parameter."
   local args=( "$@" ) path
 
   for path in "${extensions_search_paths[@]}"
@@ -315,12 +315,12 @@ modules()
 {
   local _module _sm _extension _path _file _modules=("$@")
 
-  (( ${#_modules[@]} )) || fail "$FUNCNAME: No modules given to load."
+  (( ${#_modules[@]} )) || fail "No modules given to load."
 
   for _module in "${_modules[@]}"
   do
     module "${_module}" ||
-      fail "$FUNCNAME: Could not find module path for ${_module}."
+      fail "Could not find module path for ${_module}."
   done
 }
 
@@ -354,7 +354,7 @@ modules_reinitialize()
   local _module _modules=("$@") _loaded_modules _module_path _initialize_path
 
   array_is_nonempty _modules ||
-    fail "$FUNCNAME: Cannot load a module; No module name was given."
+    fail "Cannot load a module; No module name was given."
 
   _loaded_modules=" ${modules[*]} "
   for _module in "${_modules[@]}"
