Refactoring sets install into wrapping set install.

diff --git a/core/cli/modules/shell/sets/dsl b/core/cli/modules/shell/sets/dsl
--- a/core/cli/modules/shell/sets/dsl
+++ b/core/cli/modules/shell/sets/dsl
@@ -66,36 +66,37 @@ sets_list_known()
 
 sets_install()
 {
-  local _name="${1:-}" _uri="${2:-}"
+  local _name _names="${1:-}" _uri="${2:-}"
+  shift || fail "$FUNCNAME: Cannot install a set; No set name was given."
 
-  shift || fail "name must be the first parameter to sets_install()."
+  _names=(${_names//,/ })
 
-  [[ "${_name}" != "builtin" ]] ||
-    error "builtin extension set may not be (re-)installed, except by updating BDSM core (bdsm get head)."
+  for _name in ${_names[@]}
+  do
+    log_step "bdsm-${_name}" set_install "${_name}" "${_uri}"
+  done
+}
 
-  if [[ -n "${_uri}" ]]
-  then
-    shift
-  else
-    _uri=$( awk -F = "/^${_name}=/ {print \$2 }" < "${bdsm_path}/core/cli/config/known_sets" | tail -n 1 )
-  fi
+set_install()
+{
+  local _name="${1:-}"
+  shift || fail "$FUNCNAME: Cannot install a set; No set name was given."
 
-  [[ -n "${_uri}" ]] ||
-    error "Cannot find ${_name} in known extension sets list."
+  local _uri="${1:-}"
+  shift || _uri=$( awk -F = "/^${_name}=/ {print \$2 }" < "${bdsm_path}/core/cli/config/known_sets" | tail -n 1 )
 
   local _identifier="$(scm_identifier "${_uri}")"
 
-  log_step "bdsm-${_name}"
+  [[ -n "${_uri}" ]] ||
+    error "$FUNCNAME: uri not given and cannot find ${_name} in known extension sets."
+
   ensure_paths_exist "${extension_sets_home}"
   enter "${extension_sets_home}"
-  if fetch_uri "${_uri}" "${src_path}/${_identifier}" "$@"
-  then
-    remove_paths "${_name}"
-    copy_directory "${src_path}/${_identifier}" to "${_name}"
-    log_step success
-  else
-    log_step failure
-  fi
+
+  fetch_uri "${_uri}" "${src_path}/${_identifier}" "$@" || return $?
+
+  remove_paths "${_name}"
+  copy_directory "${src_path}/${_identifier}" to "${_name}"
 }
 
 sets_install_all()
@@ -201,10 +202,7 @@ sets_uninstall()
       fi
   fi
 
-  #TODO: are you sure ?
-
-  log "Uninstalling extension set: ${_name}."
-  rm -rf "${_name}"
+  log_step "Uninstalling extension set: ${_name}." rm -rf "${_name}"
 }
 
 sets_check_availability()
