Templates module complete.

diff --git a/core/ext/modules/shell/templates/dsl b/core/ext/modules/shell/templates/dsl
--- a/core/ext/modules/shell/templates/dsl
+++ b/core/ext/modules/shell/templates/dsl
@@ -3,7 +3,9 @@
 detect_template()
 {
   local extensions_path=$1 _module_path
-  shift
+  shift || fail "Cannot detect template;"\
+    " No extensions path given as first parameter."
+
   rebuild_path "templates" $extensions_path $@
   _template_path="${rebuilded_path}"
 
@@ -154,59 +156,29 @@ install_template()
     esac
   done
 
-  if template_exists "${_name}"
-  then
-    _template="${template_path}"
-    _name="$(basename "${_name}")"
-  else
-    fail "No template was found matching '${_name}'."
-  fi
+  template_exists "${_name}" || fail "Cannot install template; "\
+    "No template found matching '${_name}'."
 
-  # Create the target path if it does not exist. and then copy the template file
-  # to the target location and name given.
-  #
-  # If the mode variable is not empty then we change the files access mode
-  #
-  # If the owner variable is not empty then we change the owner of the file
-  #
-  # Otherwise if the target is not a directory, it must be a fully specified
-  # template name. Copy the template directly to the target as a file.
-  # TODO: Ensure that the target's path exists.
-  # If mode variable is not empty then change the file mode of the target.
-  # If owner variable is not empty then change the owner of the target
+  _template="${template_path}"
+  _name="$(basename "${_name}")"
+
   ensure_paths_exist "$(dirname "${_target}")"
 
   if path_exists "${_target}"
   then
-    if path_exists "${_target}/${_name}"
-    then
+    ! path_exists "${_target}/${_name}" ||
       fail "Cannot install the template '${_template}' to ${_target}/${_name},"\
         " as it is a directory."
-    else
-      copy_file "${_template}" to "${_target}/${_name}"
 
-      if variable_is_nonempty _mode
-      then
-        chmod "${_mode}" "${_target}/${_name}"
-      fi
+    copy_file "${_template}" to "${_target}/${_name}"
 
-      if variable_is_nonempty _owner
-      then
-        chown "${_owner}" "${_target}/${_name}"
-      fi
-    fi
+    variable_is_empty _mode  || chmod "${_mode}" "${_target}/${_name}"
+    variable_is_empty _owner || chown "${_owner}" "${_target}/${_name}"
   else
     copy_file --force "${_template}" to "${_target}"
 
-    if variable_is_nonempty _mode
-    then
-      chmod_files "${_mode}" "${_target}"
-    fi
-
-    if variable_is_nonempty _owner
-    then
-      chown_files "${_owner}" "${_target}"
-    fi
+    variable_is_empty _mode  || chmod_files "${_mode}" "${_target}"
+    variable_is_empty _owner || chown_files "${_owner}" "${_target}"
   fi
 }
 
@@ -255,34 +227,20 @@ install_template()
 # ### Code Walkthrough
 seed_template()
 {
-  # Store the first parameter into the template variable.
   local _template="${1:-}"
-  shift || fail "Cannot install template, as no template was given."
+  shift || fail "Cannot seed template;"\
+    " No template name was given as the first parameter."
 
-  # If the template variable is not empty, remove the template from the
-  # parameters list and store the remaining parameters into the hash variable.
-  # If the template file exists on the filesystem and if the hash array is
-  # nonempty and if the hash array contains an even number of elements, then
-  # loop over the hash and aggregate the replacement strings into their own
-  # array. Filter the template with the replacments, and if the filtering
-  # happened successfully, the timestamped template file will exist on the
-  # filesystem; move the timestamped version to the target.
-  #
-  # Otherwise, if no key/value pairs were specified, this is typically a
-  # programming error; send a fail message which will also trigger a
-  # backtrace allowing the developer to fix the issue quickly.
-  # Also if no template was given, or the template file does not exist on the
-  # filesystem, then fail with an error message and backtrace for debugging.
   local _hash=("$@") _strings=() temporary=${_template}.${timestamp}.$$
 
-  file_exists "${_template}" ||
-    fail "Cannot seed template; template file '${_template}' does not exist."
+  file_exists "${_template}" || fail "Cannot seed template;"\
+    " template file '${_template}' does not exist."
 
-  array_is_nonempty _hash ||
-    fail "Cannot seed template '${_template}'; No replacement keys were specified."
+  array_is_nonempty _hash || fail "Cannot seed template '${_template}';"\
+    " No replacement keys were specified."
 
-  array_is_even _hash ||
-    fail "Every replacement key must have a replacement value."
+  array_is_even _hash || fail "Cannot seed template;"\
+    " Every replacement key must have a replacement value."
 
   for (( index=0 ; index < ${#_hash[@]} ; index++ ))
   do
@@ -290,32 +248,31 @@ seed_template()
   done
 
   sed "${_strings[@]}" ${_template} > ${temporary} ||
-    error "There was an error (?) seeding the template '${_template}'." \
-    "Most often this is due to filesystem permissions / disk full."
+    error "There was an error (?) seeding the template '${_template}';" \
+    " Most often this is due to filesystem permissions / disk full."
 
-  if file_exists "${temporary}"
-  then
-    move_file "${temporary}" "${_template}"
-  else
-    fail "Something went horribly wrong; the template intermediate file "\
-      "'${temporary}' does not exist."
-  fi
+  file_exists "${temporary}" || fail "Something went very wrong;"\
+    " the template intermediate file '${temporary}' does not exist?! "
+
+  move_file "${temporary}" "${_template}"
 }
 
 update_seed_template()
 {
   local _template="${1:-}" _target="${2:-}"
-  shift 2
+  shift || fail "Cannot update seed template;"\
+    " Template name was not given as the first parameter."
+  shift || fail "Cannot update seed template;"\
+    " Template target was not given as the second parameter."
+
   local  _incoming="${1:-${_target}.incoming}"
   shift || true
   local _hash=("$@") _strings=() _variables="${_target}.var.$$"
 
-  if template_exists "${_template}"
-  then
-    _template="${template_path}"
-  else
-    fail "No template was found matching '${_name}'."
-  fi
+  template_exists "${_template}" || fail "Cannot update seed template;"\
+    " No template was found matching '${_name}'."
+
+  _template="${template_path}"
 
   for (( index=0 ; index < ${#_hash[@]} ; index++ ))
   do
@@ -333,3 +290,4 @@ update_seed_template()
 
   rm "${_variables}"
 }
+
