Updated deploy.

diff --git a/extensions/bdsm/deploy b/extensions/bdsm/deploy
--- a/extensions/bdsm/deploy
+++ b/extensions/bdsm/deploy
@@ -46,9 +46,12 @@ update_repository() {
       git checkout -b $branch --track $remote/$branch 2>/dev/null
     elif [[ -z "$(git branch | awk "/\* $branch/")" ]] ; then
       git checkout $branch 2>/dev/null
+      if [[ $? -gt 0 ]] ; then
+        $scripts_path/log "error" "Branch $remote/$branch not found. Skipping remainder of update."
+        return 1
+      fi
     else
-      $scripts_path/log "error" "Branch $remote/$branch not found."
-      return 1
+      $scripts_path/log "info" "Already on $branch."
     fi
     git pull
 
