flexible error handling in vcs

diff --git a/core/ext/modules/shell/vcs/dsl b/core/ext/modules/shell/vcs/dsl
--- a/core/ext/modules/shell/vcs/dsl
+++ b/core/ext/modules/shell/vcs/dsl
@@ -16,11 +16,18 @@ fetch_uri_parse_args()
       case "${_token}" in
         (*${_allowed_arg})
           eval "${_allowed_arg}=\"${1}\""
-          shift || error "${_allowed_arg} must be specified after '${_token}'."
+          shift || fail "${_allowed_arg} must be specified after '${_token}'."
           continue 2
           ;;
       esac
     done
+    case "${_token}" in
+      (--on-fail)
+        fetch_error_handler=$1
+        shift || fail "fetch error handler function must be specified after '--on-fail'."
+        continue
+        ;;
+    esac
     _args+=("${_token}")
   done
 }
@@ -33,6 +40,7 @@ fetch_uri_parse_args()
 fetch_uri()
 {
   trace_filter vcs
+  fetch_error_initialize "$@"
 
   local _uri="${1:-}" _target="${2:-}" _args=()
   shift || fail "uri must be specified as the first parameter."
@@ -50,14 +58,9 @@ fetch_uri()
       "${scm_type}_get" "${_args[@]}"
       ;;
     (*)
-      error "Unknown SCM("${scm_type}") for url '${_uri}'."
+      fetch_error unknown_scm
       ;;
   esac
-}
-
-fetch()
-{
-  fetch_uri "$@"
 }
 
 fetch_update()
@@ -75,4 +78,19 @@ fetch_update()
     fi
   fi
   return 1
+}
+
+cli_fetch()
+{
+  local _uri="${1:-}" _target="${2:-}" _args=()
+  shift || error "uri must be specified as the first parameter."
+  shift || error "target path must be specified as the second parameter."
+  fetch_uri "${_uri}" "${_target}" --on-fail error "$@"
+}
+
+cli_fetch_update()
+{
+  local _target="${1:-}"
+  shift || error "target path must be specified as the second parameter."
+  fetch_update "${_target}" --on-fail error "$@"
 }
