Refactored dev module.

diff --git a/core/cli/modules/shell/dev/dsl b/core/cli/modules/shell/dev/dsl
--- a/core/cli/modules/shell/dev/dsl
+++ b/core/cli/modules/shell/dev/dsl
@@ -85,95 +85,83 @@ sm_development_update()
 extension_package()
 {
   local _name="${1:-}" _path _version file
+  shift || fail "Cannot package an extension; no extension name was given."
 
-  if [[ -n "${_name}" ]]
-  then
-    _path="${extensions_development_path:-"$extensions_src_path"}"
+  _path="${extensions_development_path:-"$extensions_src_path"}"
 
-    ensure_paths_exist "${_path}"
-    enter "${_path}"
+  ensure_paths_exist "${_path}"
+  enter "${_path}"
 
-    if extension_is_valid "${_path}/${_name}"
+  extension_is_valid "${_path}/${_name}" ||
+    error "Cannot package extension '${_name}'; the extension is not valid."
+
+  _version="$(cat "${_name}/VERSION")"
+  log "Packaging extension ${_name}"
+  log "${_name}-${_version}:"
+
+  for archiver in "gzip" "bzip2 -z" "xz -z"
+  do
+    if command_exists ${archiver// *}
     then
-      _version="$(cat "${_name}/VERSION")"
-      log "Packaging extension ${_name}"
-      log "${_name}-${_version}:"
-
-      for archiver in "gzip" "bzip2 -z" "xz -z"
-      do
-        if command_exists ${archiver// *}
-        then
-          if tar cf "${_name}-${_version}.tar" "${_name}/"
-          then
-            # TODO: parallelize this.
-            ${archiver} -f -9 "${_name}-${_version}.tar"
-          else
-            error "There was an error during packaging ($?) while trying to create a tar of the '${_name}' directory."
-          fi
-        fi
-
-        ensure_paths_exist "${_path}/pkg"
-
-        for file in "${_name}-${_version}".tar.*
-        do
-          log "  - ${file}"
-          write "$( file_md5 "${file}" )" to "${file}.md5"
-          log "  - ${file}.md5"
-          move_files --force "${file}" "${file}.md5" \
-            to "${_path}/pkg" from "${_path}"
-        done
-      done
-      log "Packaging complete! (Packages are located in '${_path}/pkg'.)"
-    else
-      error "Cannot package extension '${_name}'; the extension is not valid."
+      if tar cf "${_name}-${_version}.tar" "${_name}/"
+      then
+        # TODO: parallelize this.
+        ${archiver} -f -9 "${_name}-${_version}.tar"
+      else
+        error "There was an error during packaging ($?) while trying to create a tar of the '${_name}' directory."
+      fi
     fi
-  else
-    fail "Cannot package an extension; no extension name was given."
-  fi
+
+    ensure_paths_exist "${_path}/pkg"
+
+    for file in "${_name}-${_version}".tar.*
+    do
+      log "  - ${file}"
+      write "$( file_md5 "${file}" )" to "${file}.md5"
+      log "  - ${file}.md5"
+      move_files --force "${file}" "${file}.md5" \
+        to "${_path}/pkg" from "${_path}"
+    done
+  done
+  log "Packaging complete! (Packages are located in '${_path}/pkg'.)"
 }
 
 extension_publish()
 {
   local _name="${1:-}" _path _version
+  shift || fail "Cannot publish an extension; no extension name was given."
 
   NIY "Extension publishing locally, to extensions. beginrescueend.com has not yet been implemented."
 
-  if [[ -n "${_name}" ]]
-  then
-    _path="${extensions_development_path:-"$extensions_src_path"}"
+  _path="${extensions_development_path:-"$extensions_src_path"}"
 
-    enter "${_path}"
+  enter "${_path}"
 
-    if extension_is_valid "${_path}/${_name}"
+  extension_is_valid "${_path}/${_name}" ||
+    error "Cannot package extension '${_name}'; the extension is not valid."
+
+  _version="$(cat "${_name}/VERSION")"
+  log "Packaging extension ${_name}"
+  log "${_name}-${_version}:"
+
+  for formats in ".tar.gz" ".tar.bz2" ".tar.xz"
+  do
+    if path_exists "${_path}/pkg/"
     then
-      _version="$(cat "${_name}/VERSION")"
-      log "Packaging extension ${_name}"
-      log "${_name}-${_version}:"
+      log "publishing ${_name}-${_version}"
 
-      for formats in ".tar.gz" ".tar.bz2" ".tar.xz"
+      for file in "${_pth}/${_name}-${_version}".tar.{gz,xz,bz2}
       do
-        if path_exists "${_path}/pkg/"
-        then
-          log "publishing ${_name}-${_version}"
-
-          for file in "${_pth}/${_name}-${_version}".tar.{gz,xz,bz2}
-          do
-            log "  - ${file}"
-            log "  - ${file}.md5"
-            NIY "publishing"
-          done
-        else
-          error "The local package path '${_path}' does not exist; did you run"\
-            "'extension package ${_name}' before 'extension publish ${_name}'?"
-        fi
+        log "  - ${file}"
+        log "  - ${file}.md5"
+        NIY "publishing"
       done
-      log "Packaging complete. (Packages are located in '${_path}/pkg' )"
     else
-      error "Cannot package extension '${_name}'; the extension is not valid."
+      error "The local package path '${_path}' does not exist; did you run"\
+        "'extension package ${_name}' before 'extension publish ${_name}'?"
     fi
-  else
-    fail "Cannot publish an extension; no extension name was given."
-  fi
+  done
+  log "Packaging complete. (Packages are located in '${_path}/pkg' )"
 }
 
 extension_module_add()
@@ -181,8 +169,6 @@ extension_module_add()
   local _extension="${1}" _module="${2}" _path
   _path="${3:-"${extensions_development_path}/${_extension}"}"
 
-  if ! file_contains "${_path}/modules/shell/modules" "${_module}"
-  then
+  file_contains "${_path}/modules/shell/modules" "${_module}" ||
     write "\n${_module}" append to "${_path}/modules/shell/modules"
-  fi
 }
