docgen now works.

diff --git a/extensions/mod/modules/bash/dsl b/extensions/mod/modules/bash/dsl
--- a/extensions/mod/modules/bash/dsl
+++ b/extensions/mod/modules/bash/dsl
@@ -40,16 +40,26 @@ modules_list()
   done
 }
 
+module_docs()
+{
+  local _function _dsl _module="${1:-}"
+  # [[ -n "${_module}" ]] || fail "... module not given"
+  local _path="${modules_path}/bash/${_module}"
+  #_dsl=($(find "${_path}" -mindepth 1 -maxdepth 1 -name dsl -type f -print0 | xargs -0 grep '^[a-z_]*()$'))
+
+  awk '/^#/{print }' "${_path}/dsl" | sed -e "1d" -e "s/^# //g" -e "s/^#\s*//"
+}
+
 modules_docgen()
 {
   local _module _modules _function _dsl
 
   _modules=($(modules_installed))
   for _module in "${_modules[@]}" ; do
-    printf "\n${_module}\n\n"
-  awk <<AWK "${_module}"
-  skip comments...
-AWK
+    ensure_paths_exist "/tmp/docs/modules/${_module}"
+    module_docs "${_module}" > "/tmp/docs/modules/${_module}/${_module}.md"
   done
+
+  printf "%s\n" "Modules documentation has been generated as Markdown files in /tmp/docs/modules/"
 }
 
