Split files into api/internal.

diff --git a/core/api/shell/extensions/manipulation/functions b/core/api/shell/extensions/manipulation/functions
--- a/core/api/shell/extensions/manipulation/functions
+++ b/core/api/shell/extensions/manipulation/functions
@@ -36,7 +36,7 @@ extension_version()
     " No extension was given."
   true ${extension_path:="${extensions_path}/${_extension}"}
 
-  if file_exists "${extension_path}/VERSION"
+  if files exist "${extension_path}/VERSION"
   then
     read -r extension_version < "${extension_path}/VERSION"
   else
@@ -96,8 +96,7 @@ extension_license()
 {
   local _extension="${1:-${extension}}"
 
-  variable_is_nonempty _extension ||
-    fail "Cannot display extension license;"\
+  [[ -n "${_extension}" ]] || fail "Cannot display extension license;"\
     " Extension name was not given."
 
   cat -v "${extensions_path}/${_extension}/LICENSE"
@@ -218,7 +217,7 @@ extension_install()
     from "${extensions_src_path}/${_src}" \
     to "${sm_path}/exts/${_extension}"
 
-  write "${extension_uri}" to "${sm_path}/exts/${_extension}/.uri"
+  files write string "${extension_uri}" to "${sm_path}/exts/${_extension}/.uri"
 
   #
   # TODO: Process extension dependencies...
diff --git a/core/api/shell/templates/functions b/core/api/shell/templates/functions
--- a/core/api/shell/templates/functions
+++ b/core/api/shell/templates/functions
@@ -178,16 +178,13 @@ install_template()
       fail "Cannot install the template '${_template}' to ${_target}/${_name},"\
         " as it is a directory."
     fi
-
-    copy_file "${_template}" to "${_target}/${_name}"
-
-    variable_is_empty _mode  || chmod "${_mode}" "${_target}/${_name}"
-    variable_is_empty _owner || chown "${_owner}" "${_target}/${_name}"
+    files copy \
+      from "${_template}" to "${_target}/${_name}" \
+      mode "${_mode}" owner "${_owner}"
   else
-    copy_file --force "${_template}" to "${_target}"
-
-    variable_is_empty _mode  || chmod_files "${_mode}" "${_target}"
-    variable_is_empty _owner || chown_files "${_owner}" "${_target}"
+    files copy force \
+      from "${_template}" to "${_target}"
+      mode "${_mode}" owner "${_owner}"
   fi
 }
 
@@ -244,7 +241,7 @@ seed_template()
 
   local _hash=("$@") _strings=() temporary=${_template}.${timestamp}.$$
 
-  file_exists "${_template}" || fail "Cannot seed template;"\
+  files exist "${_template}" || fail "Cannot seed template;"\
     " template file '${_template}' does not exist."
 
   [[ -n "${_hash}" ]] || fail "Cannot seed template '${_template}';"\
@@ -262,10 +259,10 @@ seed_template()
     error "There was an error (?) seeding the template '${_template}';" \
     " Most often this is due to filesystem permissions / disk full."
 
-  file_exists "${temporary}" || fail "Something went very wrong;"\
+  files exist "${temporary}" || fail "Something went very wrong;"\
     " the template intermediate file '${temporary}' does not exist?! "
 
-  move_file "${temporary}" "${_template}"
+  files move from "${temporary}" to "${_template}"
 }
 
 update_seed_template()
diff --git a/core/internal/shell/templates/functions b/core/internal/shell/templates/functions
--- a/core/internal/shell/templates/functions
+++ b/core/internal/shell/templates/functions
@@ -179,15 +179,12 @@ install_template()
         " as it is a directory."
     fi
 
-    copy_file "${_template}" to "${_target}/${_name}"
-
-    variable_is_empty _mode  || chmod "${_mode}" "${_target}/${_name}"
-    variable_is_empty _owner || chown "${_owner}" "${_target}/${_name}"
+    files copy from "${_template}" to "${_target}/${_name}" \
+      mode "${_mode}" owner "${_owner}"
   else
-    copy_file --force "${_template}" to "${_target}"
-
-    variable_is_empty _mode  || chmod_files "${_mode}" "${_target}"
-    variable_is_empty _owner || chown_files "${_owner}" "${_target}"
+    files copy force \
+      from "${_template}" to "${_target}" \
+      mode "${_mode}" owner "${_owner}"
   fi
 }
 
@@ -244,7 +241,7 @@ seed_template()
 
   local _hash=("$@") _strings=() temporary=${_template}.${timestamp}.$$
 
-  file_exists "${_template}" || fail "Cannot seed template;"\
+  files exist "${_template}" || fail "Cannot seed template;"\
     " template file '${_template}' does not exist."
 
   [[ -n "${_hash}" ]] || fail "Cannot seed template '${_template}';"\
@@ -262,7 +259,7 @@ seed_template()
     error "There was an error (?) seeding the template '${_template}';" \
     " Most often this is due to filesystem permissions / disk full."
 
-  file_exists "${temporary}" || fail "Something went very wrong;"\
+  files exist "${temporary}" || fail "Something went very wrong;"\
     " the template intermediate file '${temporary}' does not exist?! "
 
   move_file "${temporary}" "${_template}"
