Initial bash help module documentation.

diff --git a/modules/bash/help/dsl b/modules/bash/help/dsl
--- a/modules/bash/help/dsl
+++ b/modules/bash/help/dsl
@@ -1,5 +1,35 @@
 #!/usr/bin/env bash
 
+#
+# ## show_help
+#
+# Display help for the current extension based on settings declared in the help
+# action.
+#
+# ### Input Parameterss
+#
+# First parameter is the help section to display, default is all sections 'usage'.
+#
+# ### Stream Outputs
+#
+# Prints out formatted help sections to the calling environments STDOUT stream.
+#
+# ### Environmental effects
+#
+# None.
+#
+# ### Return Codes
+#
+# 0 for success.
+#
+# ### Failure Scenarios
+#
+# No failure scenarios currently.
+#
+# ### Usage Examples
+#
+#     user$ show_help usage
+#
 show_help()
 {
   local _help_command="usage" _token
@@ -19,16 +49,210 @@ show_help()
   "${_help_command}"
 }
 
-description() { help_description="$*" ; }
+#
+# ## description
+#
+# Set the string that will be printed when the actions help section is output.
+#
+# ### Input Parameterss
+#
+# First parameter is a string containing a description of the extension.
+#
+# ### Stream Outputs
+#
+# None.
+#
+# ### Environmental effects
+#
+# None.
+#
+# ### Return Codes
+#
+# 0 for success.
+#
+# ### Failure Scenarios
+#
+# Fails if no description is given.
+#
+# ### Usage Examples
+#
+#     user$ description "This extension handles X Y and Z."
+#
+description()
+{
+  [[ -n "$*" ]] || fail "No help description was given."
 
-actions(){ help_actions="$*" ; }
+  help_description="$*"
+}
 
-notes() { help_notes="$*" ; }
+#
+# ## actions
+#
+# Set the string that will be printed when the actions help section is output.
+#
+# ### Input Parameterss
+#
+# First parameter is a string of the action descriptions.
+#
+# ### Stream Outputs
+#
+# None.
+#
+# ### Environmental effects
+#
+# None.
+#
+# ### Return Codes
+#
+# 0 for success.
+#
+# ### Failure Scenarios
+#
+# Fails if no actions are given.
+#
+# ### Usage Examples
+#
+#     user$ actions "install  - Installs the extension..."
+#
+actions()
+{
+  [[ -n "$*" ]] || fail "No help actions were given."
+  help_actions="$*"
+}
 
-dependencies() { help_dependencies="$*" ; }
+#
+# ## notes
+#
+# Define the notes help section content.
+#
+# ### Input Parameterss
+#
+# First parameter is a string containing any notes for the notes section of the
+# current extension's help output.
+#
+# ### Stream Outputs
+#
+# None.
+#
+# ### Environmental effects
+#
+# None.
+#
+# ### Return Codes
+#
+# 0 for success.
+#
+# ### Failure Scenarios
+#
+# No failure scenarios currently.
+#
+# ### Usage Examples
+#
+#     user$ notes "Help for this extension can be found in #beginrescueend on irc.freenode.net"
+#
+notes()
+{
+  help_notes="$*"
+}
 
-resources() { help_resources="$*" ; }
+#
+# ## dependencies
+#
+# Specify content for the dependencies section of the help command.
+#
+# ### Input Parameterss
+#
+# First parameter is a string containing any dependencies for the dependencies
+# section of the current extension's help output.
+#
+# ### Stream Outputs
+#
+# None.
+#
+# ### Environmental effects
+#
+# None.
+#
+# ### Return Codes
+#
+# 0 for success
+#
+# ### Failure Scenarios
+#
+# No failure scenarios currently.
+#
+# ### Usage Examples
+#
+#     user$ dependencies " * pcre"
+#
+dependencies()
+{
+  help_dependencies="$*"
+}
 
+#
+# ## resources
+#
+# Specify content for the resources section of the help command.
+#
+# ### Input Parameterss
+#
+# First parameter is a string containing any resources for the resources
+# section of the current extension's help output.
+#
+# ### Stream Outputs
+#
+# None.
+#
+# ### Environmental effects
+#
+# None.
+#
+# ### Return Codes
+#
+# 0 for success
+#
+# ### Failure Scenarios
+#
+# No failure scenarios currently.
+#
+# ### Usage Examples
+#
+#     user$ resources "website: ..."
+#
+resources() {
+  help_resources="$*"
+}
+
+#
+# ## usage
+#
+# Display the usage help output of the command. This displays all help sections.
+#
+# ### Input Parameterss
+#
+# None.
+#
+# ### Stream Outputs
+#
+# Prints all help sections to the STDOUT of the calling environment.
+#
+# ### Environmental effects
+#
+# None.
+#
+# ### Return Codes
+#
+# 0 for success
+#
+# ### Failure Scenarios
+#
+# No failure scenarios currently.
+#
+# ### Usage Examples
+#
+#     user$ usage
+#
 usage()
 {
   log "\nUsage\n\n    bdsm ${extension} <action> <<arguments>>"
