Well that was dumb.

diff --git a/extensions/core/modules/bash/dsl b/extensions/core/modules/bash/dsl
--- a/extensions/core/modules/bash/dsl
+++ b/extensions/core/modules/bash/dsl
@@ -365,6 +365,30 @@ Code
 
 setup_bdsmrc()
 {
+  unset bdsm_path
+
+  for file in /etc/bdsmrc "$HOME/.bdsmrc"
+  do
+    if [[ -s "${file}" ]]
+    then
+      source "${file}" || true # Continue if it fails.
+    fi
+  done
+
+  # The default prefix is /usr/local,
+  # this should be set to where BDSM is installed to in /etc/bdsmrc
+  prefix_path="${prefix_path:-/usr/local}"
+
+  if [[ -z "${bdsm_path}" ]]
+  then
+    if [[ "$prefix_path" = "$HOME" ]]
+    then
+      bdsm_path="${prefix_path}/.bdsm"
+    else
+      bdsm_path="${prefix_path}/bdsm"
+    fi
+  fi
+
   if user_is_root
   then
     ensure_files_exist "/etc/bdsmrc"
