Cleaned up variable module code.

diff --git a/modules/bash/variables/dsl b/modules/bash/variables/dsl
--- a/modules/bash/variables/dsl
+++ b/modules/bash/variables/dsl
@@ -38,10 +38,12 @@ first()
 {
   local _array=("$@")
 
-  (( ${#_array[@]} > 0 )) ||
+  if (( ${#_array[@]} > 0 ))
+  then
+    printf "%s" "${_array[0]}"
+  else
     fail "No parameters given, cannot return the first one."
-
-  printf "%s" "${_array[0]}"
+  fi
 }
 
 #
@@ -82,10 +84,12 @@ last()
 {
   local _array=("$@")
 
-  (( ${#_array[@]} > 0 )) ||
+  if (( ${#_array[@]} > 0 ))
+  then
+    printf "%s" "${_array[$((${#_array[@]} - 1))]}"
+  else
     fail "No parameters given, cannot return the last one."
-
-  printf "%s" "${_array[$((${#_array[@]} - 1))]}"
+  fi
 }
 
 #
@@ -129,22 +133,27 @@ match()
 {
   local _value="$1"
 
-  [[ -n "${_value}" ]] ||
+  if [[ -n "${_value}" ]]
+  then
+    shift
+    local _regex="$1"
+    if [[ -n "${_value}" ]]
+    then
+      shopt -s extglob
+      case "${_value}" in
+        (${_regex})
+          return 0
+          ;;
+        (*)
+          return 1
+          ;;
+      esac
+    else
+      fail "A regex must be specified in order to match ${_value} against it."
+    fi
+  else
     fail "A value and regex must be specified in order to match."
-
-  shift
-
-  local _regex="$1"
-
-  [[ -n "${_value}" ]] ||
-    fail "A regex must be specified in order to match ${_value} against it."
-
-  shopt -s extglob
-
-  case "${_value}" in
-    (${_regex}) return 0 ;;
-    (*)         return 1 ;;
-  esac
+  fi
 }
 
 #
@@ -197,14 +206,20 @@ variables_must_be_nonempty()
 {
   local _variable _variables=("$@")
 
-  (( ${#_variables[@]} > 0 )) ||
+  if (( ${#_variables[@]} > 0 ))
+  then
+    for _variable in "${_variables}"
+    do
+      if eval "[[ -n \"\${${_variable}}\" ]]"
+      then
+        continue
+      else
+        fail "Required variable '$_variable' is not set."
+      fi
+    done
+  else
     fail "Cannot ensure variables are nonempty as no variables were given."
-
-  for _variable in "${_variables}"
-  do
-    eval "[[ -n \"\${${_variable}}\" ]]" ||
-      fail "Required variable '$_variable' is not set."
-  done
+  fi
 }
 
 #
@@ -247,10 +262,71 @@ variable_is_nonempty()
 {
   local _variable="${1:-}"
 
-  [[ -n "${_variable}" ]] ||
+  if [[ -n "${_variable}" ]]
+  then
+    if eval "[[ -n \"\${${_variable}:-}\" ]]"
+    then
+      return 0
+    else
+      return 1
+    fi
+  else
     fail "Cannot check if variable is nonempty, no variable was given."
+  fi
 
-  eval "[[ -n \"\${${_variable}:-}\" ]]"
+}
+
+#
+# ## variable_is_empty()
+#
+# Test to see if a variable is empty.
+#
+# ### Input Parameters
+#
+# First parameter is a string containing a variable name.
+#
+# ### Stream Outputs
+#
+# None.
+#
+# ### Environmental effects
+#
+# None.
+#
+# ### Return Codes
+#
+# 0 for success.
+#
+# ### Failure Scenarios
+#
+# Fails if no variable name was given as the first argument.
+#
+# ### Usage Examples
+#
+#     user$ variable_is_empty asdf
+#     user$ echo $?
+#     1
+#
+#     user$ asdf="w00t! "
+#     user$ variable_is_empty asdf
+#     user$ echo $?
+#     0
+#
+variable_is_empty()
+{
+  local _variable="${1:-}"
+
+  if [[ -n "${_variable}" ]]
+  then
+    if eval "[[ -z \"\${${_variable}:-}\" ]]"
+    then
+      return 0
+    else
+      return 1
+    fi
+  else
+    fail "Cannot check if variable is empty as no variable was given."
+  fi
 }
 
 #
@@ -294,16 +370,19 @@ variables_are_nonempty()
 {
   local _variable _variables=("$@")
 
-  (( "${#_variables[@]}" > 0 )) ||
+  if (( "${#_variables[@]}" > 0 ))
+  then
+    for _variable in "${_variables}"
+    do
+      if eval "[[ -z \"\${${_variable}:-}\" ]]"
+      then
+        return 1
+      fi
+    done
+    return 0
+  else
     fail "Cannot check if variables are nonempty as no variables were given."
+  fi
 
-  for _variable in "${_variables}"
-  do
-    if eval "[[ -z \"\${${_variable}:-}\" ]]"
-    then
-      return 1
-    fi
-  done
-  return 0
 }
 
