Getting closer to 0.2.0

diff --git a/extensions/extension/bin/create b/extensions/extension/bin/create
--- a/extensions/extension/bin/create
+++ b/extensions/extension/bin/create
@@ -1,28 +1,24 @@
 #!/usr/bin/env bash
 
-if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi
+[[ -n "$extensions" ]] || fail "At least one extension name must be specified."
 
-result=0 ; extensions="$1" ; shift
-releases_url="${releases_url:-$($scripts_path/db "$config_path/bdsm" "releases_url")}"
-extension_url="${extension_url:-$($scripts_path/db "$config_path/bdsm" "extension_url")}"
-if [[ -z "$extensions" ]] ; then
-  "$scripts_path"/log "error" "A extension must be specified." ; exit 1
-fi
-# TODO: Should we allow user installs?...
-if [[ "root" != "user" ]] ; then
-  "$scripts_path"/log "error" "extensions must be installed as root." ; exit 1
-fi
+for extension in ${extensions//,/ } ; do
 
-if [[ -z "$extension" ]] ; then
-  $scripts_path/log "error" "A extension must be specified to edit." ; exit 1
-else
   if [[ ! -d "$extensions_path/extension" ]] ; then
-    rsync -avgz "$extensions_path/extension/templates/" "$extensions_path/$extension/"
-    cd "$extensions_path/$extension/"
-    ${EDITOR:-vi} .
-  else
-    "$scripts_path"/log "error" "extension $extension already exists in $extensions_path/$extension!." ; exit 1
-  fi
-fi
 
-exit $?
+    if [[ -d "${extensions_path}/extension/templates/${language}" ]] ; then
+      cp -Rf \
+        "$extensions_path/extension/templates/${language}" \
+        "$extensions_path/$extension/"
+
+      succeed "Extension created from template at ${extensions_path}/${extension}/"
+    else
+      fail "Extension template files for are missing from $extensions_path/extension/templates/${language}."
+    fi
+  else
+    fail "Extension '$extension' already exists at ${extensions_path}/${extension}."
+  fi
+
+done
+
+succeed "Removed extensions ${extensions}"
