cleaning in extensions

diff --git a/extensions/builtin/bdsm/modules/shell/dev/dsl b/extensions/builtin/bdsm/modules/shell/dev/dsl
--- a/extensions/builtin/bdsm/modules/shell/dev/dsl
+++ b/extensions/builtin/bdsm/modules/shell/dev/dsl
@@ -80,3 +80,108 @@ bdsm_development_update()
 {
   NIY
 }
+
+extension_package()
+{
+  local _name="${1:-}" _path _version file
+
+  if [[ -n "${_name}" ]]
+  then
+    _path="${extensions_development_path:-"$extensions_src_path"}"
+
+    ensure_paths_exist "${_path}"
+    enter "${_path}"
+
+    if extension_is_valid "${_path}/${_name}"
+    then
+      _version="$(cat "${_name}/VERSION")"
+      log "Packaging extension ${_name}"
+      log "${_name}-${_version}:"
+
+      for archiver in "gzip" "bzip2 -z" "xz -z"
+      do
+        if command_exists ${archiver// *}
+        then
+          if tar cf "${_name}-${_version}.tar" "${_name}/"
+          then
+            # TODO: parallelize this.
+            ${archiver} -f -9 "${_name}-${_version}.tar"
+          else
+            error "There was an error ($?) while trying to create a tar of the '${_name}' directory while packaging."
+          fi
+        fi
+
+        ensure_paths_exist "${_path}/pkg"
+
+        for file in "${_name}-${_version}".tar.*
+        do
+          log "  - ${file}"
+          write "$( file_md5 "${file}" )" to "${file}.md5"
+          log "  - ${file}.md5"
+          move_files --force "${file}" "${file}.md5" \
+            to "${_path}/pkg" from "${_path}"
+        done
+      done
+      log "Packaging complete (packages are located in '${_path}/pkg' )"
+    else
+      error "Cannot package extension '${_name}' as the extension is not valid."
+    fi
+  else
+    fail "Cannot package an extension as no extension name was given."
+  fi
+}
+
+extension_publish()
+{
+  local _name="${1:-}" _path _version
+
+  NIY "Extension publishing to extensions.beginrescueend.com has not yet been implemented."
+
+  if [[ -n "${_name}" ]]
+  then
+    _path="${extensions_development_path:-"$extensions_src_path"}"
+
+    enter "${_path}"
+
+    if extension_is_valid "${_path}/${_name}"
+    then
+      _version="$(cat "${_name}/VERSION")"
+      log "Packaging extension ${_name}"
+      log "${_name}-${_version}:"
+
+      for formats in ".tar.gz" ".tar.bz2" ".tar.xz"
+      do
+        if path_exists "${_path}/pkg/"
+        then
+          log "publishing ${_name}-${_version}"
+
+          for file in "${_pth}/${_name}-${_version}".tar.{gz,xz,bz2}
+          do
+            log "  - ${file}"
+            log "  - ${file}.md5"
+            NIY "publishing"
+          done
+        else
+          error "The local package path '${_path}' does not exist, did you run"\
+            "'extension package ${_name}' before 'extension publish ${_name}'?"
+        fi
+      done
+      log "Packaging complete (packages are located in '${_path}/pkg' )"
+    else
+      error "Cannot package extension '${_name}' as the extension is not valid."
+    fi
+  else
+    fail "Cannot publish an extension as no extension name was given."
+  fi
+}
+
+extension_module_add()
+{
+  local _extension="${1}" _module="${2}" _path
+  _path="${3:-"${extensions_development_path}/${_extension}"}"
+
+  if ! file_contains "${_path}/modules/shell/modules" "${_module}"
+  then
+    write "\n${_module}" append to "${_path}/modules/shell/modules"
+  fi
+}
