extract single module loading to separate function

diff --git a/extensions/builtin/core/modules/shell/modules/dsl b/extensions/builtin/core/modules/shell/modules/dsl
--- a/extensions/builtin/core/modules/shell/modules/dsl
+++ b/extensions/builtin/core/modules/shell/modules/dsl
@@ -79,6 +79,33 @@ in_search_paths()
   return 1
 }
 
+module()
+{
+  local _module=$1 _file
+
+  if module_is_loaded "${_module}"
+  then
+    return 0
+  else
+    if in_search_paths detect_module "${_module}"
+    then
+      log_search module "$module_name" "${module_path##${bdsm_path}\/extensions\/}"
+      modules+=("${module_name}")
+    else
+      debug "Could not find module path for ${_module}"
+      return 1
+    fi
+    for _file in dsl cli initialize
+    do
+      if [[ -s "${module_path}/${_file}" ]]
+      then
+        source "${module_path}/${_file}"
+      fi
+    done
+    return 0
+  fi
+}
+
 #
 # ## modules()
 #
@@ -120,24 +147,9 @@ modules()
   then
     for _module in "${_modules[@]}"
     do
-      if module_is_loaded "${_module}"
+      if ! module "${_module}"
       then
-        continue # The module has already been loaded, continue to the next one.
-      else
-        if in_search_paths detect_module "${_module}"
-        then
-          log_search module "$module_name" "${module_path##${bdsm_path}\/extensions\/}"
-          modules+=("${module_name}")
-        else
-          fail "Could not find module path for ${_module}"
-        fi
-        for _file in dsl cli initialize
-        do
-          if [[ -s "${module_path}/${_file}" ]]
-          then
-            source "${module_path}/${_file}"
-          fi
-        done
+        fail "Could not find module path for ${_module}"
       fi
     done
   else
