extension loads using module, cleaning

diff --git a/extensions/builtin/core/modules/shell/modules/dsl b/extensions/builtin/core/modules/shell/modules/dsl
--- a/extensions/builtin/core/modules/shell/modules/dsl
+++ b/extensions/builtin/core/modules/shell/modules/dsl
@@ -81,29 +81,40 @@ in_search_paths()
 
 module()
 {
-  local _module=$1 _file
+  local _module=$1 _skip_path_detection=$2 _file
 
   if module_is_loaded "${_module}"
   then
     return 0
+  fi
+  if [[ "${_skip_path_detection}" == "skip_path_detection" ]]
+  then
+    if [[ -d "${module_path}" ]] && [[ -f "${module_path}/dsl" ]]
+    then
+      log_search fast_mod "$module_name" "${module_path##${bdsm_path}\/extensions\/}"
+      modules+=("${module_name}")
+    else
+      log_search fast_mod "${_module}" "Not found !!! ${module_path}/dsl"
+      return 1
+    fi
   else
     if in_search_paths detect_module "${_module}"
     then
       log_search module "$module_name" "${module_path##${bdsm_path}\/extensions\/}"
       modules+=("${module_name}")
     else
-      debug "Could not find module path for ${_module}"
+      log_search module "${_module}" "Not found !!!"
       return 1
     fi
-    for _file in dsl cli initialize
-    do
-      if [[ -s "${module_path}/${_file}" ]]
-      then
-        source "${module_path}/${_file}"
-      fi
-    done
-    return 0
   fi
+  for _file in dsl cli initialize
+  do
+    if [[ -s "${module_path}/${_file}" ]]
+    then
+      source "${module_path}/${_file}"
+    fi
+  done
+  return 0
 }
 
 # load module or show error msg if module not available
@@ -112,6 +123,18 @@ module_or_error()
   if ! module "$1"
   then
     error "$2"
+  fi
+}
+
+# load a core module or fail
+core_module()
+{
+  module=$1
+  module_name="core/$module"
+  module_path="${modules_path}/shell/$module"
+  if ! module "$module_name" skip_path_detection
+  then
+    fail "core module '${module_name}' is missing!!!"
   fi
 }
 
