More work on APIs, specifically service and variables.

diff --git a/core/internal/shell/service/functions b/core/internal/shell/service/functions
--- a/core/internal/shell/service/functions
+++ b/core/internal/shell/service/functions
@@ -1,17 +1,12 @@
 #!/bin/sh
 
-#
-# SM Framework Extended Module ~ Service Module
-#
-
-ext_service_initialize()
+__sm.service.initialize()
 {
-  variable_is_nonempty init_scripts_path || init_scripts_path="$(init_scripts_path)"
-  variable_is_nonempty confd_path        || confd_path="$(confd_path)"
+   [[ -n "${init_scripts_path}" ]] || init_scripts_path="$(init_scripts_path)"
+   [[ -n "${confd_path}" ]]        ||confd_path="$(confd_path)"
 
   # TODO: Account for user service installs...
   # TODO: Merge service_paths and service_root_paths...
-
   # TODO: determine root_install vs user_install...
   if user is root
   then
@@ -22,7 +17,7 @@ ext_service_initialize()
     var_path="${packages_path}/active/var"
   fi
 
-  : \
+  true \
     "${service:="${extension:-${package_name}}"}" \
     "${service_version:="${package_version}"}" \
     "${prefix_path:="${sm_path}/active"}" \
@@ -81,7 +76,7 @@ ext_service_initialize()
     fi
   done
 
-  if variable_is_empty service_binary
+  if [[ -z "${service_binary}" ]]
   then
     if __sm.command.exists ${service}
     then
@@ -111,47 +106,9 @@ ext_service_initialize()
   service_initialized=1
 }
 
-services_avilable()
+__sm.service.setup()
 {
-  __sm.extensions.installed module "api/service" "$@"
-}
-
-services_list()
-{
-  local _action="${1:-}" _args
-
-  shift || true
-
-  case "${_action}" in
-    (active)
-      services_active "$@"
-      ;;
-
-    (available)
-      services_available "$@"
-      ;;
-
-    (installed|*)
-      services_installed "$@"
-      ;;
-  esac
-}
-
-services_installed()
-{
-  # Notify that the services_installed() function has not yet been implemented.
-  NIY "Installed services has not yet been implemented."
-}
-
-services_available()
-{
-  # Notify that the services_available() function has not yet been implemented.
-  NIY "Installed services has not yet been implemented."
-}
-
-service_setup()
-{
-  (( $# == 0 )) || service_cli $@
+  (( $# == 0 )) || __sm.service.cli "$@"
 
   local _path _file
 
@@ -171,7 +128,7 @@ service_setup()
 
   for _path in "${service_paths[@]}"
   do
-    if variable_is_nonempty _path
+    if [[ -n "${_path}" ]]
     then
       if paths exist "${_path}"
       then
@@ -183,22 +140,25 @@ service_setup()
     fi
   done
 
-  ! __sm.command.exists "${service}_service_setup" || "${service}_service_setup"
+  if  __sm.command.exists "${service}_service_setup"
+  then
+    "${service}_service_setup"
+  fi
 
-  service_install_init_d "${service}"
+  __sm.service.initd.install "${service}"
 }
 
-service_uninstall()
+__sm.service.uninstall()
 {
-  NIY "service_uninstall() has not yet been implemented."
+  NIY "service uninstall has not yet been implemented."
   # 1. Remove init scripts.
   # 2. Unload OS service hooks.
   # 3. Deactivate database path.
 }
 
-service_start()
+__sm.service.start()
 {
-  (( $# == 0 )) || service_cli $@
+  (( $# == 0 )) || __sm.service.cli "$@"
 
   [[ -n "${service}" ]] || fail "To start a service, you must set the 'service' variable."
 
@@ -206,98 +166,83 @@ service_start()
   then
     log_step "Starting ${service}..." "${service}_start"
   else
-    service_init_start
+    __sm.service.init.start
   fi
 }
 
-service_stop()
+__sm.service.stop()
 {
-  variable_is_nonempty service ||
+  variables are nonempty service ||
     fail "To start a service, you must set the 'service' variable."
 
   if __sm.command.exists "${service}_stop"
   then
     log_step "Stopping ${service}..." "${service}_stop"
   else
-    service_init_stop
+    __sm.service.init.stop
   fi
 }
 
-service_reload()
+__sm.service.reload()
 {
-  (( $# == 0 )) || service_cli $@
+  (( $# == 0 )) || __sm.service.cli "$@"
 
-  variable_is_nonempty service ||
+  variables are nonempty service ||
     fail "To start a service, you must set the 'service' variable."
 
   if __sm.command.exists "${service}_reload"
   then
     "${service}_reload"
   else
-    service_init_reload
+    __sm.service.init.reload
   fi
 }
 
-service_restart()
+__sm.service.restart()
 {
-  (( $# == 0 )) || service_cli $@
+  (( $# == 0 )) || __sm.service.cli "$@"
 
-  variable_is_nonempty service ||
+  variables are nonempty service ||
     fail "To start a service, you must set the 'service' variable."
 
   if __sm.command.exists "${service}_restart"
   then
     log_step "Restarting ${service}..." "${service}_restart"
   else
-    service_init_restart
+    __sm.service.init.restart
   fi
 }
 
-service_init_restart()
+__sm.service.init.restart()
 {
   if __sm.command.exists "${service}_restart"
   then
     log_step "Restarting ${service}..." "${service}_restart"
   else
     log "Restarting ${service}..."
-    service_init_stop $@
-    service_init_start $@
+    __sm.service.init.stop $@
+    __sm.service.init.start $@
   fi
 }
 
-service_status()
+__sm.service.logtail()
 {
-  (( $# == 0 )) || service_cli $@
+  (( $# == 0 )) || __sm.service.cli "$@"
 
-  variable_is_nonempty service ||
-    fail "To start a service, you must set the 'service' variable."
-
-  if __sm.command.exists "${service}_status"
-  then
-    "${service}_status"
-  else
-    service_init_status
-  fi
-}
-
-service_logtail()
-{
-  (( $# == 0 )) || service_cli $@
-
-  variable_is_nonempty service ||
+  variables are nonempty service ||
     fail "To start a service, you must set the 'service' variable."
 
   if __sm.command.exists "${service}_logtail"
   then
     "${service}_logtail"
   else
-    service_init_logtail
+    __sm.service.init.logtail
   fi
 }
 
-service_info()
+__sm.service.info()
 {
-  (( $# == 0 )) || service_cli $@
+  (( $# == 0 )) || __sm.service.cli "$@"
 
   [[ -n "${service}" ]] ||
     fail "In order to get info on a service, the 'service' variable must be set."
@@ -306,15 +251,15 @@ service_info()
   then
     "${service}_info"
   else
-    service_init_info
+    __sm.service.init.info
   fi
 }
 
-service_configcheck()
+__sm.service.configcheck()
 {
-  (( $# == 0 )) || service_cli $@
+  (( $# == 0 )) || __sm.service.cli "$@"
 
-  variable_is_nonempty service ||
+  variables are nonempty service ||
     fail "To configcheck a service, the 'service' variable must be set."
 
   if __sm.command.exists "${service}_configcheck"
@@ -325,7 +270,8 @@ service_configcheck()
   fi
 }
 
-service_usage() {
+__sm.service.usage()
+{
   # TODO: Update this for service specific items.
   printf "
 Usage:
@@ -345,7 +291,7 @@ Options:
   return 0
 }
 
-service_cli()
+__sm.service.cli()
 {
   local _ignored_args=() _service_args=( $@ ) _token
 
@@ -356,51 +302,51 @@ service_cli()
     token="${extension_args[$index]}"
 
     case "$token" in
-      user)
+      (user)
         service_user="${extension_args[$((++index))]}"
         [[ -n "${service_user}" ]] ||
           error "a user name must follow keyword 'user'"
         ;;
-      version)
+      (version)
         service_version="${extension_args[$((++index))]}"
         [[ -n "${service_version}" ]] ||
           error "a version number string must follow keyword 'version'"
         ;;
-      data)
+      (data)
         service_data_path="${_package_args[$((++index))]}"
         [[ -n "${service_data_path}" ]] ||
           error "a path must follow keyword 'data'"
         ;;
-      pid)
+      (pid)
         service_pid_path="${_package_args[$((++index))]}"
         [[ -n "${service_pid_path}" ]] ||
           error "a path must follow keyword 'pid'"
         ;;
-      log)
+      (log)
         service_log_path="${_package_args[$((++index))]}"
         [[ -n "${service_log_path}" ]] ||
           error "a path must follow keyword 'log'"
         ;;
-      config)
+      (config)
         service_config_path="${_package_args[$((++index))]}"
         [[ -n "${service_config_path}" ]] ||
           error "a path must follow keyword 'config'"
         ;;
-      lock)
+      (lock)
         service_lock_path="${_package_args[$((++index))]}"
         [[ -n "${service_lock_path}" ]] ||
           error "a path must follow keyword 'lock'"
         ;;
-      db)
+      (db)
         service_db_path="${_package_args[$((++index))]}"
         [[ -n "${service_db_path}" ]] ||
           error "a path must follow keyword 'db'"
         ;;
-      help)
-        service_usage
+      (help)
+        __sm.service.usage
         exit 0
         ;;
-      --trace)
+      (--trace)
         set -o xtrace
         ;;
       *)
@@ -411,10 +357,10 @@ service_cli()
 
   extension_args=( "${_ignored_args[@]}" )
 
-  ext_service_initialize "${extension_args[@]}"
+  __sm.service.initialize "${extension_args[@]}"
 }
 
-service_pid()
+__sm.service.pid()
 {
   local _path="${run_path:="/var/run"}/${service}"
   local _pid=0
@@ -439,19 +385,21 @@ service_pid()
   return 0
 }
 
-service_load_conf_d()
+__sm.service.load.confd()
 {
   files source "${confd_path}/${service}.conf"
 }
 
-service_install_init_d()
+__sm.service.initd.install()
 {
-  local _service="${1:-}" _version="${2:-${package_version}}"
+  local _service="${1:-}" _version
+  shift ||fail "Service name was not passed in as the first parameter"
+  _version="${2:-${package_version}}"
 
-  variables_must_be_nonempty _service
-
-  paths exist "${init_scripts_path}" ||
+  if ! paths exist "${init_scripts_path}"
+  then
     return 0 # No bin/ dir, no need for it to be in the path.
+  fi
 
   if user is root
   then
@@ -464,17 +412,17 @@ service_install_init_d()
         mode 0755
     else
       # Use core svc init.d template
-      install_template "cli/init.d" \
+      templates install "cli/init.d" \
         to "${init_scripts_path}/${_service}" mode 0755
 
-      seed_template "${init_scripts_path}/${_service}" \
+      templates seed "${init_scripts_path}/${_service}" \
         modules_path "${modules_path}" \
         service "${service}" \
         service_user "${service_user}" \
         service_config_path "${service_config_path}"
     fi
 
-    service_activate "${service}" "${package_version}"
+    __sm.service.activate "${service}" "${package_version}"
 
     # TODO: Replace this with install_template + seed_template
     files write \
@@ -489,7 +437,7 @@ service_install_init_d()
   fi
 }
 
-service_init_start()
+__sm.service.init.start()
 {
   log_step "Starting ${service}..."
 
@@ -528,7 +476,7 @@ service_init_start()
   log_step success
 }
 
-service_init_stop()
+__sm.service.init.stop()
 {
   (( service_pid > 0 )) || error "Service pid has not been set, or is zero."
   log_step "Stopping ${service}..."
@@ -546,7 +494,7 @@ service_init_stop()
   log_step success
 }
 
-service_init_status()
+__sm.service.init.status()
 {
   log "statusing ${service}..."
 
@@ -583,7 +531,7 @@ service_init_status()
   fi
 }
 
-service_init_reload()
+__sm.service.init.reload()
 {
   log "reloading ${service}..."
 
@@ -607,35 +555,34 @@ service_init_reload()
   fi
 }
 
-service_init_usage()
+__sm.service.init.usage()
 {
   log "Usage:"
   log "  $0 {start|stop|restart|status|info|logtail}"
 }
 
-service_init_logtail()
+__sm.service.init.logtail()
 {
-  # TODO: Adjust this to allow for parameter passing.
-
-  tail -n 10 "${service_log_file}"
+  local _lines="${1:-10}"
+  tail -n ${_lines} "${service_log_file}"
 }
 
-service_init_info()
+__sm.service.init.info()
 {
-  NIY "service_init_info has not yet been implemented for the service module."
+  NIY "service init info has not yet been implemented for the service module."
 }
 
-service_conf_d()
+__sm.service.confd()
 {
   # TODO: Install a default conf.d template if extension does not define one.
-  template_exists "conf.d" || return 0
+  templates exist "conf.d" || return 0
 
-  install_template "conf.d.template" to "/etc/conf.d/${service}.conf" \
+  templates install "conf.d.template" to "/etc/conf.d/${service}.conf" \
     mode 0644 owner "${service_user}:${service_user}"
 
-  if template_exists "/etc/conf.d/${service}.conf"
+  if templates exist "/etc/conf.d/${service}.conf"
   then
-    seed_template "/etc/conf.d/${service}.conf" \
+    templates seed "/etc/conf.d/${service}.conf" \
       prefix_path "${prefix_path}" \
       init_scripts_path "${init_scripts_path}" \
       modules_path "${modules_path}" \
@@ -645,11 +592,11 @@ service_conf_d()
   fi
 }
 
-service_init_action()
+__sm.service.init.action()
 {
   local _action="${1:-}"
 
-  service_load_conf_d
+  __sm.service.load.confd
 
   if __sm.command.exists "${service}_${action}"
   then
@@ -659,38 +606,31 @@ service_init_action()
     then
       service_init_${action}
     else
-      service_init_usage
+      __sm.service.init.usage
     fi
   fi
 
   return $?
 }
 
-service_init_d()
+__sm.service.initd()
 {
-  service_load_conf_d # Load the configuration file.
-
-  # Sanity checks go here.
-  [[ -x "${service_binary}" ]] ||
-    fail "Could not find ${service_binary}, or ${service_binary} is not executable."
-
-  service_pid
-
-  service_cli # Parse the script arguments and take action accordingly.
-
-  service_init_action "${service_action}"
+  __sm.service.load.confd # Load the configuration file.
+  [[ -x "${service_binary}" ]] || fail "'${service_binary}' not found/executable."
+  __sm.service.pid
+  __sm.service.cli
+  __sm.service.init.action "${service_action}"
 }
 
-service_deactivate()
+__sm.service.deactivate()
 {
   local _service="${1:-"${service}"}"
 
-  [[ -n "${_service}" ]] ||
-    fail "A service name must be set or passed in to deactivate a service."
+  [[ -n "${_service}" ]] || fail "Service name must be set or given to deactivate."
 
   if files exist "${init_scripts_path}/${_service}"
   then
-    chmod_files 0644 "${init_scripts_path}/${_service}"
+    files chmod 0644 "${init_scripts_path}/${_service}"
 
     if user is root
     then # Add service to system startup
@@ -725,20 +665,17 @@ service_deactivate()
   # TDOO: hook into system's paths.
 }
 
-service_activate()
+__sm.service.activate()
 {
   local _service="${1:-"${service}"}"
-
-  [[ -n "${_service}" ]] ||
-    fail "The service name must be set or passed in to activate a service."
+  shift || fail "The service name must be set or given to activate a service."
 
   local _version="${2:-${package_version}}"
-
-  variables_must_be_nonempty _service _version
+  [[ -n "${_version}" ]] || fail "Version must be set or given to activate a service."
 
   if files are symlinks "${service_db_path}/active"
   then # TODO: use versionedfs to check if a version is active.
-    service_deactivate "${_service}"
+    __sm.service.deactivate "${_service}"
   fi
 
   if paths exist "${service_db_path}/${_version}"
@@ -793,7 +730,7 @@ service_activate()
   fi
 }
 
-service_status()
+__sm.service.status()
 {
   log "${service}:"
 
@@ -904,7 +841,7 @@ service_status()
   fi
 }
 
-service_signal()
+__sm.service.signal()
 {
   local _signal="${1}" _pid="${2:-0}"
   shift || fail "Cannot signal service;"\
diff --git a/core/sm/shell/string/functions b/core/sm/shell/string/functions
--- a/core/sm/shell/string/functions
+++ b/core/sm/shell/string/functions
@@ -9,3 +9,21 @@ __sm.string.contains.key()
 {
   [[ " $2 " =~ " $1=" ]]
 }
+
+__sm.string.ematch()
+{
+  local _value="$1" _regex="$2" _result
+
+  # Use grep for extended regexp.
+  echo "${_value}" | grep -qE "${_regex}"
+  _result=$?
+  case ${result} in
+    0|1)
+      # 0 & 1 are correct results.
+      return ${_result}
+      ;;
+    *)
+      fail "grep returned unknown error code: $result"
+      ;;
+  esac
+}
