More progress, still have not figured out what the syntax error in package is.

diff --git a/modules/bash/core/cli b/modules/bash/core/cli
--- a/modules/bash/core/cli
+++ b/modules/bash/core/cli
@@ -13,54 +13,62 @@ while [[ $# -gt 0 ]] ; do
     # TODO: Fall back on default actions instead of specifying them here
     #       In case the user has set their default serfice in the environment.
 
-    --disable-hooks)
-      hooks_flag=0
-      ;;
+    -*)
+      case "$token" in
+        --disable-hooks)
+          hooks_flag=0
+          ;;
 
-    --project)
-      project="$1"
-      shift
-      ;;
+        --project)
+          project="$1"
+          shift
+          ;;
 
-    --environment)
-      environment="$1"
-      shift
-      ;;
+        --environment)
+          environment="$1"
+          shift
+          ;;
 
-    --repo|repository)
-      repository="$1"
-      shift
-      ;;
+        --repo|repository)
+          repository="$1"
+          shift
+          ;;
 
-    --revision)
-      revision="$1"
-      shift
-      ;;
+        --revision)
+          revision="$1"
+          shift
+          ;;
 
-    --user)
-      user="$1"
-      shift
-      ;;
+        --user)
+          user="$1"
+          shift
+          ;;
 
-    --head)
-      head_flag=1
-      ;;
+        --head)
+          head_flag=1
+          ;;
 
-    --debug)
-      debug_flag=1
-      ;;
+        --debug)
+          debug_flag=1
+          ;;
 
-    -v|--version)
-      extension="core"
-      action="version"
-      ;;
+        -v|--version)
+          extension="core"
+          action="version"
+          ;;
 
-    --trace)
-      trace_flag=1
-      source "${modules_path}/bash/trace/initialize"
-      ;;
+        --trace)
+          trace_flag=1
+          source "${modules_path}/bash/trace/initialize"
+          ;;
 
-    --) extension_args=("$@") # Stop processing arguments.
+        --) extension_args=("$@") # Stop processing arguments.
+          ;;
+        *)
+          error "Unknown flag ${token}"
+          exit 1
+          ;;
+      esac
       ;;
 
     *)
@@ -132,7 +140,7 @@ while [[ $# -gt 0 ]] ; do
               extension="mod"
               ;;
 
-            edit|open)
+            edit|open|install)
               extension="ext"
               action="${token}"
               extension_args=("$@")
@@ -140,7 +148,10 @@ while [[ $# -gt 0 ]] ; do
               ;;
 
             *)
-              extension="${extension:-core}"
+              if [[ -z "${extension}" ]] ; then
+                error "Extension ${token} not found"
+                exit 1
+              fi
               ;;
           esac
         fi
diff --git a/modules/bash/core/dsl b/modules/bash/core/dsl
--- a/modules/bash/core/dsl
+++ b/modules/bash/core/dsl
@@ -29,22 +29,19 @@ bdsm_set_trap()
 
 modules()
 {
-  local _module _bdsm _extension _path _file
-  local _modules=("$@")
+  local _module _bdsm _extension _path _file _modules=("$@")
 
-  [[ ${#_modules[@]} -gt 0 ]] ||
-    fail "${extension} ${action} ${FUNCNAME}()\n => No modules specified to load."
+  [[ ${#_modules[@]} -gt 0 ]] || fail "No modules specified to load."
 
-  for _module in "${_modules[@]}"
-  do
+  for _module in "${_modules[@]}" ; do
     _bdsm="${modules_path}/bash/${_module}"
     _extension="${extension_modules_path}/bash/${_module}"
 
-    for _path in "${_bdsm}" "${_extension}"
-    do
-      for _file in "dsl" "initialize" "cli"
-      do
-        [[ -s "${_path}/${_file}" ]] && source "${_path}/${_file}"
+    for _path in "${_bdsm}" "${_extension}" ; do
+      for _file in dsl initialize cli ; do
+        if [[ -s "${_path}/${_file}" ]] ; then
+          source "${_path}/${_file}"
+        fi
       done
     done
   done
@@ -52,8 +49,7 @@ modules()
 
 load()
 {
-  local _file
-  local _files=("$@")
+  local _file _files=("$@")
 
   for _file in "${_files[@]}" ; do
     source_files "${extension_modules_path:-"$modules_path"}/bash/${_file}"
diff --git a/modules/bash/filesystem/dsl b/modules/bash/filesystem/dsl
--- a/modules/bash/filesystem/dsl
+++ b/modules/bash/filesystem/dsl
@@ -15,7 +15,10 @@ source_files()
     _file=${_file/\~\//$HOME\/} # Expand ~/ to full value of $HOME
 
     if file_is_nonempty "${_file}" ; then
-      source "${_file}" || fail "Failed to source ${_file}."
+      source "${_file}"
+      # TODO: figure out how to see if 'source' itself failed or simply
+      # returning nonzero code.
+      # || fail "Failed to source ${_file}."
     fi
   done
 }
