Extension argument parsing has now been rewritten.

diff --git a/modules/shell/extensions/dsl b/modules/shell/extensions/dsl
--- a/modules/shell/extensions/dsl
+++ b/modules/shell/extensions/dsl
@@ -1,11 +1,13 @@
 #!/usr/bin/env bash
 
 
-detect_action_path()
+# detect_action $extension action extension_args "${extension_args[@]}"
+detect_action()
 {
-  local _extension=$1 _action_var=$2 _variables_var=$3 _action_path=()
-  local extension_actions_path=$(path_join ${extensions_path} ${_extension} actions)
-  shift 3
+  local _extension="${1:=core}"
+  shift
+
+  local _action_path=("$extensions_path/$extension/actions")
 
   while (( $# > 0 ))
   do
@@ -13,39 +15,235 @@ detect_action_path()
     shift
 
     # Detect a namespace
-    if path_exists $(path_join $extension_actions_path "${_action_path[@]}" $token)
+    if path_exists "$(path_join "${_action_path[@]}" $token)"
     then
-      array_push _action_path $token
+      _action_path+=("$token")
       continue
 
     # Detect a file
-    elif file_exists $(path_join $extension_actions_path "${_action_path[@]}" $token)
+    elif file_exists "$(path_join "${_action_path[@]}" $token)"
     then
-      array_push _action_path $token
-      eval "${_action_var}=(\"\${_action_path[@]}\" \"\$token\")"
-      eval "${_variables_var}=(\"\$@\")"
+      action_path=$(array_join _action_path '/')
+      action="$token"
+      extension_args=("$@")
       return 0
 
     # run default if found
-    elif file_exists $(path_join $extension_actions_path "${_action_path[@]}" default)
+    elif file_exists "$(path_join "${_action_path[@]}" default)"
     then
-      eval "${_action_var}=(\"\${_action_path[@]}\" 'default')"
-      eval "${_variables_var}=(\"\$token\" \"\$@\")"
+      action="default"
+      action_path=$(array_join _action_path '/')
+      extension_args=("$token")
+      extension_args+=("$@")
       return 0
 
     # default to help if no defualt set in path
-    elif file_exists $(path_join $extension_actions_path "${_action_path[@]}" help)
+    elif file_exists "$(path_join "${_action_path[@]}" help)"
     then
-      eval "${_action_var}=(\"\${_action_path[@]}\" 'help')"
-      eval "${_variables_var}=(\"\$token\" \"\$@\")"
+      action="help"
+      action_path=$(array_join _action_path '/')
+      extension_args=("$token")
+      extension_args+=("$@")
       return 0
 
     # Not found, error.
     else
-      fail "Action or namespace '${token}' missing for extension ${extension}"
+      log "Usage: \n  bdsm ${extension} [namespace] [action]\nActions:\n   $(extension_actions "${extension}")"
     fi
   done
+
   fail "Action or namespace '${token}' missing for extension ${extension}"
+}
+
+detect_action_type()
+{
+  local _path="${1:-}" _action="${2:-}"
+
+  _path_type="$(file "${_path}/${_action}")"
+
+  case "${_path_type}" in
+
+    *sh[[:space:]]script*|*POSIX[[:space:]]shell*|*Bourne-Again*)
+      action_type="shell"
+      ;;
+
+    *ASCII*)
+      # Launch with helper dsl, if possible.
+      extension="${_path//.}"
+
+      case "${extension}" in
+        shell|zsh|bash|sh)
+          action_type="shell"
+          #rb) action_type="ruby"   ;;
+          ;;
+        *)
+          read -r shebang < "${_path}"
+
+          case "${shebang}" in
+            *ruby|*rbx|*jruby|*macruby)
+              binary="${shebang##*(#|!)}"
+              binary="${binary##* }"
+              action_type="ruby"
+              ;;
+            *)
+              if [[ -x "${_path}" ]] ; then
+                action_type="binary"
+              else
+                action_type="not executable"
+              fi
+              ;;
+          esac
+          ;;
+      esac
+      result=$?
+      ;;
+
+    cannot[[:space:]]open)
+      action_type="dne"
+      ;;
+
+    *)
+      if file_is_executable "${_path}"
+      then
+        action_type="binary"
+      else
+        action_type="noexec"
+      fi
+      ;;
+  esac
+
+  return $?
+}
+
+extension_modules_load()
+{
+  local _token _namespace=()
+
+  # Load the extensions's core module
+  source_files \
+    "${extension_modules_path}/shell/dsl" \
+    "${extension_modules_path}/shell/initialize" \
+    "${extension_modules_path}/shell/cli"
+
+  while (( $# > 0 ))
+  do
+    _namespace+=("${1}")
+    shift
+
+    namespace="$(path_join ${_namespace[*]})"
+
+    source_files \
+      "${extension_modules_path}/shell/${namespace}/dsl" \
+      "${extension_modules_path}/shell/${namespace}/initialize" \
+      "${extension_modules_path}/shell/${namespace}/cli"
+  done
+}
+
+extension_run()
+{
+  local _type="${1:-}" _path="${2:-}" _namespaces
+
+  # Now based on the determined _type we launch the extension.
+  case "${_type}" in
+    shell)
+      (
+      enable_backtrace
+      if [[ "${action##*/}" == help ]]
+      then # Load the help module also.
+        modules core help
+      else
+        modules core
+      fi
+
+      _namespaces=${_path##${extension_actions_path}}
+
+      extension_modules_load ${_namespaces//\// }
+
+      . "${_path}/${action}"
+
+      ) || result=$?
+      return $result
+      ;;
+
+    ruby)
+      requires=()
+      for script in dsl initialize
+      do
+        requires+=( "-r${modules_path}/ruby/core/${script}.rb" )
+      done
+
+      "${binary:-ruby}" -I"${modules_path}/ruby" -I"${extension_modules_path}/ruby" \
+        ${requires[@]} "${_path}/${action}"
+      ;;
+    # python|lua|javascript)
+      #   ADD "${modules_path}/${_type}/" to the lib path so the script can require "bdsm"
+      #  "${_path}"
+      #  ;;
+    dne|noexec)
+      fail "Processing ${action} failed, file type is unknown, file does not exist or file is not executable."
+      ;;
+    binary|*)
+      "${_path}/${action}" ${extension_action} ${extension_args[*]}
+      ;;
+  esac || result=$?
+
+  return $result
+}
+
+extension_extend_from()
+{
+  # "release" "${extension_args[@]}"
+  local _source="${1:-}" _params _name
+  if variable_is_nonempty _source
+  then
+    shift
+    _name="${1}"
+    shift
+    _params=($@)
+
+    if variable_is_nonempty _name
+    then
+      case "${_source}" in
+        git)
+          NIY "extend from git repository"
+          fetch_extensions_git_repository "${_params[${#_params[@]}]}"
+          extensions_install "${_name}" "${_params[@]}"
+          ;;
+        github)
+          NIY "extend from github repository"
+          ;;
+        help)
+          NIY "extend from help"
+          ;;
+        release)
+          NIY "extend from release"
+          ;;
+        tarball)
+          NIY "extend from tarball"
+          ;;
+        hg)
+          NIY "extend from hg repository"
+          ;;
+        svn)
+          NIY "extend from svn repository"
+          ;;
+        rsync)
+          NIY "extend from rsync dirctory url"
+          ;;
+        scp)
+          NIY "extend from scp tarball url"
+          ;;
+        default|wayneeseguin|*)
+          fetch_extensions_git_repository
+          extensions_install "${_name}" "${_params[@]}"
+          ;;
+      esac
+    else
+      fail "An extension name must be given."
+    fi
+  else
+    fail "Source must be specified."
+  fi
 }
 
 #
@@ -95,27 +293,19 @@ extension_action()
 
   unset extension action
 
-  export extension="${1:-}"
+  export extension="${1:-}" action="${2:-}"
 
   if variable_is_nonempty extension
   then
     shift
-    export action="${1:-}"
-
-    if variable_is_nonempty action
+    if array_is_empty extension_args
     then
-      shift
-    else
-      fail "'action' is not set! Something has gone terribly wrong."
+      extension_args="$@"
     fi
   else
     fail "'extension' is not set! Something has gone terribly wrong."
   fi
 
-  if (( ${#extension_args[@]} == 0 ))
-  then
-    extension_args="$@"
-  fi
   export extension_args
 
   extension_path="$extensions_path/$extension"
@@ -128,135 +318,15 @@ extension_action()
   paths=$(env | awk -F= -v ORS=' ' '/_path/{print $1}')
   flags=$(env | awk -F= -v ORS=' ' '/_flag/{print $1}')
 
-  enter "${extension_path}" ||
-    fail "Could not enter the extension directory!\n    (${extension_path})"
+  detect_action ${extension_args[@]}
+
+  enter "${extension_path}"
 
   bdsm_exports
 
-  # TODO: Alter this here for nesting.
-  if variable_is_nonempty namespace
-  then
-    action_path="${extension_actions_path}/${namespace}/${action}"
-  else
-    action_path="${extension_actions_path}/${action}"
-  fi
+  detect_action_type "${action_path}" "${action}"
 
-  if file_exists "${action_path}" && file_is_executable "${action_path}"
-  then
-    true # Direct action, continue.
-  else
-    fail "Action or namespace '${action}' missing for extension ${extension}\n    (${action_path})"
-  fi
-
-  action_path_type="$(file "$action_path")"
-
-  case "${action_path_type}" in
-
-    *sh[[:space:]]script*|*POSIX[[:space:]]shell*|*Bourne-Again*)
-      action_type="shell"
-      ;;
-
-    *ASCII*)
-      # Launch with helper dsl, if possible.
-      extension="${action_path//.}"
-
-      case "${extension}" in
-        shell|zsh|bash|sh)
-          action_type="shell"
-          #rb) action_type="ruby"   ;;
-          ;;
-        *)
-          read -r shebang < "${action_path}"
-
-          case "${shebang}" in
-            *ruby|*rbx|*jruby|*macruby)
-              binary="${shebang##*(#|!)}"
-              binary="${binary##* }"
-              action_type="ruby"
-              ;;
-            *)
-              if [[ -x "${action_path}" ]] ; then
-                action_type="binary"
-              else
-                action_type="not executable"
-              fi
-              ;;
-          esac
-          ;;
-      esac
-      result=$?
-      ;;
-
-    cannot[[:space:]]open)
-      action_type="dne"
-      ;;
-
-    *)
-      if file_is_executable "${action_path}"
-      then
-        action_type="binary"
-      else
-        action_type="noexec"
-      fi
-      ;;
-  esac || result=$?
-
-  # Now based on the determined action_type we launch the extension.
-  case "${action_type}" in
-    shell)
-      (
-      enable_backtrace
-      if [[ "${action##*/}" == help ]]
-      then # Load the help module also.
-        modules core help
-      else
-        modules core
-      fi
-
-      # Load the extensions's core module
-      source_files \
-        "${extension_modules_path}/shell/dsl" \
-        "${extension_modules_path}/shell/initialize" \
-        "${extension_modules_path}/shell/cli"
-
-      # If a namespace was called, load the namespace's module.
-      if variable_is_nonempty namespace
-      then
-        source_files \
-          "${extension_modules_path}/shell/${namespace}/dsl" \
-          "${extension_modules_path}/shell/${namespace}/initialize" \
-          "${extension_modules_path}/shell/${namespace}/cli"
-      fi
-
-      . "${action_path}"
-
-      ) || result=$?
-      return $result
-      ;;
-
-    ruby)
-      requires=()
-      for script in dsl initialize
-      do
-        requires+=( "-r${modules_path}/ruby/core/${script}.rb" )
-      done
-
-      "${binary:-ruby}" -I"${modules_path}/ruby" -I"${extension_modules_path}/ruby" \
-        ${requires[@]} "${action_path}"
-      ;;
-    # python|lua|javascript)
-      #   ADD "${modules_path}/${action_type}/" to the lib path so the script can require "bdsm"
-      #  "${action_path}"
-      #  ;;
-    dne|noexec)
-      fail "Processing ${action} failed, file type is unknown, file does not exist or file is not executable."
-      ;;
-    binary|*)
-      "${action_path}" "${extension_action}" "${extension_args[@]}"
-      ;;
-  esac || result=$?
-
-  return $result
+  extension_run "${action_type}" "${action_path}"
 }
 
 #
