Reworked mustache to use Google Go

diff --git a/core/internal/shell/templates/functions b/core/internal/shell/templates/functions
--- a/core/internal/shell/templates/functions
+++ b/core/internal/shell/templates/functions
@@ -55,7 +55,7 @@ __sm.templates.exists()
 __sm.templates.install()
 {
   typeset _template _target _owner _mode _variable _path _append _json \
-    _json_file _tmp_file _target_path
+    _json_file _tmp_file _target_path _data_string
 
   typeset -a _params _data _strings
 
@@ -92,12 +92,15 @@ __sm.templates.install()
     done"
   fi
 
+  _data_string+="--data \""
   for (( _index=1 ; _index <= ${#_data} ; _index = _index + 2 ))
-  do _params+=( --data "${_data[${_index}]}=${_data[$((_index+1))]}" )
+  do _data_string+="${_data[${_index}]}=${_data[$((_index+1))]}:~"
   done
 
-  if ! "${sm_path}/bin/sm-mustache" "${_params[@]}"
-  then log error "There was an error rendering the template!"
+  _params+="${_data_string}\""
+
+  if ! eval "${sm_path}/bin/sm-mustache ${_params[@]}"
+  then log error "There was an error rendering the template gay! ${_params[@]}"
   fi
 
   chmod "${_mode}" "${_target}"
