Steps module complete.

diff --git a/core/ext/modules/shell/steps/dsl b/core/ext/modules/shell/steps/dsl
--- a/core/ext/modules/shell/steps/dsl
+++ b/core/ext/modules/shell/steps/dsl
@@ -8,23 +8,16 @@ start_step()
 step()
 {
   local name="$1"
-  shift
-
-  if variable_is_empty name
-  then fail "step_start [name] #missing name."
-  fi
+  shift || fail "Cannot take step as no step name given;"\
+    "step [name] <- missing name."
 
   start_step "$name"
 
-  if command_exists before_step
-  then before_step "$name" "$@"
-  fi
+  ! command_exists before_step || before_step "$name" "$@"
 
   "$name" "$@"
 
-  if command_exists after_step
-  then after_step "$name" "$@"
-  fi
+  ! command_exists after_step || after_step "$name" "$@"
 }
 
 steps()
@@ -47,13 +40,7 @@ retreat()
   while array_is_nonempty steps_started
   do
     array_pop steps_started step
-
-    if command_exists "fail_${step}"
-    then "fail_${step}"
-    fi
-
-    if command_exists after_step
-    then after_step "fail_${step}"
-    fi
+    ! command_exists "fail_${step}" || "fail_${step}"
+    ! command_exists after_step || after_step "fail_${step}"
   done
 }
