More cleanup.

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -8,8 +8,7 @@ actions_for_extension() {
 
 version()
 {
-  printf "\n%s\n\n" \
-    "bdsm ${VERSION:-"?.?.?"} http://bdsm.beginrescueend.com/ by Wayne E. Seguin (wayneeseguin@gmail.com)"
+  log "\nbdsm ${VERSION:-"?.?.?"} http://bdsm.beginrescueend.com/ by Wayne E. Seguin (wayneeseguin@gmail.com)\n"
 }
 
 usage()
@@ -21,131 +20,95 @@ usage()
 
 db()
 {
-  if [[ -f "$1" ]] ; then
-    database_file="$1" ; shift
-    if [[ ! -f "$database_file" ]] ; then
-      mkdir -p $(dirname $database_file)
-      touch $database_file
-    fi
-  else
-    echo "usage: $0 database key [value]"
-    exit 1
-  fi
+  [[ -f "$1" ]] || fail "db() => Usage: $0 database key [value]"
 
-  key="$1" ; shift
-  if [[ -z "$key" ]] ; then
-    echo "usage: $0 database key [value]"
-    exit 1
-  else
-    value="$*"
-    if [[ "unset" = "$value" ]] || [[ "delete" = "$value" ]] ; then
+  database_file="$1" ; shift
+  key="$1"           ; shift
+
+  ensure_paths_exist $(dirname $database_file)
+  ensure_files_exist "$database_file"
+
+  [[ -n "$key" ]] || fail "usage: $0 database key [value]"
+
+  value="$*"
+  case "$value" in
+    unset|delete)
       sed -i.tmp "s#^$key=.*\$##" $database_file
-    else
+      ;;
+    *)
       if [[ -z "$value" ]] ; then # get
-        awk -F= '/^'"$key"'=/{print $2}' $database_file
+        awk -F= '/^'"${key}"'=/{print $2}' "$database_file"
       else # set
-        if [[ -z "$(awk -F= "/^'"$key"'=/{print $2}" $database_file)" ]] ; then # append
+        if ! awk -F= "/^'"$key"'=/{print $2}" "$database_file" >/dev/null 2>&1; then
           echo "$key=$value" >> $database_file
         else # overwrite
-          sed -i.tmp "s#^$key=.*\$#$key=$value#" $database_file
+          sed -i.tmp "s#^$key=.*\$#$key=$value#" "$database_file"
         fi
       fi
-    fi
-  fi
+      ;;
+  esac
 }
 
 fetch()
 {
-  fetch_command=$(which curl)
-  if [[ $? -ne 0 ]] ; then
-    $scripts_path/log "fail" \
-      "rvm requires curl, which does not seem to exist in your path :("
-    exit 1
-  else
+  if fetch_command=$(which curl) ; then
     fetch_command="$fetch_command -O -L --create-dirs -C - " # -s for silent
+  else
+    fail "bdsm requires curl, which was not found in the PATH :(\nPlease install curl and try again."
   fi
 
-  pushd "$archives_path" > /dev/null 2>&1
+  (
+  cd "$archives_path"
 
-  if [[ -z "$1" ]] ; then
-    $scripts_path/log "fail" "BUG: $0 called without an argument :/"
-    exit 1
-  fi
+  [[ -n "${1}" ]] || fail "BUG: $0 called without an argument :/"
 
-  archive=$(basename "$1") ; downlaod=1
+  archive=$(basename "$1")
+  download=1
 
-  (( $debug_flag )) && $scripts_path/log "debug" "Fetching $archive"
+  debug "Fetching $archive"
 
   # Check first if we have the correct archive
-  if [[ -e "$archive" ]] && [[ -e "$archive.md5" ]] ; then
-
-    if (( $debug_flag )) ; then
-      $scripts_path/log "debug" "Found archive and its md5, testing correctness"
-    fi
+  if [[ -e "$archive" && -e "$archive.md5" ]] ; then
+    debug "Found archive and its md5, testing correctness"
 
     if [[ $(md5sum --status -c "$archive.md5") -gt 0 ]] ; then
-
-      if (( $debug_flag )) ; then
-        $scripts_path/log "debug" "Archive is bad, downloading"
-      fi
+      debug "Archive is bad, downloading"
       download=1
-
     else
-
-      if (( $debug_flag )) ; then
-        $scripts_path/log "debug" "Archive is good, not downloading"
-      fi
+      debug "Archive is good, not downloading"
       download=0
       result=0
-
     fi
-
   else
-
-    if (( $debug_flag )) ; then
-      $scripts_path/log "debug" "No archive or no MD5, downloading"
-    fi
+    debug "No archive or no MD5, downloading"
     download=1
-
   fi
 
   if [[ $download -gt 0 ]] ; then
-    eval $fetch_command "$1"
-    result=$?
-    if [[ $result -gt 0 ]] ; then
+    if ! eval $fetch_command "$1" ; then
       retry=0
       if [[ $result -eq 78 ]] ; then
-        $scripts_path/log "error" "The requested url does not exist: '$1'"
+        error "The requested url does not exist: '$1'"
       elif [[ $result -eq 18 ]] ; then
-        $scripts_path/log "error" \
-          "Only a part of the file was transferred. Removing and re-trying."
+        error "Only a part of the file was transferred. Removing and re-trying."
         rm -f "$archive"
         retry=1
       elif [[ $result -eq 33 ]] ; then
-        if (( $debug_flag )) ; then
-          $scripts_path/log "debug" \
-            "Server does not support 'range' command, removing '$archive'"
-        fi
+        debug "Server does not support 'range' command, removing '$archive'"
         rm -f "$archive"
         retry=1
       else
-        $scripts_path/log "error" \
-          "There was an error, please check $log_path/*.error.log"
+        error "There was an error, please check $log_path/*.error.log"
       fi
 
       if [[ $retry -eq 1 ]] ; then
-        eval $fetch_command "$1"
-        result=$?
-        if [[ $result -gt 0 ]] ; then
-          $scripts_path/log "error" \
-            "There was an error, please check $log_path/*.error.log"
+        if ! eval $fetch_command "$1" ; then
+          error "There was an error, please check $log_path/*.error.log"
         fi
       fi
-
     fi
-    popd > /dev/null 2>&1
   fi
 
-  return $result
+  return $0
 }
 
