Extensions module cleansing.

diff --git a/core/ext/modules/shell/extensions/detection/dsl b/core/ext/modules/shell/extensions/detection/dsl
--- a/core/ext/modules/shell/extensions/detection/dsl
+++ b/core/ext/modules/shell/extensions/detection/dsl
@@ -4,10 +4,11 @@
 detect_action()
 {
   extensions_path=$1
-  shift || fail "$FUNCNAME: Cannot detect action; No extensions path was passed"
+  shift || fail "$FUNCNAME: Cannot detect action; No extensions path was given."
 
   extension="${1:-core}"
-  shift
+  # Question: v v v ^ ^  The logic here seems... fuzzy ~ Wayne
+  shift || fail "$FUNCNAME: Cannot detect action; No extension name was given."
 
   local token _word _action_path="$extensions_path/$extension/actions"
 
@@ -119,12 +120,12 @@ detect_action()
   return 0
 }
 
-# find modules on path
-# return longest module path on top
+# find modules on path and return the longest module path on top
 detect_modules_paths()
 {
   local root="$1" path="" IFS='/'
-  shift
+  shift || fail "$FUNCNAME: Cannot detect modules path;"\
+    "modules root was not given as the first parameter."
   _module_definitions=( )
   while (( $# > 0 ))
   do
@@ -142,7 +143,14 @@ detect_modules_paths()
 detect_module_modules_action()
 {
   debug detect_module_modules_action "start:$*:"
-  local _modules_path="$1" _module_path="$2" _module_params="$3" _module_name module_path
+
+  local _modules_path="${1:-}" _module_path="${2:-}" _module_params="${3:-}" \
+    _module_name module_path
+
+  shift || fail "$FUNCNAME: modules path was not given as the first parameter"
+  shift || fail "$FUNCNAME: another modules path was not given as the second parameter"
+  shift || fail "$FUNCNAME: module parameters were not given as the third parameter"
+
   if [[ -s "${_modules_path}/${_module_path}/modules" ]]
   then
     for _module_name in $( cat "${_modules_path}/${_module_path}/modules" )
@@ -185,8 +193,12 @@ detect_modules_action()
 {
   trace_filter modules_action
 
-  extensions_path=$1 extension="${2:-core}"
-  shift 2 # TODO: proper error handling here...
+  extensions_path="${1:-}" extension="${2:-core}"
+  # Question ^^^^^ vvvvvvvv The :-core piece looks suspicious ...
+  shift || fail "$FUNCNAME: cannot detect modules action;"\
+    " Extensions path was not given as first parameter."
+  shift || fail "$FUNCNAME: cannot detect modules action;"\
+    " Extension name was not given as second parameter."
 
   local token _word _modules_path="$extensions_path/$extension/modules/shell"
   local __params=("$@") _module_path _module_params _module_name
@@ -194,6 +206,7 @@ detect_modules_action()
   # first level modules dependency
   local _module_definition _module_definitions=()
   detect_modules_paths "${_modules_path}" "${__params[@]}"
+
   for _module_definition in "${_module_definitions[@]}"
   do
     _module_path="${_module_definition//=*}"
@@ -227,9 +240,18 @@ detect_modules_action()
 detect_unique_2nd_level_action()
 {
   trace_filter detect_unique_2nd_level_action
-  extensions_path=$1 extension=$2
-  local _action=$3 _actions_path _found_actions=() _found_actions_paths _found_action_path
-  shift 3
+
+  extensions_path="${1:-}" extension="${2:-}"
+  local _action="${3:-}" _actions_path _found_actions=() _found_actions_paths \
+    _found_action_path
+
+  shift || fail "$FUNCNAME: cannot detect modules action;"\
+    " Extensions path was not given as first parameter."
+  shift || fail "$FUNCNAME: cannot detect modules action;"\
+    " Extension name was not given as second parameter."
+  shift || fail "$FUNCNAME: cannot detect modules action;"\
+    " Action was not given as third parameter."
+
   _actions_path="$extensions_path/$extension/actions"
   if [[ -d "${_actions_path}" ]]
   then
@@ -484,10 +506,9 @@ extension_run()
 #
 extension_action()
 {
-  if (( extension_action_calls > 0 ))
-  then
-    fail "Cannot call a 2nd time:\n  extension_action ${extension_args[@]}"
-  fi
+  (( extension_action_calls == 0 )) ||
+    fail "$FUNCNAME: Cannot call a 2nd time:\n"\
+    "  extension_action ${extension_args[@]}"
 
   extension_action_calls+=1
 
diff --git a/core/ext/modules/shell/extensions/manipulation/dsl b/core/ext/modules/shell/extensions/manipulation/dsl
--- a/core/ext/modules/shell/extensions/manipulation/dsl
+++ b/core/ext/modules/shell/extensions/manipulation/dsl
@@ -32,23 +32,18 @@
 extension_version()
 {
   local _extension="${1:-}"
+  shift || fail "$FUNCNAME: Cannot retrieve extension version;"\
+    " No extension was given."
+  true ${extension_path:="${extensions_path}/${_extension}"}
 
-  if variable_is_nonempty _extension
+  if file_exists "${extension_path}/VERSION"
   then
-    shift
-    true ${extension_path:="${extensions_path}/${_extension}"}
-
-    if file_exists "${extension_path}/VERSION"
-    then
-      read -r extension_version < "${extension_path}/VERSION"
-    else
-      extension_version="head"
-    fi
-
-    log "${extension}-${extension_version}"
+    read -r extension_version < "${extension_path}/VERSION"
   else
-    fail "Cannot retrieve extension version, as no extension was given."
+    extension_version="head"
   fi
+
+  log "${extension}-${extension_version}"
 }
 
 #
@@ -101,12 +96,11 @@ extension_license()
 {
   local _extension="${1:-${extension}}"
 
-  if variable_is_nonempty _extension
-  then
-    cat -v "${extensions_path}/${_extension}/LICENSE"
-  else
-    fail "Cannot display extension license, as an extension was not given."
-  fi
+  variable_is_nonempty _extension ||
+    fail "$FUNCNAME: Cannot display extension license;"\
+    " Extension name was not given."
+
+  cat -v "${extensions_path}/${_extension}/LICENSE"
 }
 
 #
@@ -151,26 +145,21 @@ extension_actions()
 {
   local _extension="${1:-}" _files _file _actions=()
 
-  if variable_is_nonempty _extension
-  then
-    if path_exists "${extension_actions_path}"
-    then
-      _files=($(
-      find "${extension_actions_path}" -mindepth 1 -type f -perm -o+rx
-      ))
+  shift || fail "$FUNCNAME; Cannot list actions for extension;"\
+    " No extension was given."
 
-      for _file in "${_files[@]}"
-      do
-        _actions+=("${_file#${extension_actions_path}}")
-      done
-      _actions="${_actions[@]}" # Convert from array to string.
-      printf "${_actions}"
-    else
-      return 0
-    fi
-  else
-    fail "Cannot list actions for extension, as no extension was given."
-  fi
+  path_exists "${extension_actions_path}" || return 0
+
+  _files=($(
+  find "${extension_actions_path}" -mindepth 1 -type f -perm -o+rx
+  ))
+
+  for _file in "${_files[@]}"
+  do
+    _actions+=("${_file#${extension_actions_path}}")
+  done
+  _actions="${_actions[@]}" # Convert from array to string.
+  printf "${_actions}"
 }
 
 #
@@ -206,32 +195,27 @@ extension_actions()
 #
 extension_install()
 {
-  local _extension="${1:-}" _src
-  _src="${2:-${_extension}}"
+  # TODO: This should likely be removed now with sets/ext ?
 
-  if variable_is_nonempty _extension
-  then
-    if extension_is_valid "${extensions_src_path}/${_src}"
-    then
-      log "Installing ${_extension}"
-      if path_exists "${sm_path}/exts/${_extension}"
-      then
-        remove_paths "${sm_path}/exts/${_extension}"
-      fi
+  local _extension="${1:-}" _src="${2:-${_extension}}"
+  shift || fail "$FUNCNAME: Cannot install extension;"\
+    " No extension name was given."
 
-      copy_directory "${extensions_src_path}/${_src}" \
-        to "${sm_path}/exts/${_extension}"
+  extension_is_valid "${extensions_src_path}/${_src}" ||
+    error "$FUNCNAME: ${extensions_src_path}/${_src} is not a valid extension,"\
+    "as it is missing VERSION and/or actions/help files."
 
-      write "${extension_uri}" to "${sm_path}/exts/${_extension}/.uri"
+  log "Installing ${_extension}"
 
-      #
-      # TODO: Process extension dependencies...
-      #
-    else
-      error "${extensions_src_path}/${_src} is not a valid extension,"\
-        "as it is missing VERSION and/or actions/help files."
-    fi
-  else
-    fail "Cannot install an extension, as no extension name was given."
-  fi
+  ! path_exists "${sm_path}/exts/${_extension}" ||
+    remove_paths "${sm_path}/exts/${_extension}"
+
+  copy_directory "${extensions_src_path}/${_src}" \
+    to "${sm_path}/exts/${_extension}"
+
+  write "${extension_uri}" to "${sm_path}/exts/${_extension}/.uri"
+
+  #
+  # TODO: Process extension dependencies...
+  #
 }
diff --git a/core/ext/modules/shell/extensions/standard/dsl b/core/ext/modules/shell/extensions/standard/dsl
--- a/core/ext/modules/shell/extensions/standard/dsl
+++ b/core/ext/modules/shell/extensions/standard/dsl
@@ -2,7 +2,10 @@
 
 extension_path()
 {
-  local path extension=$1
+  local path extension="${1:-}"
+  shift || fail "$FUNCNAME: Cannot process extension path;"\
+    " No extension name was given."
+
   for path in ${extensions_search_paths[@]}
   do
     if [[ -d "${path}/${extension}/actions" || -d "${path}/${extension}/modules" ]]
@@ -16,19 +19,24 @@ extension_path()
 
 extension_is_valid()
 {
-  local _path="$1"
+  local _path="${1:-}"
 
-  if [[ -n "${_path}" ]]
-  then
-    # TODO: Add all extension requirement checks here.
-    [[ -d "${_path}/actions" ]] || [[ -d "${_path}/modules" ]]
-  else
+  shift || fail "$FUNCNAME: Cannot check if extension is valid;"\
+    " No extension path was given."
+
+  [[ -n "${_path}" ]] ||
     fail "Cannot determine if an extension is valid, as the path to the extension was not given."
-  fi
+
+  # TODO: Add all extension requirement checks here.
+  [[ -d "${_path}/actions" ]] || [[ -d "${_path}/modules" ]]
 }
 
 detect_extension_existence()
 {
-  extensions_path=$1 extension=$2
+  extensions_path="${1:-}" extension="${2:-}"
+  shift || fail "$FUNCNAME: Cannot detect extension existence;"\
+    " No extension path was given."
+  shift || fail "$FUNCNAME: Cannot detect extension existence;"\
+    " No extension name was given."
   extension_is_valid $extensions_path/$extension
 }
