Made fetch_extensions_repository() more robust.

diff --git a/extensions/ext/modules/bash/dsl b/extensions/ext/modules/bash/dsl
--- a/extensions/ext/modules/bash/dsl
+++ b/extensions/ext/modules/bash/dsl
@@ -35,28 +35,55 @@ md5_match()
 
 fetch_extensions_repository()
 {
-  (
-  if directory_exists "$extensions_src_path/.git" ; then
+  local initial_pwd="$PWD"
+
+  if directory_exists "$extensions_src_path/.git"
+  then
     log "Updating $extension repository."
 
     enter "$extensions_src_path"
 
-    git fetch ${remote:-origin} >/dev/null 2>&1
+    if git fetch ${remote:-origin}
+    then
+      log "Successfully fetched from ${extensions_repository_url}"
+    else
+      fail "Failed fetching ${extensions_repository_url}"\
+        "into ${extensions_src_path} as git fetch returned error code ($?)"
+    fi
 
     # TODO: Branch switching logic
+    if git reset --hard HEAD
+    then
+      log "Successfully reset to HEAD from ${extensions_repository_url}"
+    else
+      fail "Failed fetching ${extensions_repository_url}"\
+        "into ${extensions_src_path} as git reset returned error code ($?)"
+    fi
 
-    git reset --hard HEAD >/dev/null 2>&1
-    git pull --rebase --force ${remote:-origin} "${branch:-master}" >/dev/null 2>&1
+    if git pull --rebase --force ${remote:-origin} "${branch:-master}"
+    then
+      log "Successfully updated from ${extensions_repository_url}"
+    else
+      fail "Failed pulling ${extensions_repository_url}"\
+        "into ${extensions_src_path} as git pull returned error code ($?)"
+    fi
   else
     log "Cloning $extension repository from ${extensions_repository_url}"
 
-    enter "${src_path}"
+    enter "${extensions_src_path%\/*}"
 
     # TODO: git/hg/svn url detection, only git to start for now
 
-    git clone --depth 1 "${extensions_repository_url}" "extensions" >/dev/null 2>&1
+    if git clone --depth 1 "${extensions_repository_url}" "${extensions_src_path}"
+    then
+      log "Successfully cloned ${extensions_repository_url}"
+    else
+      fail "Failed cloning ${extensions_repository_url}"\
+        "into ${extensions_src_path} as git clone returned error code ($?)"
+    fi
   fi
-  )
+
+  enter "$initial_pwd"
 }
 
 fetch_tarball()
