More wording alterations and code simplification.

diff --git a/core/cli/actions/clone b/core/cli/actions/clone
--- a/core/cli/actions/clone
+++ b/core/cli/actions/clone
@@ -3,59 +3,50 @@
 NYI
 # extension_is_installed removed, as it was not working already.
 
-if array_is_nonempty extension_args
-then
-  for (( index = 0 ; index < ${#extension_args[@]} ; index++ ))
-  do
-    token="${extension_args[${index}]}"
-    case "${token}" in
-      to)
-        _target="${extension_args[$((++index))]}"
-        ;;
-      from)
-        _source="${extension_args[$((++index))]}"
-        ;;
-      *)
-        if [[ -z "${_source}" ]]
-        then
-          _source="$token"
-        elif [[ -z "${_target}" ]]
-        then
-          _target="$token"
-        else
-          break
-        fi
-        ;;
-    esac
-  done
-
-  # Sanity checks.
-  if variable_is_nonempty _source
-  then
-    if variable_is_nonempty _target
-    then
-      if extension_is_installed "${_source}"
-      then
-        if extension_is_installed "${_target}"
-        then
-          error "The target extension '${_target}' already exists; "\
-            "cannot create it from ${_source}."
-        else
-          copy_directory \
-            from "${extensions_development_path}/${_source}" \
-            to "${extensions_development_path}/${_target}"
-
-        fi
-      else
-        error "The extension '${_source}' was not found installed; "\
-          "cannot create a new extension from it."
-      fi
-    else
-      error "A target extension name must be specified."
-    fi
-  else
-    error "A source extension name must be specified."
-  fi
-else
+array_is_nonempty extension_args ||
   error "An extension name must be specified."
+
+for (( index = 0 ; index < ${#extension_args[@]} ; index++ ))
+do
+  token="${extension_args[${index}]}"
+  case "${token}" in
+    to)
+      _target="${extension_args[$((++index))]}"
+      ;;
+    from)
+      _source="${extension_args[$((++index))]}"
+      ;;
+    *)
+      if [[ -z "${_source}" ]]
+      then
+        _source="$token"
+      elif [[ -z "${_target}" ]]
+      then
+        _target="$token"
+      else
+        break
+      fi
+      ;;
+  esac
+done
+
+# Sanity checks.
+variable_is_nonempty _source ||
+  error "A source extension name must be specified."
+
+variable_is_nonempty _target ||
+  error "A target extension name must be specified."
+
+extension_is_installed "${_source}" ||
+  error "The extension '${_source}' was not found installed; "\
+    "cannot create a new extension from it."
+
+if extension_is_installed "${_target}"
+then
+  error "The target extension '${_target}' already exists; "\
+    "cannot create it from ${_source}."
+else
+  copy_directory \
+    from "${extensions_development_path}/${_source}" \
+    to "${extensions_development_path}/${_target}"
 fi
diff --git a/core/cli/actions/console b/core/cli/actions/console
--- a/core/cli/actions/console
+++ b/core/cli/actions/console
@@ -2,29 +2,19 @@
 
 shell_version=( $( ${user_shell}  --version | head -n 1 ) )
 
-if [[ "${shell_version[1]}" == "bash," ]] && (( ${BASH_VERSINFO[0]} > 3 ))
-then
-  trap - ERR
-  ${user_shell} --rcfile <(echo "
-    [[ -s ~/.bash_profile ]] && source ~/.bash_profile
-    [[ -s ~/.profile ]] && source ~/.profile
-    source ${sm_path}/core/sm/modules/shell/core/initialize
-    module ext/vcs
-    fail()
-    {
-      backtrace \"\$*\" no_exit
-    }
-    error()
-    {
-      printf \"\\nERROR: \$*\\n\" >&2
-    }
-    exit()
-    {
-      builtin exit 0
-    }
-    trap \"backtrace \\\"A command has returned error code (\\\$?) without being handled.\\\" no_exit\" ERR
-    export PS1='(sm) [ret=\$?] \w > '
-  ") -i
-else
+[[ "${shell_version[1]}" == "bash," ]] && (( ${BASH_VERSINFO[0]} > 3 )) ||
   error "Unsuported shell:\n  ${shell_version[*]}\n\nUse bash 4 for console\n"
-fi
+
+trap - ERR
+${user_shell} --rcfile <(echo "
+  [[ -s ~/.bash_profile ]] && source ~/.bash_profile
+  [[ -s ~/.profile ]] && source ~/.profile
+  source ${sm_path}/core/sm/modules/shell/core/initialize
+  module ext/vcs
+  fail() { backtrace \"\$*\" no_exit ; }
+  error() { printf \"\\nERROR: \$*\\n\" >&2 ; }
+  exit() { builtin exit 0 ; }
+  trap \"backtrace \\\"A command has returned error code (\\\$?) without being handled.\\\" no_exit\" ERR
+  export PS1='(sm) [ret=\$?] \w > '
+") -i
+
diff --git a/core/cli/actions/open b/core/cli/actions/open
--- a/core/cli/actions/open
+++ b/core/cli/actions/open
@@ -1,15 +1,10 @@
 #!/usr/bin/env bash
 
-if array_is_nonempty extension_args
-then
-  if path_exists "${extensions_development_path}/${extension_args[0]}"
-  then
-    enter "${extensions_development_path}/${extension_args[0]}"
-
-    os_open "$PWD"
-  else
-    error "Failed to open '${extension_args[0]}'; it appears to not be installed."
-  fi
-else
+array_is_nonempty extension_args ||
   fail "You must specify at least one extension name."
-fi
+
+path_exists "${extensions_development_path}/${extension_args[0]}" ||
+  error "Failed to open '${extension_args[0]}'; it appears to not be installed."
+
+os_open "${extensions_development_path}/${extension_args[0]}"
+
diff --git a/core/cli/actions/src b/core/cli/actions/src
--- a/core/cli/actions/src
+++ b/core/cli/actions/src
@@ -1,15 +1,13 @@
 #!/usr/bin/env bash
 
-if array_is_nonempty extension_args
-then
-  if path_exists "${extensions_development_path}/${extension_args[0]}"
-  then
-    printf "${extensions_development_path}/${extension_args[0]}"
-  else
-    printf "." # Stay put!
-    error "Failed to edit '${extension_args[0]}'; it appears to not be installed."
-  fi
-else
+array_is_nonempty extension_args ||
   fail "You must specify at least one extension name."
+
+if path_exists "${extensions_development_path}/${extension_args[0]}"
+then
+  printf "${extensions_development_path}/${extension_args[0]}"
+else
+  printf "." # Stay put!
+  error "Failed to edit '${extension_args[0]}'; it appears to not be installed."
 fi
 
diff --git a/core/cli/modules/shell/dev/dsl b/core/cli/modules/shell/dev/dsl
--- a/core/cli/modules/shell/dev/dsl
+++ b/core/cli/modules/shell/dev/dsl
@@ -65,12 +65,11 @@ sm_development_setup()
           ;;
       esac
 
-      if git clone ${_url} ${_component}
-      then
-        log "  * ${_component} repository successfully cloned into $PWD/${_component}/."
-      else
+      # TODO: Switch to using fetch_uri here.
+      git clone ${_url} ${_component} ||
         error "There was an error cloning ${_component} repository from ${_url} into ${PWD}/${_component}."
-      fi
+
+      log "  * ${_component} repository successfully cloned into $PWD/${_component}/."
     fi
   done
 
@@ -103,13 +102,10 @@ extension_package()
   do
     if command_exists ${archiver// *}
     then
-      if tar cf "${_name}-${_version}.tar" "${_name}/"
-      then
-        # TODO: parallelize this.
-        ${archiver} -f -9 "${_name}-${_version}.tar"
-      else
-        error "There was an error during packaging ($?) while trying to create a tar of the '${_name}' directory."
-      fi
+      tar cf "${_name}-${_version}.tar" "${_name}/" ||
+        error "Error during packaging ($?) whilst trying to create a tar of the '${_name}' directory."
+
+      ${archiver} -f -9 "${_name}-${_version}.tar" # TODO: parallelize this.
     fi
 
     ensure_paths_exist "${_path}/pkg"
@@ -146,21 +142,20 @@ extension_publish()
 
   for formats in ".tar.gz" ".tar.bz2" ".tar.xz"
   do
-    if path_exists "${_path}/pkg/"
-    then
-      log "publishing ${_name}-${_version}"
+    path_exists "${_path}/pkg/" ||
+    error "The local package path '${_path}' does not exist; did you run"\
+      "'extension package ${_name}' before 'extension publish ${_name}'?"
 
-      for file in "${_pth}/${_name}-${_version}".tar.{gz,xz,bz2}
-      do
-        log "  - ${file}"
-        log "  - ${file}.md5"
-        NIY "publishing"
-      done
-    else
-      error "The local package path '${_path}' does not exist; did you run"\
-        "'extension package ${_name}' before 'extension publish ${_name}'?"
-    fi
+    log "publishing ${_name}-${_version}"
+
+    for file in "${_pth}/${_name}-${_version}".tar.{gz,xz,bz2}
+    do
+      log "  - ${file}"
+      log "  - ${file}.md5"
+      NIY "publishing"
+    done
   done
+
   log "Packaging complete. (Packages are located in '${_path}/pkg' )"
 }
 
