Added "bdsm ext package {extension name}" feature.

diff --git a/modules/bash/extensions/dsl b/modules/bash/extensions/dsl
--- a/modules/bash/extensions/dsl
+++ b/modules/bash/extensions/dsl
@@ -191,65 +191,6 @@ extension_action()
 }
 
 #
-# ### extensions_install()
-#
-# Installs the given extensions.
-#
-# ##### Input Parameters
-#
-# One or more extension names.
-#
-# ##### Stream Outputs
-#
-# None.
-#
-# ##### Environmental effects
-#
-# The named extensions will be installed to the filesystem in the BDSM
-# extensions directory.
-#
-# ##### Return Codes
-#
-# 0 for success
-#
-# ##### Failure Scenarios
-#
-# Fails if no extensions are passed in to install.
-#
-# ##### Usage Examples
-#
-#     user$ extensions_install libevent tmux
-#
-extensions_install()
-{
-  local _extension
-  local _extensions=("$@")
-
-  (( ${#_extensions[@]} > 0 )) ||
-    fail "Cannot install extensions as no extensions were given to install."
-
-  for _extension in "${_extensions[@]}"
-  do
-    case "${_extension#\/}" in
-      ext|srv|pkg|core|mod) continue ;;
-    esac
-
-    [[ -n "${_extension}" ]] || continue
-
-    extension_src_path="${extensions_src_path}/${_extension}"
-
-    # TODO: Install extension dependencies?
-
-    if [[ -s "${extension_src_path}/VERSION" && -x "${extension_src_path}/bin/help" ]]
-    then
-      copy_directories_to "${bdsm_path}/extensions" "${extension_src_path}"
-    else
-      error "${extension_src_path}/${extension} is not a proper extension.\nIt is missing one or more of the VERSION or bin/help."
-    fi
-  done
-}
-
-#
 # ### extension_reload()
 #
 # Reloads (re-sources) the current extension's DSL and initialization files.
@@ -758,5 +699,210 @@ extension_is_installed()
       return 1
       ;;
   esac
+}
+
+
+#
+# ### extensions_install()
+#
+# Installs the given extensions.
+#
+# ##### Input Parameters
+#
+# One or more extension names.
+#
+# ##### Stream Outputs
+#
+# None.
+#
+# ##### Environmental effects
+#
+# The named extensions will be installed to the filesystem in the BDSM
+# extensions directory.
+#
+# ##### Return Codes
+#
+# 0 for success
+#
+# ##### Failure Scenarios
+#
+# Fails if no extensions are passed in to install.
+#
+# ##### Usage Examples
+#
+#     user$ extensions_install libevent tmux
+#
+extensions_install()
+{
+  local _extension
+  local _extensions=("$@")
+
+  if (( ${#_extensions[@]} == 0 ))
+  then
+    fail "Cannot install extensions as no extensions were given to install."
+  fi
+
+  for _extension in "${_extensions[@]}"
+  do
+    case "${_extension#\/}" in
+      ext|srv|pkg|core|mod)
+        continue # Skip core extensions.
+        ;;
+    esac
+
+    if [[ -z "${_extension}" ]]
+    then # Skip any empty extensions / 'artifact'.
+      continue
+    else
+      extension_install "${_extension}"
+    fi
+  done
+}
+
+#
+# ### extension_install()
+#
+# Installs the given extension.
+#
+# ##### Input Parameters
+#
+# First parameter is the name of the extension to install
+#
+# ##### Stream Outputs
+#
+# None.
+#
+# ##### Environmental effects
+#
+# The named extension will be installed to the filesystem in the BDSM
+# extension directory.
+#
+# ##### Return Codes
+#
+# 0 for success
+#
+# ##### Failure Scenarios
+#
+# Fails if no extension are passed in to install.
+#
+# ##### Usage Examples
+#
+#     user$ extension_install redis
+#
+extension_install()
+{
+  local _extension="${1:-}"
+
+  if [[ -z "${_extension}" ]]
+  then
+    fail "Cannot install an extension as no extension name was given."
+  fi
+
+  true "${extensions_url:="${extensions_repository_url:-}"}"
+
+  # TODO: source path
+  if [[ -n "${extension_url}" ]]
+  then
+    extension_fetch "${extension_url}"
+    extension_source="${extension_url}"
+  else # Extension comes from the default repository.
+    # TODO: Merge this with the above, use the default url as the base.
+    extension_src_path="${extensions_src_path}/${_extension}"
+    extension_source="${extensions_src_path}"
+  fi
+
+  # TODO: Install extension dependencies?
+  if extension_is_valid "${extension_src_path}"
+  then
+    copy_directories_to "${bdsm_path}/extensions" "${extension_src_path}"
+    # TODO: Now record the source of the extension.
+    log "${extension_url:-"${extensions_src_path}"}" > "${bdsm_path}/extensions/${_extension}"
+  else
+    warn "${extension_src_path} is not a proper extension.\nIt is missing VERSION and/or bin/help. Skipping installation of ${_extension}."
+  fi
+}
+
+extension_fetch()
+{
+  local _url="${1:-$extension_url}"
+  local _identifier="${_url//\//_}" # Convert '/' to an invalid url component '_'
+  local repo_path="${repos_path}/${_identifier}"
+
+  if [[ -z "${_url}" ]]
+  then
+    fail "Cannot fetch an extension from a url as no url was given"
+  fi
+
+   # TODO: scm fetch vs tarball fetch
+  scm_fetch "${_url}"
+
+  scm_update "${_url}"
+
+  extension_src_path="${repo_path}"
+}
+
+extension_is_valid()
+{
+  local _path="${1:-}"
+
+  if [[ -z "${_path}" ]]
+  then
+    fail "Cannot determine if an extension is valid as the path to the extension was not given."
+  fi
+
+  # TODO: Add all extension requirement checks here.
+  if [[ -s "${_path}/VERSION" && -x "${_path}/bin/help" ]]
+  then
+    return 0
+  else
+    return 1
+  fi
+}
+
+extension_package()
+{
+  local _name="${1:-}"
+
+  if [[ -z "${_name}" ]]
+  then
+    fail "Cannot package an extension as no extension name was given."
+  fi
+
+  local _path="${extensions_development_path:-"$extensions_src_path"}"
+
+  enter "${_path}"
+
+  if extension_is_valid "${_path}/${_name}"
+  then
+    local _version="$(cat "${_name}/VERSION")"
+    log "Packaging extension ${_name}"
+    log "${_name}-${_version}:"
+
+    for archiver in "gzip" "bzip2 -z" "xz -z"
+    do
+      if command_exists ${archiver// *}
+      then
+        if tar cf "${_name}-${_version}.tar" "${_name}/"
+        then
+          ${archiver} -f -9 "${_name}-${_version}.tar"
+        else
+          error "There was an error ($?) while trying to create a tar of the '${_name}' directory while packaging."
+        fi
+      fi
+
+      ensure_paths_exist "${_path}/pkg"
+      for file in "${_name}-${_version}".tar.*
+      do
+        log "  - ${file}"
+        file_md5 "${file}" > "${file}.md5"
+        log "  - ${file}.md5"
+        move_files --force "${file}" "${file}.md5" to "${_path}/pkg"
+      done
+    done
+
+    log "Packaging complete (packages are located in '${_path}/pkg' )"
+  else
+    error "Cannot package extension '${_name}' as the extension is not valid."
+  fi
 }
 
diff --git a/modules/bash/filesystem/dsl b/modules/bash/filesystem/dsl
--- a/modules/bash/filesystem/dsl
+++ b/modules/bash/filesystem/dsl
@@ -917,6 +917,8 @@ move_files_to()
     shift
   fi
 
+  log "DEPRECIATED, use 'move_files ... to _path' instead"
+
   local _files=("$@")
 
   if (( ${#_files[@]} > 0 ))
@@ -931,6 +933,106 @@ move_files_to()
     if file_exists "${_file}"
     then
       mv "${_file}" "${_path}/${_file}"
+    else
+      error "Cannot move file ${_file} to ${_path} as the file does not exist."
+    fi
+  done
+}
+
+#
+# ## move_files
+#
+# Moves a given list of files into the named path.
+#
+# ##### Input Parameters
+#
+# Parameters are file name/path for one or more files
+# Target directory is specified as 'to {{path}}'
+# Optional source directory is specified as 'from {{path}}'
+# Optional force flag '--force' may be specified
+#
+# ##### Stream Outputs
+#
+# None.
+#
+# ##### Environmental effects
+#
+# If successful, all named files are copied into the target path.
+#
+# ##### Return Codes
+#
+# 0 for success.
+#
+# ##### Failure Scenarios
+#
+# Fails if no target path is given.
+# Fails if no files are given.
+#
+# ##### Usage Examples
+#
+#     user$ move_files "$HOME/.bashrc" "$HOME/.bash_profile" to "$HOME/backup"
+#
+# Alternatively,
+#
+#     user$ move_files ".bashrc" ".bash_profile" from "$HOME" to "$HOME/backup"
+#
+move_files()
+{
+  local _source _target _file _force_flag=0 _files=()
+
+  while (( $# > 0 ))
+  do
+    token="$1"
+    shift
+
+    case "${token}" in
+      to)
+        _target="${1}"
+        shift
+        ;;
+      from)
+        _source="${1}"
+        shift
+        ;;
+      --force)
+        _force_flag=1
+        ;;
+
+      *)
+        _files+=( "${token}" )
+        ;;
+    esac
+  done
+
+  if [[ -z "${_target}" ]]
+  then
+    fail "Cannot move files as no target path was given (eg. move_files ... to {path})."
+  else
+    shift
+  fi
+
+  if (( ${#_files[@]} == 0 ))
+  then
+    fail "Cannot move files as no files were given to move."
+  fi
+
+  ensure_paths_exist "${_target}"
+
+  for _file in "${_files[@]}"
+  do
+    if [[ -n "${_source}" ]]
+    then
+      _file="${_source}/${_file}"
+    fi
+
+    if file_exists "${_file}"
+    then
+      if (( _force_flag == 1 ))
+      then
+        mv -f "${_file}" "${_target}/${_file//*\/}"
+      else
+        mv "${_file}" "${_target}/${_file//*\/}"
+      fi
     else
       error "Cannot move file ${_file} to ${_path} as the file does not exist."
     fi
@@ -2390,17 +2492,7 @@ file_matches_md5()
     return 1
   fi
 
-  if os_is_linux
-  then
-    _command="md5sum"
-  elif os_is_darwin
-  then
-    _command="/sbin/md5 -q"
-  else
-    _command="md5" # ... ?
-  fi
-
-  _file_md5="$($_command "$_file")"
+  _file_md5="$(file_md5 "${_file}")"
 
   if [[ "${_file_md5// *}" = "$_md5" ]]
   then
@@ -2410,3 +2502,84 @@ file_matches_md5()
   fi
 }
 
+extract_archive()
+{
+  local _archive="${1:-}"
+
+  if [[ -z "${_archive}" ]]
+  then
+    fail "Cannot extract an archive to a target location as no archive was given."
+  else
+    shift
+  fi
+
+  local _path="${1:-}"
+
+  case "${archive}" in
+    *.tar.gz|*.tgz) # gzip
+      if ! tar zxf "${archive}"
+      then
+        error "There was an error while extracting the archive '${archive}'"
+      fi
+      ;;
+    *tar.xz) # LZMA
+      # TODO: if 'xz' command exists, use that, otherwise use tar J
+      if ! tar Jxf "${archive}"
+      then
+        error "There was an error while extracting the archive '${archive}'"
+      fi
+      ;;
+    *.tar.bz2) # bzip
+      if ! tar jxf "${archive}"
+      then
+        error "There was an error while extracting the archive '${archive}'"
+      fi
+      ;;
+    *.zip)
+      if ! unzip "${archive}" -d "${_path:-}"
+      then
+        error "There was an error while extracting the archive '${archive}'"
+      fi
+      ;;
+    *)
+      error "Unknown archive format for ${archive}"
+      ;;
+  esac
+}
+
+file_md5()
+{
+  local _file="${1:-}" _command _md5
+
+  if [[ -z "${_file}" ]]
+  then
+    fail "Cannot calculate md5 of a file as no file name/path was given."
+  fi
+
+  if os_is_darwin
+  then
+    _command="/sbin/md5 -q"
+
+  else
+    if command_exists "md5sum"
+    then
+      _command="md5sum"
+
+    elif command_exists md5
+    then
+      _command="md5"
+
+    else
+      error "Could not find a suitable md5 command in the path."
+    fi
+  fi
+
+  if _md5="$(${_command} "$_file" 2>/dev/null)"
+  then
+    printf "${_md5// *}"
+
+  else # Should this be error ?
+    warn "There was an unknown error computing the md5"
+    return 1
+  fi
+}
