cleaning extensions

diff --git a/core/internal/shell/extensions/manipulation/functions b/core/internal/shell/extensions/manipulation/functions
--- a/core/internal/shell/extensions/manipulation/functions
+++ b/core/internal/shell/extensions/manipulation/functions
@@ -42,7 +42,8 @@ extension_license()
 {
   local _extension="${1:-${extension}}"
 
-  [[ -n "${_extension}" ]] || fail "Cannot display extension license;"\
+  variable_is_nonempty _extension ||
+    fail "Cannot display extension license;"\
     " Extension name was not given."
 
   cat -v "${extensions_path}/${_extension}/LICENSE"
@@ -53,14 +54,14 @@ extension_license()
 #      $ cat $HOME/test
 #      #!/bin/sm
 #      modules api/extensions/manipulation
-#      __sm.extensions.actions "postgresql"
+#      __sm.extension.actions "postgresql"
 #
 #      $ $HOME/test
 #      backup configure help initialize install restart start status stop uninstall upgrade
 #
 #
 #
-__sm.extensions.actions()
+__sm.extension.actions()
 {
   local _extension="${1:-}" _files _file _actions=()
   shift || fail "No extension was given."
@@ -85,39 +86,49 @@ __sm.extensions.actions()
 
 # ### Usage Examples
 #
-#     user$ __sm.extensions.install backup mpapis_sm_backup
+#     user$ sm --call=internal/extensions/manipulation/__sm.extension.install backup mpapis/sm_backup
 #
-__sm.extensions.install()
+__sm.extension.install()
 {
-  # TODO: This should likely be removed now with sets/ext ?
+  local _name="${1:-}"
+  shift || fail "No extension name was given."
 
-  local _extension="${1:-}" _src="${2:-${_extension}}"
-  shift || fail "Cannot install extension;"\
-    " No extension name was given."
+  local _uri="${1:-}"
+  shift || _uri=$( awk -F= "/^${_name}=/ {print \$2 }" < "${sm_path}/core/cli/config/known_ext" | tail -n 1 )
 
-  __sm.extensions.are.valid "${extensions_src_path}/${_src}" ||
-    error "${extensions_src_path}/${_src} is not a valid extension;"\
-    "It is missing modules/ and/or bin/ files."
+  [[ -n "${_uri}" ]] ||
+    error "uri not given and cannot find ${_name} in known extensions."
 
-  log "Installing ${_extension}"
-
-  if paths exists "${sm_path}/exts/${_extension}"
+  local _version="head"
+  if [[ "${_name}" == *:* ]]
   then
-    paths remove "${sm_path}/exts/${_extension}"
+    _version="${_name/*:}"
   fi
 
-  paths copy \
-    from "${extensions_src_path}/${_src}" \
-    to "${sm_path}/exts/${_extension}"
+  local _identifier="$(scm_identifier "${_uri}")"
 
-  files write string "${extension_uri}" to "${sm_path}/exts/${_extension}/.uri"
+  if fetch_uri "${_uri}" "${src_path}/${_identifier}" "$@"
+  then
+    __sm.extension.is.valid "${src_path}/${_identifier}" ||
+      error "${src_path}/${_identifier} is not a valid extension;"\
+      "It is missing modules/ and/or bin/ files."
 
-  #
-  # TODO: Process extension dependencies...
-  #
+    #
+    # TODO: Process extension dependencies...
+    #
+
+    versionedfs add \
+      path "${exts_user_path}" name "${_name}" version "${_version}" \
+      source "${src_path}/${_identifier}"
+
+    versionedfs activate \
+      path "${exts_user_path}" name "${_name}" version "${_version}"
+  else
+    return $?
+  fi
 }
 
-__sm.extensions.installed()
+__sm.extension.installed()
 {
   local _token _type _modules _paths=() _excludes=() _exclude
 
