More work on the core.

diff --git a/extensions/rails/bin/setup b/extensions/rails/bin/setup
--- a/extensions/rails/bin/setup
+++ b/extensions/rails/bin/setup
@@ -18,37 +18,41 @@ done
 # Sanity checks
 #
 if [[ "root" = $(whoami) ]] ; then
-  $scripts_path/log "error" "bdsm extension $extension must be run as the project user and NOT root." ; exit 1
+  $scripts_path/log "error" "bdsm extension $extension must be run as the project user and NOT root."
+  exit 1
 fi
 
-mkdir -p $shared_path
+touch "$HOME/.bash_profile" "$HOME/.bdsmrc"
 
 if [[ -z "$project" ]] ; then
-  $scripts_path/log "error" "$variable must be set for extension $extension." ; exit 1
+  $scripts_path/log "error" "project variable must be set for extension $extension."
+  exit 1
 else
-  if ! awk "/^project/" "$HOME/.bash_profile" ; then
-    echo "export project=\"$(user)\"" >> $HOME/.bdsmrc
+  if ! awk "/^project=/" "$HOME/.bash_profile" ; then
+    printf "\nexport project=\"${project:-$user}\"\n" >> $HOME/.bdsmrc
   fi
 fi
 
 if [[ -z "$environment" ]] ; then
-  $scripts_path/log "error" "$variable must be set for extension $extension." ; exit 1
+  $scripts_path/log "error" "environment variable must be set for extension $extension."
+  exit 1
 else
-  if ! awk "/^environment/" "$HOME/.bash_profile" ; then
-    echo "export environment=\"$environment\"" >> $HOME/.bdsmrc
+  if ! awk "/^environment=/" "$HOME/.bash_profile" ; then
+    printf "\nexport environment=\"$environment\"\n" >> $HOME/.bdsmrc
   fi
 
-  if ! awk "/^RAILS_ENV/" "$HOME/.bash_profile" ; then
-    echo "export RAILS_ENV=\"$environment\"" >> $HOME/.bdsmrc
+  if ! awk "/^RAILS_ENV=/" "$HOME/.bash_profile" ; then
+    printf "\nexport RAILS_ENV=\"$environment\"\n" >> $HOME/.bdsmrc
   fi
 fi
 
 if [[ ! -z "$repo" ]] ; then
-  if ! awk "/^repo/" "$HOME/.bash_profile" ; then
-    echo "export repo=\"$repo\"" >> $HOME/.bdsmrc
+  if ! awk "/^repo=/" "$HOME/.bash_profile" ; then
+    printf "\nexport repo=\"$repo\"\n" >> $HOME/.bdsmrc
   fi
 
-  cd $shared_path
+  mkdir -p "$shared_path" && cd "$shared_path"
+
   if [[ "$scm" = "git" ]] || (echo $repo | awk "/git/") ; then
     if [[ ! -d "$shared_path/$project/.git" ]] ; then
       git clone $repo $project
@@ -66,14 +70,14 @@ if [[ ! -z "$repo" ]] ; then
   fi
 fi
 
-for dir in config log pids sockets "public/assets" tmp  ; do
+for dir in config log pids sockets "public/assets" tmp ; do
   mkdir -p "$project_path/shared/$dir"
 done
 
 #
 # Ensure the .bdsmrc file and the profiles are setup properly.
 #
-touch $project_path/shared/config/database.yml $project_path/.bash_profile
+touch "$shared_path/config/database.yml"
 
 if [[ ! -z "$database" ]] ; then
   if ! awk "/^database/" "$HOME/.bash_profile" ; then
@@ -81,42 +85,58 @@ if [[ ! -z "$database" ]] ; then
   fi
 fi
 
-if ! awk '/current\/\.bdsmrc/' "$HOME/.bash_profile" ; then
-  echo 'if [[ -d $HOME/current ]] && [[ -f $HOME/current/.bdsmrc ]] ; then source $HOME/current/.bdsmrc ; fi' >> $HOME/.bash_profile
+if ! awk '/current\/\.bdsmrc/' "$HOME/.bashrc" ; then
+  echo '[[ -s "$HOME/.bdsmrc" ]] && . "$HOME/current/.bdsmrc"' >> $HOME/.bash_profile
+fi
+
+if ! awk '/current\/\.bashrc/' "$HOME/.bash_profile" ; then
+  echo '[[ "-s $HOME/.bashrc" ]] && . "$HOME/current/.bashrc"' >> $HOME/.bash_profile
 fi
 
 if ! awk '/current\/\.rvmrc/' "$HOME/.bash_profile" ; then
-  echo 'if [[ -d $HOME/current ]] && [[ -f $HOME/current/.rvmrc ]] ; then source $HOME/current/.rvmrc ; fi' >> $HOME/.bash_profile
+  echo '[[ "-d $HOME/current" ]] && [[ -f "$HOME/current/.rvmrc" ]] && . "$HOME/current/.rvmrc"' >> $HOME/.bash_profile
 fi
-cp $HOME/.bash_profile $HOME/.bashrc
 
 if [[ ! -s "$HOME/.rvm/scripts/rvm" ]] ; then
   mkdir -p $HOME/.rvm/src ; cd $HOME/.rvm/src
   if [[ -d rvm/.git ]] ; then
-    cd rvm
-    git reset --hard HEAD
-    git pull origin "${rvm_branch:-master}"
+    cd rvm &&
+    git reset --hard HEAD &&
+    git pull origin "${rvm_branch:-master}" &&
     ./install
   else
-    git clone git://github.com/wayneeseguin/rvm.git && cd rvm && ./install
+    git clone git://github.com/wayneeseguin/rvm.git &&
+    cd rvm &&
+    ./install
   fi
   cd $HOME
 fi
 
 if [[ ! -s "$project_path/shared/config/database.yml" ]] ; then
-  echo -e "${environment}: &defaults\n  adapter: ${database:-postgresql}\n  username: $project\n  password: '$project'\n  database: ${project}_${environment}\n  pool: 5\n  timeout: 5000" > "$project_path/shared/config/database.yml"
+  printf "\n${environment}: &defaults\n  adapter: ${database:-postgresql}\n  username: $project\n  password: '$project'\n  database: ${project}_${environment}\n  pool: 5\n  timeout: 5000\n" > "$shared_path/config/database.yml"
+  if [[ "$database" = "mysql" ]] ; then
+    printf "\n  socket: ${socket:-/tmp/mysql.sock}\n  encoding: utf8\n" >> "$shared_path/config/database.yml"
+  fi
 fi
 
-if [[ -d "$project_path/shared/$project/" ]] && [[ -s "$project_path/shared/$project/.rvmrc" ]] ; then
+if [[ -d "$shared_path/$project/" ]] && [[ -s "$shared_path/$project/.rvmrc" ]] ; then
   export rvm_install_on_use_flag=1
-  "source $project_path/shared/$project/.rvmrc"
+  . "$shared_path/$project/.rvmrc"
 fi
 
 if [[ ! -z "$database" ]] && command -v gem > /dev/null; then
   if [[ "postgresql" = "$database" ]] ; then
     gem install pg --no-rdoc --no-ri
+    if [[ "$?" -ne 0 ]] ; then
+      pg_config=$(command -v pg_config)
+      gem install pg --no-rdoc --no-ri -- --with-pg-config=${pg_config:-/usr/local/postgresql/bin/pg_config}
+    fi
   elif [[ "mysql" = "$database" ]] ; then
     gem install mysql --no-rdoc --no-ri
+    if [[ "$?" -ne 0 ]] ; then
+      mysql_config=$(command -v mysql_config)
+      gem install mysql --no-rdoc --no-ri -- --with-mysql-config=${mysql_config:-/usr/local/mysql/bin/mysql_config}
+    fi
   else
     gem install sqlite --no-rdoc --no-ri
   fi
@@ -128,8 +148,11 @@ if [[ ! -z "$server" ]] ; then
     "$bin_path/bdsm unicorn setup"
   elif [[ "mongrel" = "$server" ]] ; then
     "$bin_path/bdsm mongrel setup"
+  elif [[ "mongrel2" = "$server" ]] ; then
+    "$bin_path/bdsm mongrel2 setup"
   elif [[ "thin" = "$server" ]] ; then
     "$bin_path/bdsm thin setup"
   fi
 fi
 
+exit $?
