Cleaner handling of missing extension. Improved logging.

diff --git a/extensions/ext/bin/create b/extensions/ext/bin/create
--- a/extensions/ext/bin/create
+++ b/extensions/ext/bin/create
@@ -1,30 +1,35 @@
 #!/usr/bin/env bash
 
-(( ${#extension_args[@]} > 0 )) ||
+if (( ${#extension_args[@]} > 0 ))
+then
+  target_path="${extensions_development_path:-"$initial_pwd"}"
+
+  for extension in ${extension_args[@]} ; do
+
+    if directory_exists "${target_path}/${extension}"
+    then
+      error "Extension '${extension}' already exists at ${target_path}/${extension}."
+    fi
+
+    if ! directory_exists "${extensions_path}/ext/templates/${language:-bash}"
+    then
+      fail "Extension template files for are missing from $target_path/ext/templates/${language:-bash}."
+    fi
+
+    (
+    enter "${extensions_path}/ext/templates/${language:-bash}"
+
+    copy_directories_to "${target_path}/${extension}/" \
+      bin modules templates config
+
+    copy_files_to "$target_path/$extension/" \
+      README.md VERSION CHANGELOG.md TODO.md
+    )
+
+    log "Extension created from template at ${target_path}/${extension}/"
+  done
+
+  succeed "Created extensions ${extension_args[@]}"
+else
   fail "At least one extension name must be specified."
-
-target_path="${extensions_development_path:-"$initial_pwd"}"
-
-for extension in ${extension_args[@]} ; do
-
-  [[ -d "${target_path}/${extension}" ]] &&
-    fail "Extension '${extension}' already exists at ${target_path}/${extension}."
-
-  [[ -d "${extensions_path}/ext/templates/${language:-bash}" ]] ||
-    fail "Extension template files for are missing from $target_path/ext/templates/${language:-bash}."
-
-  (
-  enter "${extensions_path}/ext/templates/${language:-bash}"
-
-  copy_directories_to "${target_path}/${extension}/" \
-    bin modules templates config
-
-  copy_files_to "$target_path/$extension/" \
-    README.md VERSION CHANGELOG.md TODO.md
-  )
-
-  log "Extension created from template at ${target_path}/${extension}/"
-
-done
-
-succeed "Created extensions ${extension_args[@]}"
+fi
diff --git a/extensions/ext/bin/src b/extensions/ext/bin/src
--- a/extensions/ext/bin/src
+++ b/extensions/ext/bin/src
@@ -1,6 +1,13 @@
 #!/usr/bin/env bash
 
-(( ${#extension_args[@]} > 0 )) ||
-  fail "An extension name must be specified."
+(( ${#extension_args[@]} > 0 )) || fail "An extension name must be specified."
 
-printf "${extensions_development_path}/${extension_args[0]}"
+
+if directory_exists "${extensions_development_path}/${extension_args[0]}"
+then
+  printf "${extensions_development_path}/${extension_args[0]}"
+else
+  printf "." # Stay put!
+  error "Failed to edit '${extension_args[0]}' as it appears to not be installed. Installed extensions are,\n$(installed_extensions)"
+fi
+
diff --git a/modules/bash/core/cli b/modules/bash/core/cli
--- a/modules/bash/core/cli
+++ b/modules/bash/core/cli
@@ -67,7 +67,6 @@ while (( $# > 0 )) ; do
           ;;
         *)
           error "Unknown flag '${token}'"
-          exit 1
           ;;
       esac
       ;;
@@ -153,10 +152,7 @@ while (( $# > 0 )) ; do
               ;;
 
             *)
-              [[ -z "${extension}" ]] || {
-                error "Extension '${token}' not found"
-                exit 1
-              }
+              [[ -z "${extension}" ]] || error "Extension '${token}' not found"
               ;;
           esac
         fi
