Some cleansing, some removal of external processes.

diff --git a/core/ext/modules/shell/array/functions b/core/ext/modules/shell/array/functions
--- a/core/ext/modules/shell/array/functions
+++ b/core/ext/modules/shell/array/functions
@@ -65,8 +65,7 @@ array_is_nonempty()
 {
   trace_filter array
   local _array_name="${1:-}"
-  shift || fail "Cannot determine if an array is nonempty;"\
-    "Array name was not given."
+  shift || fail "Array name was not given."
 
   eval "(( \${#${_array_name}[@]} > 0 ))"
 }
@@ -110,8 +109,7 @@ array_is_empty()
 {
   trace_filter array
   local _array_name="${1:-}"
-  shift || fail "Cannot push onto array;"\
-    "Array name was not given."
+  shift || fail "Array name was not given."
   eval "(( \${#${_array_name}[@]} == 0 ))"
 }
 
@@ -148,8 +146,7 @@ array_length()
 {
   trace_filter array
   local _array_name="${1:-}" _length
-  shift || fail "Cannot determine array length;"\
-    "Array name was not given."
+  shift || fail "Array name was not given."
   eval "_length=\${#${_array_name}[@]}"
   printf ${_length}
   return 0
@@ -188,7 +185,7 @@ array_last_element()
 {
   trace_filter array
   local _array_name="${1:-}" _length _element
-  shift || fail "Cannot print last element of array; Array name was not given."
+  shift || fail "Array name was not given."
 
   eval "_length=\${#${_array_name}[@]}"
   eval "_element=\"\${${_array_name}[${_length}]}\""
@@ -230,8 +227,7 @@ array_first_element()
   trace_filter array
   local _array_name="${1:-}" _element _array_length
 
-  shift || fail "Cannot print the first element of array;"\
-    "Array name was not given."
+  shift || fail "Array name was not given."
 
   eval "_array_length=\"\${#${_array_name}[@]}\""
   (( _array_length )) || return 1
@@ -275,15 +271,13 @@ array_push()
 {
   trace_filter array
   local _array_name="${1:-}"
-  shift || fail "Cannot push elements onto array;"\
-    " Array name not given."
+  shift || fail "Array name not given."
 
   if eval "(( \${#${_array_name}[@]} > 0 ))"
   then
     local _element _elements=("$@")
 
-    (( ${#_elements[@]} )) || fail "Cannot push elements onto array;"\
-      " No elements were given."
+    (( ${#_elements[@]} )) || fail "No elements were given."
 
     for _element in "${_elements[@]}"
     do
@@ -328,13 +322,11 @@ array_append()
 {
   trace_filter array
   local _array_name="${1:-}"
-  shift || fail "Cannot append elements to array;"\
-    " No array name was given."
+  shift || fail "No array name was given."
 
   local _element _elements=("$@")
 
-  (( ${#_elements[@]} )) || fail "Cannot append elements to array;"\
-    " No elements were given."
+  (( ${#_elements[@]} )) || fail "No elements were given."
 
   for _element in "${_elements[@]}"
   do
@@ -379,11 +371,10 @@ array_pop()
 
   local _array_name="${1:-}" temp_array=() index _variable="${2:-}"
 
-  shift || fail "Cannot pop element from array;"\
-    " Array name was not given."
+  shift || fail "Array name was not given."
 
   eval "(( \${#${_array_name}[@]} ))" ||
-    fail "Cannot pop from array; Array '${_array_name}' was empty."
+    fail "Array '${_array_name}' was empty."
 
   variable_is_empty _variable ||
     eval "${_variable}=\${${_array_name}[\${#${_array_name}[@]}-1]}"
@@ -428,7 +419,7 @@ array_shift()
 {
   trace_filter array
   local _array_name="${1:-}" temp_array=() index _variable="${2:-}"
-  shift || fail "Cannot shift array; Array name was not given."
+  shift || fail "Array name was not given."
 
   variable_is_empty _variable || eval "${_variable}=\${${_array_name}[0]}"
 
@@ -474,13 +465,11 @@ array_unshift()
 {
   trace_filter array
   local _array_name="${1:-}"
-  shift || fail "Cannot unshift elements onto array;"\
-    "Array name was given."
+  shift || fail "Array name was given."
 
   local _elements=("$@")
 
-  (( ${#_elements[@]} )) || fail "Cannot unshift elements into array;"\
-    " No elements were given."
+  (( ${#_elements[@]} )) || fail "No elements were given."
 
   eval "${_array_name}=(\"${_elements[@]}\" \"\${${_array_name}[@]}\")"
 }
@@ -525,7 +514,7 @@ array_join()
 {
   trace_filter array
   local _array_name="${1:-}"
-  shift || fail "Cannot join array; Array name was not given."
+  shift || fail "Array name was not given."
   local IFS=${1:-' '}
   eval "printf \"\${${_array_name}[*]}\""
 }
@@ -563,8 +552,7 @@ array_largest()
 {
   trace_filter array
   local _array_name="${1:-}" _index _largest=""
-  shift || fail "Cannot find largest element;"\
-    "No array variable name was given."
+  shift || fail "No array variable name was given."
 
   eval "
   for (( _index=0 ; _index < \${#${_array_name}[@]} ; _index++ ))
@@ -618,8 +606,7 @@ array_sort_desc()
 {
   trace_filter array
   local _array_name="${1:-}" _index _largest=""
-  shift || fail "Cannot sort an array in decending order;"\
-    "Array variable name was not given."
+  shift || fail "Array variable name was not given."
 
   eval "${_array_name}=(\$(
   echo \"\${${_array_name}[@]}\" | sed -e 's/\s/\n/g' | sort -r
@@ -667,8 +654,7 @@ array_sort_asc()
   trace_filter array
   local _array_name="${1:-}" _index _largest=""
 
-  shift || fail "Cannot sort an array in ascending order;"\
-    " Array variable name was not given."
+  shift || fail "Array variable name was not given."
 
   eval "${_array_name}=(\$(
   echo \"\${${_array_name}[@]}\" | tr ' ' \"\n\" | sort
@@ -715,8 +701,7 @@ array_unique()
 {
   trace_filter array
   local _array_name="${1:-}" _index _largest=""
-  shift ||
-    fail "Cannot uniquify array; Array variable name was not given."
+  shift || fail "Array variable name was not given."
 
   eval "${_array_name}=(\$(
   echo \" \${${_array_name}[@]} \" |
@@ -799,8 +784,7 @@ array_is_even()
 {
   trace_filter array
   local _array_name="${1:-}"
-  shift || fail "Cannot determine if array is even;"\
-    " Array name was not given."
+  shift || fail "Array name was not given."
 
   eval "(( ( \${#${_array_name}[@]} % 2 ) == 0 ))"
 }
